Samchon Framework for CPP: samchon::library::GeneticAlgorithm< GeneArray, Compare > Class Template Reference
samchon::library::GeneticAlgorithm< GeneArray, Compare > Class Template Reference
A genetic algorithm class.
#include <GeneticAlgorithm.hpp>
Public Member Functions
GeneticAlgorithm (bool unique, double mutationRate=0.015, size_t tournament=10)
Construct from parameters of Genetic Algorithm.
auto evolveGeneArray (std::shared_ptr< GeneArray > geneArray, size_t population, size_t generation) const -> std::shared_ptr< GeneArray >
Evolve a GeneArray.
auto evolvePopulation (std::shared_ptr< Population > population) const -> std::shared_ptr< Population >
Evolve population, a mass of GeneArray(es)
Private Member Functions
auto selection (std::shared_ptr< Population > population) const -> std::shared_ptr< GeneArray >
Select the best GeneArray in population from tournament.
auto crossover (std::shared_ptr< GeneArray > &parent1, std::shared_ptr< GeneArray > &parent2) const -> std::shared_ptr< GeneArray >
Create a new GeneArray by crossing over two GeneArray(s)
void mutate (std::shared_ptr< GeneArray > geneArray) const
Cause a mutation on the GeneArray.
Private Attributes
bool unique
Whether each element (Gene) is unique in their GeneArray.
double mutationRate
Rate of mutate ocurrence.
size_t tournament
Size of tournament in selection.
Detailed Description
template<typename GeneArray, typename Compare = std::less<GeneArray>>
class samchon::library::GeneticAlgorithm< GeneArray, Compare >
A genetic algorithm class.
In the field of artificial intelligence, a genetic algorithm (GA) is a search heuristic that mimics the process of natural selection. This heuristic (also sometimes called a metaheuristic) is routinely used to generate useful solutions to optimization and search problems.
Genetic algorithms belong to the larger class of evolutionary algorithms (EA), which generate solutions to optimization problems using techniques inspired by natural evolution, such as inheritance, mutation, selection, and crossover.
Referenced Wikipedia: https://en.wikipedia.org/wiki/Genetic_algorithm
Template Parameters
GeneArray An array(std::vector) containing genes as elments; sequnce listing.
The GeneArray must be a type of std::vector.
Compare A comparison class (or struct) returns whether left gene is more optimal.
Default template parameter of Compare is std::less<GeneArray>. It means to compare two std::vector (GeneArray must be a std::vector). Thus, you've to keep follwing rules.
If you don't want to follow the rules or want a custom comparison class, you have to realize a comparison class. The following code is an example realizing the comparison class.
- GeneArray is inherited from <i>std::vector</i>
- GeneArray has custom <i>auto operator<(const GeneArray &) const -> bool</i>
template <typename _Ty>
struct MyCompare
{
auto operator()(const _Ty &newObj, const _Ty &prevObj) const -> bool;
};
Example source
TSP - Traveling Salesman Problem
examples/tsp/Scheduler.hpp
 #pragma once
 #include <vector>
 #include <memory>
 namespace samchon
 {
     namespace example
     {
         namespace tsp
         {
             class Travel;
             struct GAParameters
             {
                 double mutationRate;
                 size_t tornament;
                 size_t population;
                 size_t generation;
             };
             class Scheduler
             {
             private:
                 std::shared_ptr<Travel> travel;
                 struct GAParameters gaParameters;
             public:
                 Scheduler(std::shared_ptr<Travel>, const struct GAParameters &);
                 auto optimize() -> std::shared_ptr<Travel>;
             };
         };
     };
 };
examples/tsp/Travel.hpp
 #pragma once
 #include <vector>
 #include <string>
 namespace samchon
 {
     namespace example
     {
         namespace tsp
         {
             class GeometryPoint;
             class Travel
                 : public std::vector<GeometryPoint*>
             {
             private:
                 typedef std::vector<GeometryPoint*> super;
                 double distance;
             public:
                 /* -----------------------------------------------------------
                     CONSTRUCTORS
                 ----------------------------------------------------------- */
                 Travel();
                 Travel(const Travel&);
                 Travel(Travel&&);
             private:
                 /* -----------------------------------------------------------
                     CALCULATORS
                 ----------------------------------------------------------- */
                 auto calcDistance() const -> double;
             public:
                 auto operator<(const Travel &) const -> bool;
                 /* -----------------------------------------------------------
                     EXPORTER
                 ----------------------------------------------------------- */
                 auto toString() const -> std::string;
             };
         };
     };
 };
examples/tsp/GeometryPoint.hpp
 #pragma once
 #include <string>
 namespace samchon
 {
     namespace example
     {
         namespace tsp
         {
             class GeometryPoint
             {
             private:
                 int uid;
                 double longitude;
                 double latitude;
             public:
                 /* -----------------------------------------------------------
                     CONSTRUCTORS
                 ----------------------------------------------------------- */
                 GeometryPoint(int);
                 GeometryPoint(int, double, double);
                 /* -----------------------------------------------------------
                     CALCULATOR
                 ----------------------------------------------------------- */
                 auto calcDistance(const GeometryPoint &) const -> double;
                 /* -----------------------------------------------------------
                     EXPORTER
                 ----------------------------------------------------------- */
                 auto toString() const -> std::string;
             };
         };
     };
 };
examples/tsp/main.cpp
 #include <iostream>
 #include <Windows.h>
 #include "Scheduler.hpp"
 #include "Travel.hpp"
 #include "GeometryPoint.hpp"
 using namespace std;
 using namespace samchon::example::tsp;
 #ifdef _WIN64
 #   ifdef _DEBUG
 #       pragma comment(lib, "x64/Debug/SamchonFramework.lib")
 #   else
 #       pragma comment(lib, "x64/Release/SamchonFramework.lib")
 #   endif
 #else
 #   ifdef _DEBUG
 #       pragma comment(lib, "Debug/SamchonFramework.lib")
 #   else
 #       pragma comment(lib, "Release/SamchonFramework.lib")
 #   endif
 #endif
 void toClipboard(const string &);
 void main()
 {
     //GEOMETRY COORPORATES
     shared_ptr<Travel> travel(new Travel());
     for(int i = 0; i < 20; i++)
         travel->push_back(new GeometryPoint(i + 1));
     //OPTIMIZING
     struct GAParameters gaParameters = {.03, 50, 100, 300};
     Scheduler scheduler(travel, gaParameters);
     travel = scheduler.optimize();
     //PRINTING
     string &str = travel->toString();
     toClipboard(str);
     cout << str << endl;
     system("pause");
 }
 void toClipboard(const string &str)
 {
     OpenClipboard(0);
     EmptyClipboard();
     HGLOBAL hg = GlobalAlloc(GMEM_MOVEABLE, str.size());
     if (!hg)
     {
         CloseClipboard();
         return;
     }
     memcpy(GlobalLock(hg), str.c_str(), str.size());
     GlobalUnlock(hg);
     SetClipboardData(CF_TEXT, hg);
     CloseClipboard();
     GlobalFree(hg);
 }
examples/tsp/Scheduler.cpp
 #include "Scheduler.hpp"
 #   include "Travel.hpp"
 #include <samchon/library/GeneticAlgorithm.hpp>
 using namespace std;
 using namespace samchon::library;
 using namespace samchon::example::tsp;
 Scheduler::Scheduler(shared_ptr<Travel> travel, const GAParameters &gaParameteres)
 {
     this->travel = travel;
     this->gaParameters = gaParameteres;
 }
 auto Scheduler::optimize() -> shared_ptr<Travel>
 {
     GeneticAlgorithm<Travel> geneticAlgorithm
     (
         true,
         gaParameters.mutationRate,
         gaParameters.tornament
     );
     travel =
         geneticAlgorithm.evolveGeneArray
         (
             travel,
             gaParameters.population,
             gaParameters.generation
         );
     return travel;
 }
examples/tsp/Travel.cpp
 #include "Travel.hpp"
 #   include "GeometryPoint.hpp"
 #include <samchon/library/StringUtil.hpp>
 using namespace std;
 using namespace samchon::library;
 using namespace samchon::example::tsp;
 /* -----------------------------------------------------------
     CONSTRUCTORS
 ----------------------------------------------------------- */
 Travel::Travel()
     : super()
 {
     distance = INT_MIN;
 }
 Travel::Travel(const Travel &travel)
     : super(travel)
 {
     distance = INT_MIN;
 }
 Travel::Travel(Travel &&travel)
     : super(move(travel))
 {
     distance = travel.distance;
 }
 /* -----------------------------------------------------------
     CALCULATORS
 ----------------------------------------------------------- */
 auto Travel::calcDistance() const -> double
 {
     if(this->distance != INT_MIN)
         return this->distance;
     double distance = 0.0;
     for(size_t i = 1; i < size(); i++)
         distance += at(i-1)->calcDistance(*at(i));
     ((Travel*)this)->distance = distance;
     return distance;
 }
 auto Travel::operator<(const Travel &travel) const -> bool
 {
     return this->calcDistance() < travel.calcDistance();
 }
 /* -----------------------------------------------------------
     EXPORTER
 ----------------------------------------------------------- */
 auto Travel::toString() const -> string
 {
     string str =
         "Distance: " + StringUtil::numberFormat(calcDistance()) + " km\n" +
         "uid    longitude   latitude\n";
     for(size_t i = 0; i < size(); i++)
         str += at(i)->toString() + "\n";
     return move(str);
 }
examples/tsp/GeometryPoint.cpp
 #include "GeometryPoint.hpp"
 #include <random>
 #include <cmath>
 #include <samchon/library/Math.hpp>
 #include <samchon/library/StringUtil.hpp>
 using namespace std;
 using namespace samchon::library;
 using namespace samchon::example::tsp;
 /* -----------------------------------------------------------
     CONSTRUCTORS
 ----------------------------------------------------------- */
 GeometryPoint::GeometryPoint(int uid)
 {
     this->uid = uid;
     this->longitude = Math::random() * 180.0;
     this->latitude = Math::random() * 180 - 90.0;
 }
 GeometryPoint::GeometryPoint(int uid, double longitude, double latitude)
 {
     this->uid = uid;
     this->longitude = longitude;
     this->latitude = latitude;
 }
 /* -----------------------------------------------------------
     CALCULATOR
 ----------------------------------------------------------- */
 auto GeometryPoint::calcDistance(const GeometryPoint &point) const -> double
 {
     if (longitude == point.longitude && latitude == point.latitude)
         return 0.0;
     double latitude_radian1 = Math::degree_to_radian(this->latitude);
     double latitude_radian2 = Math::degree_to_radian(point.latitude);
     double theta = this->longitude - point.longitude;
     double val =
         sin(latitude_radian1) * sin(latitude_radian2)
         + cos(latitude_radian1) * cos(latitude_radian2) * cos(Math::degree_to_radian(theta));
     val = acos(val);
     val = Math::radian_to_degree(val);
     val = val * 60 * 1.1515;
     val = val * 1.609344;
     return val;
 }
 /* -----------------------------------------------------------
     EXPORTER
 ----------------------------------------------------------- */
 auto GeometryPoint::toString() const -> string
 {
     return StringUtil::substitute
         (
             "{1}\t{2}\t{3}",
             uid, longitude, latitude
         );
 }
Result of the example
Warning
Be careful for the mistakes of direction or position of Compare.
Most of logical errors failed to access optimal solution are occured by those mistakens.
See also
library::GAPopulation
samchon::library
Author
Jeongho Nam
Definition at line 83 of file GeneticAlgorithm.hpp.
Constructor & Destructor Documentation
template<typename GeneArray, typename Compare = std::less<GeneArray>> samchon::library::GeneticAlgorithm< GeneArray, Compare >::GeneticAlgorithm (bool unique, double mutationRate = 0.015, size_t tournament = 10) inline
Construct from parameters of Genetic Algorithm.
Parameters
unique Whether each Gene is unique in their GeneArray
mutationRate Rate of mutation
tournament Size of tournament in selection
elitism Whether to keep the elitest GeneArray
Definition at line 121 of file GeneticAlgorithm.hpp.
References samchon::library::GeneticAlgorithm< GeneArray, Compare >::mutationRate, samchon::library::GeneticAlgorithm< GeneArray, Compare >::tournament, and samchon::library::GeneticAlgorithm< GeneArray, Compare >::unique.
Member Function Documentation
template<typename GeneArray, typename Compare = std::less<GeneArray>> auto samchon::library::GeneticAlgorithm< GeneArray, Compare >::evolveGeneArray (std::shared_ptr< GeneArray > geneArray, size_t population, size_t generation) const -> std::shared_ptr<GeneArray> inline
Evolve a GeneArray.
Convinient method accessing to evolvePopulation().
Parameters
geneArray An initial set of genes; sequence listing
population Size of population in a generation
generation Size of generation in evolution
Returns
A evolved GeneArray optimally
Definition at line 139 of file GeneticAlgorithm.hpp.
References samchon::library::GeneticAlgorithm< GeneArray, Compare >::evolvePopulation().
Referenced by samchon::example::tsp::Scheduler::optimize().
template<typename GeneArray, typename Compare = std::less<GeneArray>> auto samchon::library::GeneticAlgorithm< GeneArray, Compare >::evolvePopulation (std::shared_ptr< Population > population) const -> std::shared_ptr<Population> inline
Evolve population, a mass of GeneArray(es)
Parameters
population An initial population
Definition at line 155 of file GeneticAlgorithm.hpp.
References samchon::library::GeneticAlgorithm< GeneArray, Compare >::crossover(), samchon::library::GeneticAlgorithm< GeneArray, Compare >::mutate(), and samchon::library::GeneticAlgorithm< GeneArray, Compare >::selection().
Referenced by samchon::library::GeneticAlgorithm< GeneArray, Compare >::evolveGeneArray().
template<typename GeneArray, typename Compare = std::less<GeneArray>> auto samchon::library::GeneticAlgorithm< GeneArray, Compare >::selection (std::shared_ptr< Population > population) const -> std::shared_ptr<GeneArray> inline private
Select the best GeneArray in population from tournament.
Selection is the stage of a genetic algorithm in which individual genomes are chosen from a population for later breeding (using crossover operator). A generic selection procedure may be implemented as follows:
The fitness function is evaluated for each individual, providing fitness values, which are then normalized. Normalization means dividing the fitness value of each individual by the sum of all fitness values, so that the sum of all resulting fitness values equals 1.
The population is sorted by descending fitness values.
Accumulated normalized fitness values are computed (the accumulated fitness value of an individual is the sum of its own fitness value plus the fitness values of all the previous individuals). The accumulated fitness of the last individual should be 1 (otherwise something went wrong in the normalization step).
A random number R between 0 and 1 is chosen.
The selected individual is the first one whose accumulated normalized value is greater than R.
Referenced Wekipedia: https://en.wikipedia.org/wiki/Selection_(genetic_algorithm)
Parameters
population The target of tournament
Returns
The best genes derived by the tournament
Definition at line 212 of file GeneticAlgorithm.hpp.
References samchon::library::GAPopulation< GeneArray, Compare >::children, samchon::library::GAPopulation< GeneArray, Compare >::fitTest(), and samchon::library::Math::random().
Referenced by samchon::library::GeneticAlgorithm< GeneArray, Compare >::evolvePopulation().
template<typename GeneArray, typename Compare = std::less<GeneArray>> auto samchon::library::GeneticAlgorithm< GeneArray, Compare >::crossover (std::shared_ptr< GeneArray > & parent1, std::shared_ptr< GeneArray > & parent2) const -> std::shared_ptr<GeneArray> inline private
Create a new GeneArray by crossing over two GeneArray(s)
crossover is a genetic operator used to vary the programming of a chromosome or chromosomes from one generation to the next. It is analogous to reproduction and biological crossover, upon which genetic algorithms are based.
Cross over is a process of taking more than one parent solutions and producing a child solution from them. There are methods for selection of the chromosomes.
Referenced Wikipedia: https://en.wikipedia.org/wiki/Crossover_(genetic_algorithm)
Parameters
parent1 A parent sequence listing
parent2 A parent sequence listing
Definition at line 241 of file GeneticAlgorithm.hpp.
References samchon::library::Math::random().
Referenced by samchon::library::GeneticAlgorithm< GeneArray, Compare >::evolvePopulation().
template<typename GeneArray, typename Compare = std::less<GeneArray>> void samchon::library::GeneticAlgorithm< GeneArray, Compare >::mutate (std::shared_ptr< GeneArray > geneArray) const inline private
Cause a mutation on the GeneArray.
Mutation is a genetic operator used to maintain genetic diversity from one generation of a population of genetic algorithm chromosomes to the next. It is analogous to biological mutation.
Mutation alters one or more gene values in a chromosome from its initial state. In mutation, the solution may change entirely from the previous solution. Hence GA can come to better solution by using mutation.
Mutation occurs during evolution according to a user-definable mutation probability. This probability should be set low. If it is set too high, the search will turn into a primitive random search.
Referenced Wikipedia: https://en.wikipedia.org/wiki/Mutation_(genetic_algorithm)
Note
Muttion is pursuing diversity. Mutation is useful for avoiding the following problem.
When initial set of genes(GeneArray) is far away from optimail, without mutation (only with selection and crossover), the genetic algorithm has a tend to wandering outside of the optimal.
Genes in the GeneArray will be swapped following percentage of the mutationRate.
Parameters
geneArray A container of genes to mutate
See also
mutationRate;
Definition at line 313 of file GeneticAlgorithm.hpp.
References samchon::library::GeneticAlgorithm< GeneArray, Compare >::mutationRate, and samchon::library::Math::random().
Referenced by samchon::library::GeneticAlgorithm< GeneArray, Compare >::evolvePopulation().
Member Data Documentation
template<typename GeneArray, typename Compare = std::less<GeneArray>> bool samchon::library::GeneticAlgorithm< GeneArray, Compare >::unique private
Whether each element (Gene) is unique in their GeneArray.
Definition at line 92 of file GeneticAlgorithm.hpp.
Referenced by samchon::library::GeneticAlgorithm< GeneArray, Compare >::GeneticAlgorithm().
template<typename GeneArray, typename Compare = std::less<GeneArray>> double samchon::library::GeneticAlgorithm< GeneArray, Compare >::mutationRate private
Rate of mutate ocurrence.
The mutationRate determines the percentage of occurence of mutation in a GeneArray.
Note
When mutationRate is too high, it is hard to ancitipate studying on genetic algorithm.
When mutationRate is too low and initial set of genes(GeneArray) is far away from optimal, the evolution tends to wandering outside of he optimal.
Definition at line 105 of file GeneticAlgorithm.hpp.
Referenced by samchon::library::GeneticAlgorithm< GeneArray, Compare >::GeneticAlgorithm(), and samchon::library::GeneticAlgorithm< GeneArray, Compare >::mutate().
template<typename GeneArray, typename Compare = std::less<GeneArray>> size_t samchon::library::GeneticAlgorithm< GeneArray, Compare >::tournament private
Size of tournament in selection.
Definition at line 110 of file GeneticAlgorithm.hpp.
Referenced by samchon::library::GeneticAlgorithm< GeneArray, Compare >::GeneticAlgorithm().
The documentation for this class was generated from the following file:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/library/GeneticAlgorithm.hpp