Samchon Framework for CPP: samchon::protocol::InvokeParameter Class Reference
samchon::protocol::InvokeParameter Class Reference
A parameter of an Invoke.
#include <InvokeParameter.hpp>
Public Member Functions
InvokeParameter ()
Default Constructor.
InvokeParameter (const std::string &name, const std::string &type, const std::string &val)
Construct from arguments.
template<typename T >
InvokeParameter (const std::string &name, const T &val)
Construct with its name and a value.
InvokeParameter (const std::string &name, std::string &&str)
Construct from the name and a moved string.
InvokeParameter (const std::string &name, ByteArray &&byte_array)
Construct from name and a moved ByteArray.
virtual void construct (std::shared_ptr< library::XML > xml) override
Construct data of the Entity from an XML object.
virtual auto key () const -> std::string override
Get a key that can identify the Entity uniquely.
auto get_name () const -> std::string
Get name.
auto getType () const -> std::string
Get type.
template<typename T >
auto getValue () const -> T
Get value.
auto getValueAsXML () const -> std::shared_ptr< library::XML >
Get value as XML object.
template<typename T >
auto referValue () const -> const T &
Reference value.
template<typename T >
auto moveValue () -> T
Move value.
virtual auto TAG () const -> std::string override
A tag name when represented by XML.
virtual auto toXML () const -> std::shared_ptr< library::XML > override
Get an XML object represents the Entity.
Protected Attributes
std::string name
A name can represent the parameter.
std::string type
Type of the parameter.
std::string str
A string value if the type is "string" or "number".
std::shared_ptr< library::XML > xml
An XML object if the type is "XML".
ByteArray byte_array
A binary value if the type is "ByteArray".
Detailed Description
A parameter of an Invoke.
A parameter with its name, type and value in an Invoke message.
InvokeParameter supports 4 types pre-defined.
number
string
XML
ByteArray
You can specify InvokeParameter to have some type which is not one of the basic 4 types, but values of the custom type must be enable to expressed by one of those types; number, string, XML and ByteArray.
Example Sources
example::invoke
example::interaction
Note
A member variable void* representing any type of value is deprecated.
Since C++11, method of void pointer (Declare a variable as void pointer whose type can not specified. And convert the pointer type to specified one for each case) is recommended to avoid.
As that reason, the void value was a candidate to be deprecated or to be replaced to boost::any. And the void value is really deprecated since version v1.0.
[Inherited]
Entity is a class for standardization of expression method using on network I/O by XML. If Invoke is a standard message protocol of Samchon Framework which must be kept, Entity is a recommended semi-protocol of message for expressing a data class. Following the semi-protocol Entity is not imposed but encouraged.
As we could get advantages from standardization of message for network I/O with Invoke, we can get additional advantage from standardizing expression method of data class with Entity. We do not need to know a part of network communication. Thus, with the Entity, we can only concentrate on entity's own logics and relationships between another entities. Entity does not need to how network communications are being done.
Example Sources
example::entity
example::packer
example::tsp
Note
I say repeatedly. Expression method of Entity is recommended, but not imposed. It's a semi protocol for network I/O but not a essential protocol must be kept. The expression method of Entity, using on network I/O, is expressed by XML string.
If your own network system has a critical performance issue on communication data class, it would be better to using binary communication (with ByteArray or boost::serialization). Don't worry about the problem! Invoke also provides methods for binary data (ByteArray).
See also
protocol
Author
Jeongho Nam http://samchon.org
See also
protocol::Invoke
samchon::protocol
Author
Jeongho Nam http://samchon.org
Definition at line 56 of file InvokeParameter.hpp.
Constructor & Destructor Documentation
samchon::protocol::InvokeParameter::InvokeParameter () inline
Default Constructor.
Definition at line 103 of file InvokeParameter.hpp.
Referenced by InvokeParameter().
samchon::protocol::InvokeParameter::InvokeParameter (const std::string & name, const std::string & type, const std::string & val) inline
Construct from arguments.
Specifies all arguments of an InvokeParameter. You can specify a custom type, that is not one of number or string, but value of the type must be enable to expressed by a string.
If you want to express an object or container group, use XML instead; Invoke::InvokeParameter(string, XML).
Parameters
name A name can represent the InvokeParameter
type Type of value in the InvokeParameter
value A value capsuled by a string
Definition at line 121 of file InvokeParameter.hpp.
References name, and type.
template<typename T > samchon::protocol::InvokeParameter::InvokeParameter (const std::string & name, const T & val) inline
Construct with its name and a value.
Type of the InvokeParameter will be determined automatically.
Type supported in the template constructor:
number
(unsigned) short
(unsigned) long
(unsigned) long long
(unsigned) int
float
double
long double
string
std::string
WeakString
XML
std::shared_ptr<library::XML>
Entity; protocol::Entity::toXML()
ByteArray
Template Parameters
_Ty Type of value
Definition at line 162 of file InvokeParameter.hpp.
References InvokeParameter(), and name.
samchon::protocol::InvokeParameter::InvokeParameter (const std::string & name, std::string && str) inline
Construct from the name and a moved string.
Definition at line 181 of file InvokeParameter.hpp.
References name.
samchon::protocol::InvokeParameter::InvokeParameter (const std::string & name, ByteArray && byte_array) inline
Construct from name and a moved ByteArray.
Definition at line 192 of file InvokeParameter.hpp.
References name.
Member Function Documentation
virtual void samchon::protocol::InvokeParameter::construct (std::shared_ptr< library::XML >) inline override virtual
Construct data of the Entity from an XML object.
Overrides the construct() method and fetch data of member variables from the XML.
By recommended guidance, data representing member variables are contained in properties of the put XML object.
Parameters
xml An xml used to construct data of entity
Implements samchon::protocol::Entity.
Definition at line 202 of file InvokeParameter.hpp.
References byte_array, str, samchon::WeakString::str(), and xml.
virtual auto samchon::protocol::InvokeParameter::key () const -> std::string inline override virtual
Get a key that can identify the Entity uniquely.
If identifier of the Entity is not atomic value, returns a string represents the composite identifier. If identifier of the Entity is not string, converts the identifier to string and returns the string.
Returns
An identifier
Reimplemented from samchon::protocol::Entity.
Definition at line 270 of file InvokeParameter.hpp.
References name.
auto samchon::protocol::InvokeParameter::get_name () const -> std::string inline
Get name.
Definition at line 278 of file InvokeParameter.hpp.
References name.
auto samchon::protocol::InvokeParameter::getType () const -> std::string inline
Get type.
Definition at line 286 of file InvokeParameter.hpp.
References type.
template<typename T > auto samchon::protocol::InvokeParameter::getValue () const -> T inline
Get value.
Template Parameters
_Ty Type of value to get
Definition at line 296 of file InvokeParameter.hpp.
References byte_array, str, and xml.
auto samchon::protocol::InvokeParameter::getValueAsXML () const -> std::shared_ptr<library::XML> inline
Get value as XML object.
Same with getValue< std::shared_ptr<library::XML> >();
Definition at line 323 of file InvokeParameter.hpp.
References byte_array, moveValue(), referValue(), str, and xml.
template<typename T > auto samchon::protocol::InvokeParameter::referValue () const -> const T &
Reference value.
Template Parameters
_Ty Type of value to reference
Referenced by getValueAsXML().
template<typename T > auto samchon::protocol::InvokeParameter::moveValue () -> T
Move value.
Template Parameters
_Ty Type of value to move
Referenced by getValueAsXML().
virtual auto samchon::protocol::InvokeParameter::TAG () const -> std::string inline override virtual
A tag name when represented by XML.
Returns
A tag name
Implements samchon::protocol::Entity.
Definition at line 362 of file InvokeParameter.hpp.
virtual auto samchon::protocol::InvokeParameter::toXML () const -> std::shared_ptr<library::XML> inline override virtual
Get an XML object represents the Entity.
Returns an XML object that can represents the Entity containing member variables into properties.
A member variable (not object, but atomic value like number, string or date) is categorized as a property within the framework of entity side. Thus, when overriding a toXML() method and archiving member variables to an XML object to return, puts each variable to be a property belongs to only an XML object.
Don't archive the member variable of atomic value to XML::value causing enormouse creation of XML objects to number of member variables. An Entity must be represented by only an XML instance (tag).
Standard Usage Non-standard usage abusing value
<memberList>
<member id='jhnam88' name='Jeongho+Nam' birthdate='1988-03-11' />
<member id='master' name='Administartor' birthdate='2011-07-28' />
</memberList> <member>
<id>jhnam88</id>
<name>Jeongho+Nam</name>
<birthdate>1988-03-11</birthdate>
</member>
Returns
An XML object representing the Entity.
Reimplemented from samchon::protocol::Entity.
Definition at line 367 of file InvokeParameter.hpp.
References samchon::protocol::Entity::toXML(), and xml.
Member Data Documentation
std::string samchon::protocol::InvokeParameter::name protected
A name can represent the parameter.
Definition at line 67 of file InvokeParameter.hpp.
Referenced by get_name(), InvokeParameter(), and key().
std::string samchon::protocol::InvokeParameter::type protected
Type of the parameter.
List of pre-defined types
number
string
XML
ByteArray
Definition at line 79 of file InvokeParameter.hpp.
Referenced by getType(), and InvokeParameter().
std::string samchon::protocol::InvokeParameter::str protected
A string value if the type is "string" or "number".
Definition at line 84 of file InvokeParameter.hpp.
Referenced by construct(), getValue(), and getValueAsXML().
std::shared_ptr<library::XML> samchon::protocol::InvokeParameter::xml protected
An XML object if the type is "XML".
Definition at line 89 of file InvokeParameter.hpp.
Referenced by construct(), getValue(), getValueAsXML(), and toXML().
ByteArray samchon::protocol::InvokeParameter::byte_array protected
A binary value if the type is "ByteArray".
Definition at line 94 of file InvokeParameter.hpp.
Referenced by construct(), getValue(), and getValueAsXML().
The documentation for this class was generated from the following file:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/protocol/InvokeParameter.hpp