Samchon Framework for CPP: samchon::examples::packer::Packer Class Reference
samchon::examples::packer::Packer Class Reference
A packer planning the best packaging.
#include <Packer.hpp>
Public Member Functions
Packer ()
Default Constructor.
Packer (shared_ptr< ProductArray > productArray)
Construct from products and wrapper.
Packer (const Packer &packer)
Copy Constructor.
auto productSize () const -> size_t
Get number of products to package.
auto calcPrice () const -> int
Calculate price of the wrappers.
void optimize (size_t start=0, size_t size=-1)
Find the best packaging method.
virtual auto CHILD_TAG () const -> string override
A tag name of children.
virtual auto toXML () const -> shared_ptr< XML > override
Get an XML object represents the EntityGroup.
auto toString () const -> string
Return a string represents an packaging method.
Public Member Functions inherited from samchon::protocol::EntityGroup< Container, T, Key >
virtual void construct (std::shared_ptr< library::XML > xml)
Construct data of the Entity from an XML object.
auto find (const typename child_type::key_type &key) -> typename container_type::iterator
Get iterator to element.
auto find (const typename child_type::key_type &key) const -> typename container_type::const_iterator
Get const iterator to element.
auto has (const typename child_type::key_type &key) const -> bool
Indicates whether a container has an object having the specified identifier.
auto count (const typename child_type::key_type &key) const -> size_t
Count elements with a specific key.
auto get (const typename child_type::key_type &key) -> typename container_type::value_type &
Access the element by specified identifier(key).
auto get (const typename child_type::key_type &key) const -> const typename container_type::value_type &
Access the const element by specified identifier(key).
Public Member Functions inherited from samchon::protocol::Entity< Key >
virtual auto key () const -> Key
Get a key that can identify the Entity uniquely.
Protected Attributes
shared_ptr< ProductArray > productArray
Prodcut(s) to package in some Wrapper(s)
Additional Inherited Members
Protected Member Functions inherited from samchon::protocol::EntityGroup< Container, T, Key >
virtual auto createChild (std::shared_ptr< library::XML >) -> child_type *=0
Factory method of a child Entity.
Detailed Description
A packer planning the best packaging.
Retrieves the solution of packaging by combination permuation and factorial case.
Warning
Be careful about number of products and wrappers.
The time complexity of Packer overs O(m^n). Elapsed time of calculation increases enourmously. Do not use Packer if the digits of number of products or wrappers overs 2.
Author
Jeongho Nam http://samchon.org
Definition at line 36 of file Packer.hpp.
Constructor & Destructor Documentation
samchon::examples::packer::Packer::Packer () inline
Default Constructor.
Definition at line 55 of file Packer.hpp.
samchon::examples::packer::Packer::Packer (shared_ptr< ProductArray > productArray) inline
Construct from products and wrapper.
Parameters
productArray Product(s) to input some Wrapper
wrapperArray Type of Wrapper(s) to be used
Definition at line 67 of file Packer.hpp.
samchon::examples::packer::Packer::Packer (const Packer & packer) inline
Copy Constructor.
Copy constructor of Packer does not copy children items.
Only copies member variables(productArray, wrapperArray) of Packer's.
Definition at line 80 of file Packer.hpp.
Member Function Documentation
auto samchon::examples::packer::Packer::productSize () const -> size_t inline
Get number of products to package.
Definition at line 109 of file Packer.hpp.
auto samchon::examples::packer::Packer::calcPrice () const -> int inline
Calculate price of the wrappers.
Definition at line 117 of file Packer.hpp.
void samchon::examples::packer::Packer::optimize (size_t start = 0, size_t size = -1) inline
Find the best packaging method.
Definition at line 132 of file Packer.hpp.
References samchon::library::CaseGenerator::size().
Referenced by toString().
virtual auto samchon::examples::packer::Packer::CHILD_TAG () const -> string inline override virtual
A tag name of children.
< TAG>
<CHILD_TAG />
<CHILD_TAG />
</TAG>
Implements samchon::protocol::EntityGroupBase.
Definition at line 187 of file Packer.hpp.
virtual auto samchon::examples::packer::Packer::toXML () const -> shared_ptr<XML> inline override virtual
Get an XML object represents the EntityGroup.
Archives the EntityGroup's own member variables only to the returned XML object.
Do not consider about archiving children Entity objects' data in EntityGroup::toXML(). Those children Entity objects will converted to XML object by their own toXML() method. The insertion of XML objects representing children are done by abstract method of EntityGroup::toXML().
Archives only data of EntityGroup's own.
[Inherited]
Reimplemented from samchon::protocol::EntityGroup< Container, T, Key >.
Definition at line 192 of file Packer.hpp.
auto samchon::examples::packer::Packer::toString () const -> string inline
Return a string represents an packaging method.
Definition at line 203 of file Packer.hpp.
References optimize(), and toString().
Referenced by toString().
Member Data Documentation
shared_ptr<ProductArray> samchon::examples::packer::Packer::productArray protected
Prodcut(s) to package in some Wrapper(s)
Definition at line 46 of file Packer.hpp.
The documentation for this class was generated from the following file:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/examples/packer/Packer.hpp