Samchon Framework for CPP: samchon::protocol::master::ParallelSystemArrayMediator Class Reference
samchon::protocol::master::ParallelSystemArrayMediator Class Reference
A mediator of parallel system between master and slaves.
#include <ParallelSystemArrayMediator.hpp>
Public Member Functions
ParallelSystemArrayMediator ()
Default Constructor.
virtual void construct (std::shared_ptr< library::XML >) override
Construct data of the Entity from an XML object.
virtual void start () override
Start interaction.
virtual auto toXML () const -> std::shared_ptr< library::XML > override
Get an XML object represents the EntityGroup.
Public Member Functions inherited from samchon::protocol::master::ParallelSystemArray
ParallelSystemArray ()
Default Constructor.
void sendSegmentData (std::shared_ptr< Invoke >, size_t)
Send a message with segmentation size.
virtual void sendPieceData (std::shared_ptr< Invoke >, size_t, size_t)
Send a message with piece index and size.
Public Member Functions inherited from samchon::protocol::ExternalSystemArray
ExternalSystemArray ()
Default Constructor.
auto hasRole (const std::string &) const -> bool
Test whether has a role.
auto getRole (const std::string &) const -> std::shared_ptr< ExternalSystemRole >
Get a role.
virtual void sendData (std::shared_ptr< Invoke >) override
Sends an Invoke message to related ExternalSystem(s).
virtual void replyData (std::shared_ptr< Invoke >) override
Handle replied Invoke message.
virtual auto TAG () const -> std::string override
A tag name when represented by XML.
virtual auto CHILD_TAG () const -> std::string override
A tag name of children.
Public Member Functions inherited from samchon::protocol::EntityGroup< _Container, _ETy, _Ty >
EntityGroup ()
Default Constructor.
auto has (const std::string &key) const -> bool
Indicates whether a container has an object having the specified identifier.
auto get (const std::string &key) -> value_type &
Access the element by specified identifier(key).
auto get (const std::string &key) const -> const value_type &
Access the const element by specified identifier(key).
Public Member Functions inherited from samchon::protocol::Entity
Entity ()
Default Constructor.
virtual auto key () const -> std::string
Get a key that can identify the Entity uniquely.
Public Member Functions inherited from samchon::protocol::IEntityGroup
IEntityGroup ()
Default Constructor.
Public Member Functions inherited from samchon::protocol::IProtocol
IProtocol ()
Default Constructor.
Protected Member Functions
virtual void notifyEnd (PRMasterHistory *)
Notify end of a master history.
Protected Member Functions inherited from samchon::protocol::EntityGroup< _Container, _ETy, _Ty >
virtual auto createChild (std::shared_ptr< library::XML >) -> entity_type *=0
Factory method of a child Entity.
Protected Attributes
ParallelSlaveSystemMediator * slave
A slave system for mediation.
Detailed Description
A mediator of parallel system between master and slaves.
ParallelSystemArrayMediator class is used to realizing a mediator system of tree-structured parallel processing system. ParallelSystemArrayMediator intermediates between origin-master(ParallelSystemArray) and its slaves(slave::ParallelSystem).
ParallelSystemArrayMediator is a master(ParallelSystemArray) within the framework of slaves systems (slave::ParallelSystem objects) and also can be a slave system (slave::ParallelSystem) within framework of its master(ParallelSystemArray) by having ParallelSlaveSystemMediator.
Todo:
Sends PRMasterHistory to its origin master.
[Inherited]
ParallelSystemArray is an ExternalSystemArray and an abstract class containing. and managing parallel system drvers within framework of master. The ParallelSystemArray class allocates segmented processes (Invoke message containing segmentation size) following by each system's performance index.
Unlike DistributedSystemArray, ParallelSystemArray does not have such complicate relationships and logics. All segmentation sent by sendData(Invoke, size_t) requires uniform performance. ParallelSystemArray just calculates each system's performance index by elapsing time such easily.
Of course, DistributedSystemArray determines which size of segmentation allocation will be suitable for each system by the performance index
.
Each segmentation in requested process (Invoke message) is equivalent. Thus, role of ParallelSystem objects in a ParallelSystemArray are almost same and does not need to specify ExternalSystemRole on each ParallelSystem.
Not a matter to specifying ExternalSystemRole objects to each ParallelSystem. In that case, Invoke messages having segmentation size will be processed by ParallelSystemArray's own logic and Invoke messages without segmentation size will be handled by ordinary logic of ExternalSystemArray's own.
[Inherited]
ExternalSystemArray is an abstract class containing and managing external system drivers.
Also, ExternalSystemArray can access to ExternalSystemRole(s) directly. With the method, you can use an ExternalSystemRole as "logical proxy" of an ExternalSystem. Of course, the ExternalSystemRole is belonged to an ExternalSystem. However, if you access an ExternalSystemRole from an ExternalSystemArray directly, not passing by a belonged ExternalSystem, and send an Invoke message even you're not knowing which ExternalSystem is related in, the ExternalSystemRole acted a role of proxy.
It's called as "Proxy pattern". With the pattern, you can only concentrate on ExternalSystemRole itself, what to do with Invoke message, irrespective of the ExternalSystemRole is belonged to which ExternalSystem.
ExternalSystemArray::getRole("something")->sendData(invoke);
Example Sources
example::interaction
See also
samchon::protocol
Author
Jeongho Nam
Definition at line 36 of file ParallelSystemArrayMediator.hpp.
Constructor & Destructor Documentation
ParallelSystemArrayMediator::ParallelSystemArrayMediator ()
Default Constructor.
Definition at line 19 of file ParallelSystemArrayMediator.cpp.
References slave.
Member Function Documentation
void ParallelSystemArrayMediator::construct (std::shared_ptr< library::XML > xml) override virtual
Construct data of the Entity from an XML object.
Constructs the EntityGroup's own member variables only from the input XML object.
Do not consider about constructing children Entity objects' data in EntityGroup::construct(). Those children Entity objects' data will constructed by their own construct() method. Even insertion of XML objects representing children are done by abstract method of EntityGroup::toXML().
Constructs only data of EntityGroup's own.
[Inherited]
Construct data of the Entity from an XML object.
Overrides the construct() method and fetch data of member variables from the XML.
By recommended guidance, data representing member variables are contained in properties of the put XML object.
Parameters
xml An xml used to construct data of entity
Reimplemented from samchon::protocol::EntityGroup< _Container, _ETy, _Ty >.
Reimplemented in samchon::protocol::master::ParallelClientArrayMediator.
Definition at line 29 of file ParallelSystemArrayMediator.cpp.
References samchon::protocol::ExternalSystem::construct(), samchon::protocol::EntityGroup< _Container, _ETy, _Ty >::construct(), slave, and samchon::protocol::master::ParallelSlaveSystemMediator::TAG().
void ParallelSystemArrayMediator::start () override virtual
Start interaction.
An abstract method starting interaction with external systems.
If external systems are servers, starts connection to them, else clients, opens a server and accepts the external systems. You can addict your own procudures of starting drivers, but if you directly override method of abstract ExternalSystemArray, be careful about virtual inheritance.
DistributedClientArray::start() calls DistributedSystemArray::start() and ExternalClientArray:start()
Implements samchon::protocol::ExternalSystemArray.
Reimplemented in samchon::protocol::master::ParallelClientArrayMediator, and samchon::protocol::master::ParallelServerArrayMediator.
Definition at line 43 of file ParallelSystemArrayMediator.cpp.
References samchon::protocol::master::ParallelSlaveSystemMediator::master, slave, and samchon::protocol::ExternalSystem::start().
Referenced by samchon::protocol::master::ParallelServerArrayMediator::start(), and samchon::protocol::master::ParallelClientArrayMediator::start().
void ParallelSystemArrayMediator::notifyEnd (PRMasterHistory * masterHistory) protected virtual
Notify end of a master history.
Estimates performance of each system by a master history containing their elapsed times.
The estimation is done by normalizing performances of children systems. The estimation of performance is divided by averagae elapsed time of each segmentation.
Reimplemented from samchon::protocol::master::ParallelSystemArray.
Definition at line 64 of file ParallelSystemArrayMediator.cpp.
References samchon::protocol::master::ParallelSystemArray::notifyEnd(), samchon::protocol::IClient::sendData(), slave, and samchon::protocol::InvokeHistory::toInvoke().
auto ParallelSystemArrayMediator::toXML () const -> std::shared_ptr<library::XML> override virtual
Get an XML object represents the EntityGroup.
Archives the EntityGroup's own member variables only to the returned XML object.
Do not consider about archiving children Entity objects' data in EntityGroup::toXML(). Those children Entity objects will converted to XML object by their own toXML() method. The insertion of XML objects representing children are done by abstract method of EntityGroup::toXML().
Archives only data of EntityGroup's own.
[Inherited]
Get an XML object represents the Entity.
Returns an XML object that can represents the Entity containing member variables into properties.
A member variable (not object, but atomic value like number, string or date) is categorized as a property within the framework of entity side. Thus, when overriding a toXML() method and archiving member variables to an XML object to return, puts each variable to be a property belongs to only an XML object.
Don't archive the member variable of atomic value to XML::value causing enormouse creation of XML objects to number of member variables. An Entity must be represented by only an XML instance (tag).
Standard Usage Non-standard usage abusing value
<memberList>
<member id='jhnam88' name='Jeongho+Nam' birthdate='1988-03-11' />
<member id='master' name='Administartor' birthdate='2011-07-28' />
</memberList> <member>
<id>jhnam88</id>
<name>Jeongho+Nam</name>
<birthdate>1988-03-11</birthdate>
</member>
Returns
An XML object representing the Entity.
Reimplemented from samchon::protocol::EntityGroup< _Container, _ETy, _Ty >.
Reimplemented in samchon::protocol::master::ParallelClientArrayMediator.
Definition at line 76 of file ParallelSystemArrayMediator.cpp.
References slave, samchon::protocol::ExternalSystem::toXML(), and samchon::protocol::EntityGroup< _Container, _ETy, _Ty >::toXML().
Member Data Documentation
ParallelSlaveSystemMediator* samchon::protocol::master::ParallelSystemArrayMediator::slave protected
A slave system for mediation.
Definition at line 46 of file ParallelSystemArrayMediator.hpp.
Referenced by samchon::protocol::master::ParallelClientArrayMediator::construct(), construct(), notifyEnd(), samchon::example::interaction::PackerMediator::PackerMediator(), samchon::protocol::master::ParallelClientArrayMediator::ParallelClientArrayMediator(), samchon::protocol::master::ParallelServerArrayMediator::ParallelServerArrayMediator(), ParallelSystemArrayMediator(), samchon::example::interaction::PackerMediator::replyOptimization(), start(), samchon::protocol::master::ParallelClientArrayMediator::toXML(), and toXML().
The documentation for this class was generated from the following files:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/protocol/master/ParallelSystemArrayMediator.hpp
D:/OneDrive/Project/Samchon/framework/cpp/samchon/protocol/master/ParallelSystemArrayMediator.cpp