Samchon Framework for CPP: samchon::example::chat_service::ChatRoom Class Reference
samchon::example::chat_service::ChatRoom Class Reference
A chat room.
#include <ChatRoom.hpp>
Public Member Functions
ChatRoom (ChatRoomArray *, const std::string &, ChatUser *)
Construct from rooms, name and host.
void registerClient (ChatService *)
Register a participant client.
void eraseClient (ChatService *)
Erase a participant client.
virtual auto toXML () const -> std::shared_ptr< library::XML > override
Get an XML object represents the Entity.
Public Member Functions inherited from samchon::protocol::Entity
virtual void construct (std::shared_ptr< library::XML >)=0
Construct data of the Entity from an XML object.
virtual auto key () const -> std::string
Get a key that can identify the Entity uniquely.
Public Member Functions inherited from samchon::protocol::IProtocol
virtual void replyData (std::shared_ptr< Invoke >)=0
Reply a message.
virtual void sendData (std::shared_ptr< Invoke >)=0
Send a message.
Protected Member Functions
virtual auto TAG () const -> std::string
A tag name when represented by XML.
Private Attributes
ChatRoomArray * roomArray
All rooms that the room is belonged to.
std::string name
Name of the room.
ChatUser * host
A host, who established the room.
library::CriticalSet< ChatService * > participants
Participants, ChatUser(s) in the room.
Detailed Description
A chat room.
An entity class representing a chat room containing participants. The ChatRoom class takes a responsibility of Invoke message chain between clients (participating ChatUser(s)) objects.
Author
Jeongho Nam
Definition at line 33 of file ChatRoom.hpp.
Constructor & Destructor Documentation
ChatRoom::ChatRoom (ChatRoomArray * , const std::string & , ChatUser *)
Construct from rooms, name and host.
Parameters
rooms Rooms managing ChatRoom(s).
name Name of the room, the identifier.
host A host who established the room.
Definition at line 20 of file ChatRoom.cpp.
References host, name, and roomArray.
Member Function Documentation
virtual auto samchon::example::chat_service::ChatRoom::TAG () const -> std::string inline protected virtual
A tag name when represented by XML.
Returns
A tag name
Implements samchon::protocol::Entity.
Definition at line 40 of file ChatRoom.hpp.
References roomArray.
void ChatRoom::registerClient (ChatService * service)
Register a participant client.
Registers a participant and notify the participation to another clients.
Definition at line 30 of file ChatRoom.cpp.
References samchon::example::chat_service::ChatRoomArray::notify(), participants, roomArray, and toXML().
void ChatRoom::eraseClient (ChatService * service)
Erase a participant client.
Erases a participant and notify others about the exiting.
Definition at line 37 of file ChatRoom.cpp.
References samchon::example::chat_service::ChatMessage::construct(), samchon::example::chat_service::ChatMessage::getListener(), samchon::example::chat_service::ChatRoomArray::notify(), participants, roomArray, and toXML().
Referenced by samchon::example::chat_service::ChatService::ChatService().
auto ChatRoom::toXML () const -> std::shared_ptr<library::XML> override virtual
Get an XML object represents the Entity.
Returns an XML object that can represents the Entity containing member variables into properties.
A member variable (not object, but atomic value like number, string or date) is categorized as a property within the framework of entity side. Thus, when overriding a toXML() method and archiving member variables to an XML object to return, puts each variable to be a property belongs to only an XML object.
Don't archive the member variable of atomic value to XML::value causing enormouse creation of XML objects to number of member variables. An Entity must be represented by only an XML instance (tag).
Standard Usage Non-standard usage abusing value
<memberList>
<member id='jhnam88' name='Jeongho+Nam' birthdate='1988-03-11' />
<member id='master' name='Administartor' birthdate='2011-07-28' />
</memberList> <member>
<id>jhnam88</id>
<name>Jeongho+Nam</name>
<birthdate>1988-03-11</birthdate>
</member>
Returns
An XML object representing the Entity.
Reimplemented from samchon::protocol::Entity.
Definition at line 85 of file ChatRoom.cpp.
References samchon::protocol::service::User::getID(), host, name, participants, and samchon::protocol::Entity::toXML().
Referenced by eraseClient(), and registerClient().
Member Data Documentation
ChatRoomArray* samchon::example::chat_service::ChatRoom::roomArray private
All rooms that the room is belonged to.
Definition at line 40 of file ChatRoom.hpp.
Referenced by ChatRoom(), eraseClient(), registerClient(), and TAG().
std::string samchon::example::chat_service::ChatRoom::name private
Name of the room.
The name is the identifier of the ChatRoom.
Definition at line 52 of file ChatRoom.hpp.
Referenced by ChatRoom(), and toXML().
ChatUser* samchon::example::chat_service::ChatRoom::host private
A host, who established the room.
Definition at line 57 of file ChatRoom.hpp.
Referenced by ChatRoom(), and toXML().
library::CriticalSet<ChatService*> samchon::example::chat_service::ChatRoom::participants private
Participants, ChatUser(s) in the room.
Definition at line 62 of file ChatRoom.hpp.
Referenced by eraseClient(), registerClient(), and toXML().
The documentation for this class was generated from the following files:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/example/chat_service/ChatRoom.hpp
D:/OneDrive/Project/Samchon/framework/cpp/samchon/example/chat_service/ChatRoom.cpp