Samchon Framework for CPP: samchon::protocol::IWebClientBase Class Reference
samchon::protocol::IWebClientBase Class Reference abstract
An interface for a web-client.
#include <IWebClientBase.hpp>
Public Member Functions
IWebClientBase ()
Default Constructor.
virtual void listen () override
Listens message from a related system.
virtual void sendData (std::shared_ptr< Invoke >) override
Sends message to a related system.
Public Member Functions inherited from samchon::protocol::IClient
IClient ()
Default Constructor.
Public Member Functions inherited from samchon::protocol::IProtocol
IProtocol ()
Default Constructor.
virtual void replyData (std::shared_ptr< Invoke >)
Reply a message.
Additional Inherited Members
Protected Member Functions inherited from samchon::protocol::IClient
virtual auto BUFFER_SIZE () const -> size_t
Buffer size of network I/O.
virtual void _replyData (std::shared_ptr< Invoke >)
A method for pre-processing replied Invoke message.
Protected Attributes inherited from samchon::protocol::IClient
Socket * socket
Socket for network I/O.
std::mutex * sendMtx
A mutex for sending message.
Detailed Description
An interface for a web-client.
IWebClient is a IClient following web-socket protocol.
[Inherited]
IClient is an interface not only for a physical client, but also a driver for a client in a physical server.
IServer:addClient()
service::Server -> service::User -> service::Client
ExternalClientArray (A physical server) -> ExternalClient (A driver of a client)
IClient is one of the basic 3 + 1 components that can make any type of network system in Samchon Framework with IProtocol and IServer. Looking around classes in Samchon Framework, you can see all classes related with client are implemented from the IClient.
IClient takes a role of real network I/O. IClient sends data to otherside network system from IProtocol::sendData(). IClient also gets data from otherside network system, generates standard Invoke message from parsing the replied data and shift the Invoke message to IProtocol::replyData().
Author
Jeongho Nam
Definition at line 32 of file IWebClientBase.hpp.
Constructor & Destructor Documentation
IWebClientBase::IWebClientBase ()
Default Constructor.
Definition at line 20 of file IWebClientBase.cpp.
Member Function Documentation
void IWebClientBase::listen () override virtual
Listens message from a related system.
Note
It holds (monopolies) a thread.
Reimplemented from samchon::protocol::IClient.
Definition at line 28 of file IWebClientBase.cpp.
References samchon::protocol::IClient::_replyData(), samchon::protocol::IClient::BUFFER_SIZE(), samchon::ByteArray::getPosition(), samchon::ByteArray::read(), samchon::ByteArray::readReversely(), samchon::protocol::IClient::socket, and samchon::ByteArray::write().
void IWebClientBase::sendData (std::shared_ptr< Invoke >) override virtual
Sends message to a related system.
Parameters
invoke Invoke message to send
Reimplemented from samchon::protocol::IClient.
Definition at line 184 of file IWebClientBase.cpp.
References samchon::protocol::IClient::sendMtx, samchon::protocol::IClient::socket, samchon::ByteArray::write(), and samchon::ByteArray::writeReversely().
The documentation for this class was generated from the following files:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/protocol/IWebClientBase.hpp
D:/OneDrive/Project/Samchon/framework/cpp/samchon/protocol/IWebClientBase.cpp