Samchon Framework for CPP: samchon::example::tsp::Travel Class Reference
samchon::example::tsp::Travel Class Reference
Represent a travel containning Point(s)
#include <Travel.hpp>
Public Member Functions
Travel ()
Default Constructor.
Travel (const Travel &travel)
Copy Constructor.
Travel (Travel &&travel)
Move Constructor.
virtual void construct (std::shared_ptr< library::XML > xml) override
Construct data of the Entity from an XML object.
auto calcDistance () const -> double
Calculate distance to move.
auto operator< (const Travel &travel) const -> bool
Compare which object is less.
virtual auto TAG () const -> std::string override
A tag name when represented by XML.
virtual auto CHILD_TAG () const -> std::string override
A tag name of children.
virtual auto toXML () const -> std::shared_ptr< library::XML > override
Get an XML object represents the EntityGroup.
auto toString () const -> std::string
Convert the Travel to String.
Public Member Functions inherited from samchon::protocol::EntityGroup< _Container, _ETy, _Ty >
EntityGroup ()
Default Constructor.
auto has (const std::string &key) const -> bool
Indicates whether a container has an object having the specified identifier.
auto get (const std::string &key) -> value_type &
Access the element by specified identifier(key).
auto get (const std::string &key) const -> const value_type &
Access the const element by specified identifier(key).
Public Member Functions inherited from samchon::protocol::Entity
Entity ()
Default Constructor.
virtual auto key () const -> std::string
Get a key that can identify the Entity uniquely.
Public Member Functions inherited from samchon::protocol::IEntityGroup
IEntityGroup ()
Default Constructor.
Protected Member Functions
virtual auto createChild (std::shared_ptr< library::XML >) -> GeometryPoint *
Factory method of a child Entity.
Protected Attributes
double distance
Estimated hours to move.
Detailed Description
Represent a travel containning Point(s)
Travel class is not only an array containing Point(s) but also a sequence listing of the Point(s).
Author
Jeongho Nam
Definition at line 22 of file Travel.hpp.
Constructor & Destructor Documentation
samchon::example::tsp::Travel::Travel () inline
Default Constructor.
Definition at line 44 of file Travel.hpp.
samchon::example::tsp::Travel::Travel (const Travel & travel) inline
Copy Constructor.
Travel is an array of Point(s) as gene(s). The copy constructor of Travel doesn't copy member variables which are related to G.A. because the sequence of gene(Point)s can be shuffled by process of evolution of genetic algorithm.
Definition at line 58 of file Travel.hpp.
samchon::example::tsp::Travel::Travel (Travel && travel) inline
Move Constructor.
Definition at line 67 of file Travel.hpp.
Member Function Documentation
virtual void samchon::example::tsp::Travel::construct (std::shared_ptr< library::XML > xml) inline override virtual
Construct data of the Entity from an XML object.
Constructs the EntityGroup's own member variables only from the input XML object.
Do not consider about constructing children Entity objects' data in EntityGroup::construct(). Those children Entity objects' data will constructed by their own construct() method. Even insertion of XML objects representing children are done by abstract method of EntityGroup::toXML().
Constructs only data of EntityGroup's own.
[Inherited]
Reimplemented from samchon::protocol::EntityGroup< _Container, _ETy, _Ty >.
Definition at line 75 of file Travel.hpp.
References samchon::protocol::EntityGroup< _Container, _ETy, _Ty >::construct().
virtual auto samchon::example::tsp::Travel::createChild (std::shared_ptr< library::XML >) -> GeometryPoint * inline protected virtual
Factory method of a child Entity.
EntityGroup::createChild() is a factory method creating a new child Entity which is belonged to the EntityGroup. This method is called by EntityGroup::construct(). The children construction methods Entity::construct() will be called by abstract method of the EntityGroup::construct().
Returns
A new child Entity belongs to EntityGroup.
Implements samchon::protocol::EntityGroup< _Container, _ETy, _Ty >.
Definition at line 86 of file Travel.hpp.
auto samchon::example::tsp::Travel::calcDistance () const -> double inline
Calculate distance to move.
Definition at line 98 of file Travel.hpp.
References distance.
Referenced by operator<(), and toString().
auto samchon::example::tsp::Travel::operator< (const Travel & travel) const -> bool inline
Compare which object is less.
Compares distances to move. The result is used to optimize and evolve genes by G.A.
Parameters
Target object to compare
Returns
Whether this object is less than target
Definition at line 119 of file Travel.hpp.
References calcDistance().
virtual auto samchon::example::tsp::Travel::TAG () const -> std::string inline override virtual
A tag name when represented by XML.
Returns
A tag name
Implements samchon::protocol::Entity.
Definition at line 127 of file Travel.hpp.
virtual auto samchon::example::tsp::Travel::CHILD_TAG () const -> std::string inline override virtual
A tag name of children.
< TAG>
<CHILD_TAG />
<CHILD_TAG />
</TAG>
Implements samchon::protocol::IEntityGroup.
Definition at line 131 of file Travel.hpp.
virtual auto samchon::example::tsp::Travel::toXML () const -> std::shared_ptr<library::XML> inline override virtual
Get an XML object represents the EntityGroup.
Archives the EntityGroup's own member variables only to the returned XML object.
Do not consider about archiving children Entity objects' data in EntityGroup::toXML(). Those children Entity objects will converted to XML object by their own toXML() method. The insertion of XML objects representing children are done by abstract method of EntityGroup::toXML().
Archives only data of EntityGroup's own.
[Inherited]
Reimplemented from samchon::protocol::EntityGroup< _Container, _ETy, _Ty >.
Definition at line 136 of file Travel.hpp.
References samchon::protocol::EntityGroup< _Container, _ETy, _Ty >::toXML().
auto samchon::example::tsp::Travel::toString () const -> std::string inline
Convert the Travel to String.
Have of form of tab and enter delimeters for Excel.
 {$uid1}    {$x}    {$y}
 {$uid2}   {$x}    {$y}
 {$uid3}   {$x}    {$y}
...
Returns
A string can represent the Travel
Definition at line 157 of file Travel.hpp.
References calcDistance(), and samchon::library::StringUtil::numberFormat().
Member Data Documentation
double samchon::example::tsp::Travel::distance protected
Estimated hours to move.
A variable for avoiding duplicated calculation
See also
calcDistance()
Definition at line 35 of file Travel.hpp.
Referenced by calcDistance().
The documentation for this class was generated from the following file:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/example/tsp/Travel.hpp