Samchon Framework for CPP: samchon::example::interaction::Chief Class Reference
samchon::example::interaction::Chief Class Reference
A chief system managing master systems.
#include <Chief.hpp>
Public Member Functions
Chief (const std::string &ip)
Construct from ip address.
virtual void start ()
Start interaction.
Public Member Functions inherited from samchon::protocol::ExternalSystemArray
ExternalSystemArray ()
Default Constructor.
auto hasRole (const std::string &) const -> bool
Test whether has a role.
auto getRole (const std::string &) const -> std::shared_ptr< ExternalSystemRole >
Get a role.
virtual void sendData (std::shared_ptr< Invoke >) override
Sends an Invoke message to related ExternalSystem(s).
virtual void replyData (std::shared_ptr< Invoke >) override
Handle replied Invoke message.
virtual auto TAG () const -> std::string override
A tag name when represented by XML.
virtual auto CHILD_TAG () const -> std::string override
A tag name of children.
Public Member Functions inherited from samchon::protocol::EntityGroup< _Container, _ETy, _Ty >
EntityGroup ()
Default Constructor.
virtual void construct (std::shared_ptr< library::XML > xml)
Construct data of the Entity from an XML object.
auto has (const std::string &key) const -> bool
Indicates whether a container has an object having the specified identifier.
auto get (const std::string &key) -> value_type &
Access the element by specified identifier(key).
auto get (const std::string &key) const -> const value_type &
Access the const element by specified identifier(key).
virtual auto toXML () const -> std::shared_ptr< library::XML >
Get an XML object represents the EntityGroup.
Public Member Functions inherited from samchon::protocol::Entity
Entity ()
Default Constructor.
virtual auto key () const -> std::string
Get a key that can identify the Entity uniquely.
Public Member Functions inherited from samchon::protocol::IEntityGroup
IEntityGroup ()
Default Constructor.
Public Member Functions inherited from samchon::protocol::IProtocol
IProtocol ()
Default Constructor.
Static Public Member Functions
static void main ()
Main function.
Protected Member Functions
virtual auto createChild (std::shared_ptr< library::XML >) -> protocol::ExternalSystem *
Factory method of a child Entity.
Private Member Functions
void callPacker ()
Call packer master system.
void callTSP ()
Call tsp master system.
Detailed Description
A chief system managing master systems.
A chief system manages master systems. The chief system orders optimization processes to each master system and get reports of the optimization results from those master systems.
The chief system and Chief class is built for providing a guidance for external system module. You can study how to intergrate a system with external network system following the example, the chief system and Chief class.
[Inherited]
An array of ExternalServer(s)
ExternalServerArray is an ExternalSystemArray specialized in servers' driver.
[Inherited]
ExternalSystemArray is an abstract class containing and managing external system drivers.
Also, ExternalSystemArray can access to ExternalSystemRole(s) directly. With the method, you can use an ExternalSystemRole as "logical proxy" of an ExternalSystem. Of course, the ExternalSystemRole is belonged to an ExternalSystem. However, if you access an ExternalSystemRole from an ExternalSystemArray directly, not passing by a belonged ExternalSystem, and send an Invoke message even you're not knowing which ExternalSystem is related in, the ExternalSystemRole acted a role of proxy.
It's called as "Proxy pattern". With the pattern, you can only concentrate on ExternalSystemRole itself, what to do with Invoke message, irrespective of the ExternalSystemRole is belonged to which ExternalSystem.
ExternalSystemArray::getRole("something")->sendData(invoke);
Example Sources
example::interaction
See also
samchon::protocol
Author
Jeongho Nam
Jeongho Nam
Definition at line 41 of file Chief.hpp.
Constructor & Destructor Documentation
samchon::example::interaction::Chief::Chief (const std::string & ip) inline
Construct from ip address.
Parameters
ip IP address of master systems.
Definition at line 56 of file Chief.hpp.
Member Function Documentation
virtual void samchon::example::interaction::Chief::start () inline virtual
Start interaction.
An abstract method starting interaction with external systems.
If external systems are servers, starts connection to them, else clients, opens a server and accepts the external systems. You can addict your own procudures of starting drivers, but if you directly override method of abstract ExternalSystemArray, be careful about virtual inheritance.
DistributedClientArray::start() calls DistributedSystemArray::start() and ExternalClientArray:start()
Reimplemented from samchon::protocol::ExternalServerArray.
Definition at line 64 of file Chief.hpp.
References callPacker(), callTSP(), and samchon::protocol::ExternalServerArray::start().
Referenced by main().
virtual auto samchon::example::interaction::Chief::createChild (std::shared_ptr< library::XML >) -> protocol::ExternalSystem * inline protected virtual
Factory method of a child Entity.
EntityGroup::createChild() is a factory method creating a new child Entity which is belonged to the EntityGroup. This method is called by EntityGroup::construct(). The children construction methods Entity::construct() will be called by abstract method of the EntityGroup::construct().
Returns
A new child Entity belongs to EntityGroup.
Implements samchon::protocol::EntityGroup< _Container, _ETy, _Ty >.
Definition at line 88 of file Chief.hpp.
void samchon::example::interaction::Chief::callPacker () inline private
Call packer master system.
Sends a message to packer system for ordering find the best solution of packaging with its basic data. The packer system who got the ordering message will find and reply the best optimization result about the basic data.
Definition at line 111 of file Chief.hpp.
References samchon::protocol::ExternalSystemArray::sendData(), and samchon::example::packer::Packer::toXML().
Referenced by start().
void samchon::example::interaction::Chief::callTSP () inline private
Call tsp master system.
Sends a message to tsp system for ordering find the best solution of tsp with its basic data. The tsp system who got the ordering message will find and reply the best optimization result about the basic data.
Definition at line 144 of file Chief.hpp.
References samchon::protocol::ExternalSystemArray::sendData(), and samchon::example::tsp::Scheduler::toXML().
Referenced by start().
static void samchon::example::interaction::Chief::main () inline static
Main function.
Definition at line 165 of file Chief.hpp.
References start().
The documentation for this class was generated from the following file:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/example/interaction/Chief.hpp