Samchon Framework for CPP: samchon::example::tsp::GeometryPoint Class Reference
samchon::example::tsp::GeometryPoint Class Reference
A geometry coordinates (point)
#include <GeometryPoint.hpp>
Public Member Functions
GeometryPoint ()
Default Constructor.
GeometryPoint (int uid)
Construct from uid.
GeometryPoint (int uid, double longitude, double latitude)
Construct from uid and geometry coordinates.
virtual auto key () const -> string override
Get a key that can identify the Entity uniquely.
auto calcDistance (const GeometryPoint &point) const -> double
Calculate distance between target Branch.
virtual auto TAG () const -> string
A tag name when represented by XML.
auto toXML () const -> shared_ptr< XML > override
Get an XML object represents the Entity.
auto toString () const -> string
Convert the Branch to String.
Public Member Functions inherited from samchon::protocol::Entity
Entity ()
Default Constructor.
virtual void construct (std::shared_ptr< library::XML >)=0
Construct data of the Entity from an XML object.
Protected Attributes
int uid
An unique id for uniqueness.
double longitude
The longitude; coordinates X.
double latitude
The latitude, coordinates Y.
Detailed Description
A geometry coordinates (point)
Author
Jeongho Nam http://samchon.org
Definition at line 30 of file GeometryPoint.hpp.
Constructor & Destructor Documentation
samchon::example::tsp::GeometryPoint::GeometryPoint () inline
Default Constructor.
Definition at line 59 of file GeometryPoint.hpp.
samchon::example::tsp::GeometryPoint::GeometryPoint (int uid) inline
Construct from uid.
Geometry coordinates, longitude and latitude will have a random value between
Longitude between 0 and 180.
Latitude between -90 and 90.
Definition at line 71 of file GeometryPoint.hpp.
References samchon::library::Math::random().
samchon::example::tsp::GeometryPoint::GeometryPoint (int uid, double longitude, double latitude) inline
Construct from uid and geometry coordinates.
Parameters
longitude Longitude, a coordinate of the geometry point
latitude Latitude, a coordinate of the geometry point
Definition at line 86 of file GeometryPoint.hpp.
Member Function Documentation
virtual auto samchon::example::tsp::GeometryPoint::key () const -> string inline override virtual
Get a key that can identify the Entity uniquely.
If identifier of the Entity is not atomic value, returns a string represents the composite identifier. If identifier of the Entity is not string, converts the identifier to string and returns the string.
Returns
An identifier
Reimplemented from samchon::protocol::Entity.
Definition at line 106 of file GeometryPoint.hpp.
auto samchon::example::tsp::GeometryPoint::calcDistance (const GeometryPoint & point) const -> double inline
Calculate distance between target Branch.
Referenced from http://thesunrises.tistory.com/958 (Geometry points to killometers)
Parameters
branch The target Branch to calculate
Definition at line 117 of file GeometryPoint.hpp.
References samchon::library::Math::degree_to_radian(), and samchon::library::Math::radian_to_degree().
virtual auto samchon::example::tsp::GeometryPoint::TAG () const -> string inline virtual
A tag name when represented by XML.
Returns
A tag name
Implements samchon::protocol::Entity.
Definition at line 141 of file GeometryPoint.hpp.
auto samchon::example::tsp::GeometryPoint::toXML () const -> shared_ptr<XML> inline override virtual
Get an XML object represents the Entity.
Returns an XML object that can represents the Entity containing member variables into properties.
A member variable (not object, but atomic value like number, string or date) is categorized as a property within the framework of entity side. Thus, when overriding a toXML() method and archiving member variables to an XML object to return, puts each variable to be a property belongs to only an XML object.
Don't archive the member variable of atomic value to XML::value causing enormouse creation of XML objects to number of member variables. An Entity must be represented by only an XML instance (tag).
Standard Usage Non-standard usage abusing value
<memberList>
<member id='jhnam88' name='Jeongho+Nam' birthdate='1988-03-11' />
<member id='master' name='Administartor' birthdate='2011-07-28' />
</memberList> <member>
<id>jhnam88</id>
<name>Jeongho+Nam</name>
<birthdate>1988-03-11</birthdate>
</member>
Returns
An XML object representing the Entity.
Reimplemented from samchon::protocol::Entity.
Definition at line 146 of file GeometryPoint.hpp.
auto samchon::example::tsp::GeometryPoint::toString () const -> string inline
Convert the Branch to String.
Have of form of tab and enter delimeters for Excel.
 {$uid}   {$longitude}    {$latitude}
Returns
A string represents the GeometryPoint
Definition at line 164 of file GeometryPoint.hpp.
References samchon::library::StringUtil::substitute().
Member Data Documentation
int samchon::example::tsp::GeometryPoint::uid protected
An unique id for uniqueness.
Definition at line 40 of file GeometryPoint.hpp.
double samchon::example::tsp::GeometryPoint::longitude protected
The longitude; coordinates X.
Definition at line 45 of file GeometryPoint.hpp.
double samchon::example::tsp::GeometryPoint::latitude protected
The latitude, coordinates Y.
Definition at line 50 of file GeometryPoint.hpp.
The documentation for this class was generated from the following file:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/example/tsp/GeometryPoint.hpp