Samchon Framework for CPP: samchon::library::FTFolder Class Reference
samchon::library::FTFolder Class Reference
A folder.
#include <FTFolder.hpp>
Public Member Functions
FTFolder (FTFactory *, FTFolder *)
Construct from factory and parent folder.
virtual auto toXML () const -> std::shared_ptr< library::XML > override
Get an XML object represents the Entity.
Public Member Functions inherited from samchon::protocol::EntityGroup< _Container, _ETy, _Ty >
EntityGroup ()
Default Constructor.
virtual void construct (std::shared_ptr< library::XML > xml)
Construct data of the Entity from an XML object.
auto has (const std::string &key) const -> bool
Indicates whether a container has an object having the specified identifier.
auto get (const std::string &key) -> value_type &
Access the element by specified identifier(key).
auto get (const std::string &key) const -> const value_type &
Access the const element by specified identifier(key).
Public Member Functions inherited from samchon::protocol::Entity
Entity ()
Default Constructor.
Public Member Functions inherited from samchon::protocol::IEntityGroup
IEntityGroup ()
Default Constructor.
Public Member Functions inherited from samchon::library::FTInstance
FTInstance (FTFolder *)
Construct from parent folder.
virtual auto key () const -> std::string
Get a key that can identify the Entity uniquely.
auto getUID () const -> int
Get uid.
auto getParent () const -> FTFolder *
Get parent folder.
auto getName () const -> std::string
Get name.
auto getComment () const -> std::string
Get comment.
Protected Member Functions
virtual auto CHILD_TAG () const -> std::string override
A tag name of children.
Protected Member Functions inherited from samchon::protocol::EntityGroup< _Container, _ETy, _Ty >
virtual auto createChild (std::shared_ptr< library::XML >) -> entity_type *=0
Factory method of a child Entity.
Protected Member Functions inherited from samchon::library::FTInstance
virtual auto TAG () const -> std::string
A tag name when represented by XML.
Protected Attributes
FTFactory * factory
Factory instance for creating sub files.
Protected Attributes inherited from samchon::library::FTInstance
FTFolder * parent
Parent folder containing the instance.
int uid
Key, an unique id of file.
std::string name
Name of the file.
std::string comment
Comment of the file.
Detailed Description
A folder.
A folder object has recursive and hierarchical relationship.
See also
samchon::library
Author
Jeongho Nam
Definition at line 23 of file FTFolder.hpp.
Constructor & Destructor Documentation
FTFolder::FTFolder (FTFactory * factory, FTFolder * parent)
Construct from factory and parent folder.
Parameters
factory Factory instance
parent Parent folder that this folder is belonged to
Definition at line 15 of file FTFolder.cpp.
References samchon::protocol::EntityGroup< _Container, _ETy, _Ty >::construct(), samchon::library::FTFactory::createFile(), factory, and samchon::library::FTFactory::registerInstance().
Member Function Documentation
auto FTFolder::CHILD_TAG () const -> std::string override protected virtual
A tag name of children.
< TAG>
<CHILD_TAG />
<CHILD_TAG />
</TAG>
Implements samchon::protocol::IEntityGroup.
Definition at line 13 of file FTFolder.cpp.
auto FTFolder::toXML () const -> std::shared_ptr<library::XML> override virtual
Get an XML object represents the Entity.
Returns an XML object that can represents the Entity containing member variables into properties.
A member variable (not object, but atomic value like number, string or date) is categorized as a property within the framework of entity side. Thus, when overriding a toXML() method and archiving member variables to an XML object to return, puts each variable to be a property belongs to only an XML object.
Don't archive the member variable of atomic value to XML::value causing enormouse creation of XML objects to number of member variables. An Entity must be represented by only an XML instance (tag).
Standard Usage Non-standard usage abusing value
<memberList>
<member id='jhnam88' name='Jeongho+Nam' birthdate='1988-03-11' />
<member id='master' name='Administartor' birthdate='2011-07-28' />
</memberList> <member>
<id>jhnam88</id>
<name>Jeongho+Nam</name>
<birthdate>1988-03-11</birthdate>
</member>
Returns
An XML object representing the Entity.
Reimplemented from samchon::library::FTInstance.
Definition at line 39 of file FTFolder.cpp.
References samchon::library::FTInstance::toXML(), and samchon::protocol::EntityGroup< _Container, _ETy, _Ty >::toXML().
Member Data Documentation
FTFactory* samchon::library::FTFolder::factory protected
Factory instance for creating sub files.
Definition at line 36 of file FTFolder.hpp.
Referenced by FTFolder().
The documentation for this class was generated from the following files:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/library/FTFolder.hpp
D:/OneDrive/Project/Samchon/framework/cpp/samchon/library/FTFolder.cpp