Samchon Framework for CPP: samchon::library::XML Class Reference
samchon::library::XML Class Reference
XML is a class representing xml object.
#include <XML.hpp>
Public Member Functions
XML ()
Default Constructor.
XML (const XML &xml)
Copy Constructor.
XML (XML &&xml)
Move Constructor.
XML (WeakString wstr)
Constructor by string.
void push_back (WeakString wstr)
Add children xml objects by string representing them.
void push_back (const std::shared_ptr< XML > xml)
Add children xml.
void addAllProperties (const std::shared_ptr< XML > xml)
Add all properties from another XML.
void setTag (const std::string &val)
Set tag (identifier) of the XML.
template<typename T >
void setValue (const T &val)
Set value of the XML.
template<typename T >
void setProperty (const std::string &key, const T &val)
Set a property with its key.
void eraseProperty (const std::string &key)
Erase a property by its key.
void clearProperties ()
Remove all properties in the XML.
auto getTag () const -> std::string
Get key; identifer of the XML.
template<class T = std::string>
auto getValue () const -> T
Get value of the XML.
template<class T = std::string>
auto getProperty (const std::string &key) const -> T
Get property.
template<class T = std::string>
auto fetchProperty (const std::string &key) const -> T
Try to get property.
auto hasProperty (const std::string &key) const -> bool
Test wheter a property exists or not.
auto getPropertyMap () const -> const HashMap< std::string, std::string > &
Get properties.
auto toString (size_t level=0) const -> std::string
Get the string content.
Public Member Functions inherited from samchon::HashMap< std::string, std::shared_ptr< XMLList > >
auto has (const std::string &key) const -> bool
Whether have the item or not.
auto get (const std::string &key) -> std::shared_ptr< XMLList > &
Get element.
void set (const std::string &key, const std::shared_ptr< XMLList > &val)
Set element.
auto pop (const std::string &key) -> std::shared_ptr< XMLList >
Pop item.
Private Member Functions
XML (XML *parent, WeakString &wstr)
Protected Constructor by string for child.
Private Attributes
std::string tag
Tag name.
std::string value
Value of the XML.
HashMap< std::string, std::string > properties
Properties belongs to the XML.
Detailed Description
XML is a class representing xml object.
The XML class provides methods and properties for working with XML objects.
The XML class (along with the XMLList and Namespace) implements the powerful XML-handling standard defined in ECMAScript for XML (E4X) specification.
XML class has a recursive, hierarchical relationship.
All XML objects're managed by shared_ptr.
XML contains XMLList from dictionary of shared pointer<XMLList>
XMLList contains XML from vector of shared pointer<XML>
Even if user creates an XML object directly, it's the basic principle to use shared pointer
Note
Parsing comment is not supported yet.
It's not recommeded to creating an XML object which is not being managed by shared pointer.
Warning
Do not abuse values for expressing member variables.
Standard Usage Non-standard usage abusing value
<memberList>
<member id='jhnam88' name='Jeongho+Nam' birthdate='1988-03-11' />
<member id='master' name='Administartor' birthdate='2011-07-28' />
</memberList> <member>
<id>jhnam88</id>
<name>Jeongho+Nam</name>
<birthdate>1988-03-11</birthdate>
</member>
 #include <iostream>
 #include <vector>
 #include <string>
 #include <samchon/library/XML.hpp>
 #ifdef _WIN64
 #   ifdef _DEBUG
 #       pragma comment(lib, "x64/Debug/SamchonFramework.lib")
 #   else
 #       pragma comment(lib, "x64/Release/SamchonFramework.lib")
 #   endif
 #else
 #   ifdef _DEBUG
 #       pragma comment(lib, "Debug/SamchonFramework.lib")
 #   else
 #       pragma comment(lib, "Release/SamchonFramework.lib")
 #   endif
 #endif
 using namespace std;
 using namespace samchon::library;
 struct Member
 {
     string id;
     string name;
     int age;
     int grade;
     auto toXML() const -> shared_ptr<XML>
     {
         shared_ptr<XML> xml(new XML());
         xml->setTag("member");
         xml->setProperty("id", id);
         xml->setProperty("name", name);
         xml->setProperty("age", age);
         xml->setProperty("grade", grade);
         return xml;
     };
 };
 void main()
 {
     //DECLARE An XML WITH MEMBER_ARRAY TAG
     shared_ptr<XML> xml(new XML());
     xml->setTag("memberArray");
     //ADD MEMBER(S) TO XML
     vector<struct Member> memberArray =
     {
         {"samchon", "Jeongho Nam", 27, 1},
         {"gkyu", "Kwangkyu Ko", 25, 1},
         {"guest", "John Doe", 99, 4}
     };
     for(size_t i = 0; i < memberArray.size(); i++)
         xml->push_back( memberArray[i].toXML() );
     //ADD FILE_LIST BY STRING DIRECTLY
     xml->push_back
     (
         string("") +
         "<fileList>\n" +
             "<file extension='pdf' name='API' />" +
             "<file extension='pdf' name='Guidance+For+Developer'>Damaged</file>" +
             "<file extension='docx' name='Resume' />" +
             "<file extension='jpg' name='My+House' />" +
             "<file extension='xlsx' name='Grades' />" +
         "</fileList>"
     );
     cout << "-----------------------------------------------------------------" << endl;
     cout << " Get Properties And Values" << endl;
     cout << "-----------------------------------------------------------------" << endl;
     cout << "Age of 2nd member: " << xml->get("member")->at(1)->getProperty<int>("age") << endl;
     cout << "Age of 1st member: " << xml->get("member")->at(0)->getProperty("id") << endl << endl;
     cout << "File name and extension of 5th: "
         << xml->get("fileList")->at(0)->get("file")->at(4)->getProperty("name") << "."
         << xml->get("fileList")->at(0)->get("file")->at(4)->getProperty("extension") << endl;
     cout << "Value of 2nd file: " << xml->get("fileList")->at(0)->get("file")->at(1)->getValue() << endl << endl;
     cout << "-----------------------------------------------------------------" << endl;
     cout << " XML to String: " << endl;
     cout << "-----------------------------------------------------------------" << endl;
     cout << xml->toString() << endl;
     system("pause");
 }
See also
samchon::library
Author
Jeongho Nam http://samchon.org
Definition at line 73 of file XML.hpp.
Constructor & Destructor Documentation
samchon::library::XML::XML () inline
Default Constructor.
Warning
Declare XML to managed by shared pointer
Definition at line 118 of file XML.hpp.
Referenced by push_back(), setValue(), and XML().
samchon::library::XML::XML (const XML & xml) inline
Copy Constructor.
Not copying (shared) pointer of children xml objects, but copying the real objects of children xml
Definition at line 129 of file XML.hpp.
References properties, tag, and value.
samchon::library::XML::XML (XML && xml) inline
Move Constructor.
Definition at line 154 of file XML.hpp.
samchon::library::XML::XML (WeakString wstr) inline
Constructor by string.
Parses a string so that constructs an XML object
Parameters
str A string representing xml object
Warning
Declare XML to managed by shared pointer
Definition at line 171 of file XML.hpp.
References samchon::WeakString::between(), samchon::WeakString::find(), samchon::WeakString::size(), samchon::WeakString::substr(), and samchon::WeakString::substring().
samchon::library::XML::XML (XML * parent, WeakString & wstr) inline private
Protected Constructor by string for child.
Parses a string so that creates an XML object It is called for creating children XML objects from parent XML object.
Parameters
parent Parent object who will contains this XML object
str A string to be parsed
Definition at line 225 of file XML.hpp.
References samchon::WeakString::find(), push_back(), samchon::WeakString::rfind(), samchon::HashMap< Key, T, Hash, Pred, Alloc >::set(), samchon::WeakString::size(), samchon::WeakString::substr(), samchon::WeakString::substring(), value, and XML().
Member Function Documentation
void samchon::library::XML::push_back (WeakString wstr) inline
Add children xml objects by string representing them.
Parameters
str A string representing xml objects whould be belonged to this XML
Definition at line 464 of file XML.hpp.
References samchon::WeakString::empty(), and XML().
Referenced by push_back(), setValue(), and XML().
void samchon::library::XML::push_back (const std::shared_ptr< XML > xml) inline
Add children xml.
Parameters
xml An xml object you want to add
Definition at line 488 of file XML.hpp.
References samchon::HashMap< std::string, std::shared_ptr< XMLList > >::has(), push_back(), and tag.
void samchon::library::XML::addAllProperties (const std::shared_ptr< XML > xml) inline
Add all properties from another XML.
Copies all properties from target to here.
Warning
Not a category of assign, but an insert.
Parameters
xml Target xml object to deliver its properties
Definition at line 507 of file XML.hpp.
void samchon::library::XML::setTag (const std::string & val) inline
Set tag (identifier) of the XML.
See also
XML::tag
Definition at line 521 of file XML.hpp.
template<typename T > void samchon::library::XML::setValue (const T & val) inline
Set value of the XML.
Template Parameters
_Ty Type of the value
Parameters
val The value to set
Warning
Do not abuse values for expressing member variables
Standard Usage Non-standard usage abusing value
<memberList>
<member id='jhnam88' name='Jeongho+Nam' birthdate='1988-03-11' />
<member id='master' name='Administartor' birthdate='2011-07-28' />
</memberList> <member>
<id>jhnam88</id>
<name>Jeongho+Nam</name>
<birthdate>1988-03-11</birthdate>
</member>
Definition at line 556 of file XML.hpp.
References push_back(), samchon::WeakString::str(), and XML().
template<typename T > void samchon::library::XML::setProperty (const std::string & key, const T & val) inline
Set a property with its key.
Definition at line 583 of file XML.hpp.
References samchon::HashMap< Key, T, Hash, Pred, Alloc >::set(), and samchon::WeakString::str().
void samchon::library::XML::eraseProperty (const std::string & key) inline
Erase a property by its key.
Parameters
key The key of the property to erase
Exceptions
exception Unable to find the element
Definition at line 602 of file XML.hpp.
void samchon::library::XML::clearProperties () inline
Remove all properties in the XML.
Definition at line 610 of file XML.hpp.
auto samchon::library::XML::getTag () const -> std::string inline
Get key; identifer of the XML.
Returns
tag, identifer of the XML
See also
XML::tag
Definition at line 625 of file XML.hpp.
References tag.
template<class T = std::string> auto samchon::library::XML::getValue () const -> T inline
Get value of the XML.
Definition at line 633 of file XML.hpp.
References value.
template<class T = std::string> auto samchon::library::XML::getProperty (const std::string & key) const -> T inline
Get property.
Definition at line 652 of file XML.hpp.
References samchon::HashMap< Key, T, Hash, Pred, Alloc >::get().
template<class T = std::string> auto samchon::library::XML::fetchProperty (const std::string & key) const -> T inline
Try to get property.
Definition at line 671 of file XML.hpp.
References hasProperty().
auto samchon::library::XML::hasProperty (const std::string & key) const -> bool inline
Test wheter a property exists or not.
Definition at line 682 of file XML.hpp.
References samchon::HashMap< Key, T, Hash, Pred, Alloc >::has().
Referenced by fetchProperty().
auto samchon::library::XML::getPropertyMap () const -> const HashMap<std::string, std::string>& inline
Get properties.
Definition at line 690 of file XML.hpp.
References properties, and samchon::WeakString::replaceAll().
auto samchon::library::XML::toString (size_t level = 0) const -> std::string inline
Get the string content.
Returns a string representation of the XML and its all children.
Returns
A string represents the XML.
Definition at line 777 of file XML.hpp.
References tag.
Member Data Documentation
std::string samchon::library::XML::tag private
Tag name.
<tag label='property' />: tag => "tag"
<price high='1500' low='1300' open='1450' close='1320' />: tag => "price"
Definition at line 86 of file XML.hpp.
Referenced by getTag(), push_back(), toString(), and XML().
std::string samchon::library::XML::value private
Value of the XML.
<parameter name='age' type='int'>26</parameter>: value => 26
<price high='1500' low='1300' open='1450' close='1320' />: value => null
Definition at line 95 of file XML.hpp.
Referenced by getValue(), and XML().
HashMap<std::string, std::string> samchon::library::XML::properties private
Properties belongs to the XML.
A Dictionary of properties accessing each property by its key.
<price high='1500' low='1300' open='1450' close='1320' />: properties => {{"high": 1500}, {"low": 1300}, {"open": 1450}, {"close", 1320}}
<member id='jhnam88' name='Jeongho+Nam' comment='Hello.+My+name+is+Jeongho+Nam' >: properties => {{"id", "jhnam88"}, {"name", "Jeongho Nam http://samchon.org"}, {"comment", "Hello. My name is Jeongho Nam http://samchon.org"}}
Definition at line 107 of file XML.hpp.
Referenced by getPropertyMap(), and XML().
The documentation for this class was generated from the following file:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/library/XML.hpp