Samchon Framework for CPP: samchon::examples::tsp::Scheduler Class Reference
samchon::examples::tsp::Scheduler Class Reference
A scheduler.
#include <Scheduler.hpp>
Public Member Functions
Scheduler ()
Default Constructor.
Scheduler (shared_ptr< Travel > travel, const struct GAParameters &gaParameteres)
Construct from points and parameter of genetic algorithm.
auto optimize () -> shared_ptr< Travel >
Derive optimized schedule.
Public Member Functions inherited from samchon::protocol::Entity<>
virtual auto key () const -> std::string
Get a key that can identify the Entity uniquely.
Protected Attributes
shared_ptr< Travel > travel
A travel to optimize or optimized.
struct GAParameters gaParameters
Parameters for Genetic-Algorithm.
Detailed Description
A scheduler.
Scheduler deducts an optimal schdule(Travel) by genetic algorithm.
Author
Jeongho Nam http://samchon.org
Definition at line 44 of file Scheduler.hpp.
Constructor & Destructor Documentation
samchon::examples::tsp::Scheduler::Scheduler () inline
Default Constructor.
Definition at line 68 of file Scheduler.hpp.
samchon::examples::tsp::Scheduler::Scheduler (shared_ptr< Travel > travel, const struct GAParameters & gaParameteres) inline
Construct from points and parameter of genetic algorithm.
Definition at line 78 of file Scheduler.hpp.
Member Function Documentation
auto samchon::examples::tsp::Scheduler::optimize () -> shared_ptr<Travel> inline
Derive optimized schedule.
Returns
An optimized travel schedule.
Definition at line 105 of file Scheduler.hpp.
References samchon::library::GeneticAlgorithm< GeneArray, Compare >::evolveGeneArray(), and optimize().
Referenced by optimize().
Member Data Documentation
shared_ptr<Travel> samchon::examples::tsp::Scheduler::travel protected
A travel to optimize or optimized.
Definition at line 54 of file Scheduler.hpp.
struct GAParameters samchon::examples::tsp::Scheduler::gaParameters protected
Parameters for Genetic-Algorithm.
Definition at line 59 of file Scheduler.hpp.
The documentation for this class was generated from the following file:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/examples/tsp/Scheduler.hpp