Samchon Framework for CPP: samchon::library::SQLi Class Reference
samchon::library::SQLi Class Reference
A SQL interface; DBMS connector.
#include <SQLi.hpp>
Public Member Functions
SQLi (const std::string &driver, int port)
Construct from driver name and port.
virtual auto createStatement () -> std::shared_ptr< SQLStatement >
Factory method for creating SQLStatement.
virtual void connect (const std::string &ip, const std::string &db, const std::string &id, const std::string &pwd)
Connect to the DBMS
.
virtual void disconnect ()
Disconnect from DBMS.
Protected Member Functions
virtual auto getErrorMessage (short type) const -> std::string
Get error message.
Protected Attributes
std::string driver
Driver; name of DBMS used for connection.
int port
Port number of DBMS.
bool connected
Had connected to DBMS.
Detailed Description
A SQL interface; DBMS connector.
SQLi is an abstract class managing connection (session) with a specific database and manages SQL statements are executed and results are returned within the context of a connection.
The reason why SQLStatement(s) are managed by SQLi is because of a principle of DBMS, DBMS system doesn't allow simultaneous query from a session (connection). Only a query (process0) is allowed at a time. If you try to simultaneous query from a SQLi, ODBC throws error. To avoid the error, an execute of query from SQLStatement will lock a mutex of SQLi to ensure exclusiveness.
Note
To ensure the exclusiveness, you've to make SQLStatement from SQLi. Do not make SQLStatement by yourself. call SQLi::createSQLStatement() instead. Even you make a derived class from SQLStatement, don't make its constructor to have public accessor.
Becuase execution of a sql statement causes lock on mutex in SQLi, you've to destruct the SQLStatement or call SQLStatement::free() method(). If you don't, the mutex will not be unlocked, thus you can't do anything by the SQLi.
Library - SQL Driver
Author
Jeongho Nam http://samchon.org
Definition at line 42 of file SQLi.hpp.
Constructor & Destructor Documentation
samchon::library::SQLi::SQLi (const std::string & driver, int port) inline
Construct from driver name and port.
Parameters
driver Driver name of DBMS
port Port number of DBMS
Definition at line 83 of file SQLi.hpp.
References disconnect(), driver, and port.
Member Function Documentation
virtual auto samchon::library::SQLi::createStatement () -> std::shared_ptr<SQLStatement> inline virtual
Factory method for creating SQLStatement.
Recommend to create SQLStatement by this method. Direct creation is not recommended as the reason of domain problem of each DBMS
Returns
A SQLStatement matched for the domain SQLi
Definition at line 106 of file SQLi.hpp.
References connect().
virtual void samchon::library::SQLi::connect (const std::string & ip, const std::string & db, const std::string & id, const std::string & pwd) inline virtual
Connect to the DBMS
.
Parameters
ip An IP address of the DBMS
db A name of database to access
id Your own ID authorified from DBMS
pwd A password for the ID
Exceptions
exception Error message from DBMS
Definition at line 122 of file SQLi.hpp.
References disconnect(), getErrorMessage(), and samchon::library::StringUtil::substitute().
Referenced by createStatement().
virtual void samchon::library::SQLi::disconnect () inline virtual
Disconnect from DBMS.
Definition at line 163 of file SQLi.hpp.
Referenced by connect(), and SQLi().
virtual auto samchon::library::SQLi::getErrorMessage (short type) const -> std::string inline protected virtual
Get error message.
Gets error message for throwing exception.
Definition at line 192 of file SQLi.hpp.
Referenced by connect().
Member Data Documentation
std::string samchon::library::SQLi::driver protected
Driver; name of DBMS used for connection.
MySQL: "{MySQL Server}"
MS-SQL: "{SQL Server}"
PL-SQL: "{Oracle}"
Definition at line 55 of file SQLi.hpp.
Referenced by SQLi().
int samchon::library::SQLi::port protected
Port number of DBMS.
MySQL: 3306
MS-SQL: 1433
PL-SQL: 1521
Definition at line 65 of file SQLi.hpp.
Referenced by SQLi().
bool samchon::library::SQLi::connected protected
Had connected to DBMS.
connected is a flag variable for connection to DBMS. However, it doesn't mean the real-time status. connected only stores whether a connection was succeeded or not.
Definition at line 74 of file SQLi.hpp.
The documentation for this class was generated from the following file:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/library/SQLi.hpp