Samchon Framework for CPP: samchon::library::HTTPLoader Class Reference
samchon::library::HTTPLoader Class Reference
A http, web-page loader.
#include <HTTPLoader.hpp>
Public Member Functions
HTTPLoader (const std::string &url, int method=POST)
Construct from request url and method.
void setURL (const std::string &val)
Set url.
void setMethod (int val)
Set method.
auto getURL () const -> std::string
Get url.
auto getMethod () const -> int
Get method.
auto getCookie (const std::string &key) const -> std::string
Get cookie.
auto load (const URLVariables &parameters={}) const -> ByteArray
Load data from target url.
Static Private Member Functions
static HashMap< std::string, std::string > & cookie_map ()
Cookies got from remote web server.
Private Attributes
int method
Method, Get or Post.
Detailed Description
A http, web-page loader.
Author
Jeongho Nam http://samchon.org
Definition at line 26 of file HTTPLoader.hpp.
Constructor & Destructor Documentation
samchon::library::HTTPLoader::HTTPLoader (const std::string & url, int method = POST) inline
Construct from request url and method.
Parameters
url Target url of remote web server.
method Get or Post
Definition at line 62 of file HTTPLoader.hpp.
References method.
Member Function Documentation
static HashMap<std::string, std::string>& samchon::library::HTTPLoader::cookie_map () inline static private
Cookies got from remote web server.
Definition at line 39 of file HTTPLoader.hpp.
Referenced by getCookie(), and load().
void samchon::library::HTTPLoader::setURL (const std::string & val) inline
Set url.
Definition at line 75 of file HTTPLoader.hpp.
void samchon::library::HTTPLoader::setMethod (int val) inline
Set method.
Definition at line 83 of file HTTPLoader.hpp.
References method.
auto samchon::library::HTTPLoader::getURL () const -> std::string inline
Get url.
Definition at line 91 of file HTTPLoader.hpp.
auto samchon::library::HTTPLoader::getMethod () const -> int inline
Get method.
Definition at line 99 of file HTTPLoader.hpp.
References method.
auto samchon::library::HTTPLoader::getCookie (const std::string & key) const -> std::string inline
Get cookie.
Definition at line 107 of file HTTPLoader.hpp.
References cookie_map().
Referenced by load().
auto samchon::library::HTTPLoader::load (const URLVariables & parameters = {}) const -> ByteArray inline
Load data from target url.
Loads binary data from target web server and address.
Parameters
data URLVariables containing parameters to request.
Returns
Binary data fetched from remote web server.
Definition at line 128 of file HTTPLoader.hpp.
References samchon::WeakString::between(), cookie_map(), samchon::library::URLVariables::encode(), samchon::WeakString::find(), samchon::HashMap< Key, T, Hash, Pred, Alloc >::get(), getCookie(), samchon::HashMap< Key, T, Hash, Pred, Alloc >::has(), samchon::HashMap< Key, T, Hash, Pred, Alloc >::set(), samchon::WeakString::split(), samchon::WeakString::str(), samchon::library::StringUtil::substitute(), and samchon::WeakString::substr().
Member Data Documentation
int samchon::library::HTTPLoader::method private
Method, Get or Post.
Definition at line 34 of file HTTPLoader.hpp.
Referenced by getMethod(), HTTPLoader(), and setMethod().
The documentation for this class was generated from the following file:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/library/HTTPLoader.hpp