Samchon Framework for CPP: samchon::templates::distributed::DSInvokeHistory Class Reference
samchon::templates::distributed::DSInvokeHistory Class Reference
#include <DSInvokeHistory.hpp>
Public Member Functions
DSInvokeHistory (DistributedSystem *)
DSInvokeHistory (DistributedSystem *, DistributedProcess *, std::shared_ptr< protocol::Invoke >, double weight)
auto getSystem () const -> DistributedSystem *
auto getProcess () const -> DistributedProcess *
auto getWeight () const -> double
Public Member Functions inherited from samchon::protocol::InvokeHistory
InvokeHistory ()
InvokeHistory (std::shared_ptr< Invoke > invoke)
virtual auto key () const -> size_t override
Get a key that can identify the Entity uniquely.
auto getUID () const -> size_t
auto getListener () const -> std::string
auto computeElapsedTime () const -> long long
void complete ()
Detailed Description
History of an Invoke message.
The PRInvokeHistory is a class archiving history log of an Invoke message which requests the distributed process, created whenever DistributedProcess.sendData is called.
When the distributed process has completed, then complete() is called and the elapsed time is determined. The elapsed time is utilized for computation of performance index and resource index of related objects.
Templates - Distributed System
Author
Jeongho Nam http://samchon.org
Definition at line 30 of file DSInvokeHistory.hpp.
Constructor & Destructor Documentation
DSInvokeHistory::DSInvokeHistory (DistributedSystem * system)
Construct from a DistributedSystem.
Parameters
system The DistributedSystem object who sent the Invoke message.
Definition at line 16 of file DSInvokeHistory.cpp.
References samchon::templates::distributed::DistributedProcess::getName(), and samchon::templates::distributed::DistributedSystem::getSystemArray().
samchon::templates::distributed::DSInvokeHistory::DSInvokeHistory (DistributedSystem * , DistributedProcess * , std::shared_ptr< protocol::Invoke > , double weight)
Initilizer Constructor.
Parameters
system The DistributedSystem object who sent the Invoke message.
process The DistributedProcess object who sent the Invoke message.
invoke An Invoke message requesting the distributed process.
weight Weight of resource which indicates how heavy this Invoke message is.
Member Function Documentation
auto samchon::templates::distributed::DSInvokeHistory::getSystem () const -> DistributedSystem* inline
Get the related DistributedSystem object.
Definition at line 73 of file DSInvokeHistory.hpp.
auto samchon::templates::distributed::DSInvokeHistory::getProcess () const -> DistributedProcess* inline
Get the related DistributedProcess object.
Definition at line 81 of file DSInvokeHistory.hpp.
Referenced by samchon::templates::distributed::DistributedSystem::replyData().
auto samchon::templates::distributed::DSInvokeHistory::getWeight () const -> double inline
Get weight.
Gets weight of resource which indicates how heavy this Invoke message is. Default is 1.
Definition at line 91 of file DSInvokeHistory.hpp.
The documentation for this class was generated from the following files:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/templates/distributed/DSInvokeHistory.hpp
D:/OneDrive/Project/Samchon/framework/cpp/samchon/templates/distributed/DSInvokeHistory.cpp