Samchon Framework for CPP: samchon::library::Datetime Class Reference
samchon::library::Datetime Class Reference
Date and time.
#include <Datetime.hpp>
Public Member Functions
Datetime ()
Datetime (const std::chrono::system_clock::time_point &)
Copy Constructor.
Datetime (std::chrono::system_clock::time_point &&)
Datetime (int year, int month, int date, int hour=0, int min=0, int sec=0)
Construct from datetime elements.
Datetime (const std::string &)
Construct from string.
Datetime (const WeakString &)
Construct from WeakString.
Datetime (long long linuxTime)
Construct from linux_time.
void set (const std::string &)
Setter by string.
virtual void set (const WeakString &) override
Set by weak_string.
void set (int year, int month, int date, int hours=0, int minutes=0, int seconds=0)
void set (long long linuxTime)
virtual void setYear (int)
Set year of the Date.
virtual void setMonth (int)
Set month of the Date.
virtual void setDate (int)
void setHour (int)
Set hour.
void setMinute (int)
Set minute.
void setSecond (int)
Set hour.
virtual void addYear (int) override
Add years to the Date.
virtual void addMonth (int) override
Add months to the Date.
virtual void addWeek (int) override
Add weeks to the Date.
virtual void addDate (int) override
Add days to the Date.
void addHour (int)
Add hours.
void addMinute (int)
Add minutes.
void addSecond (int)
Add seconds.
auto getHour () const -> int
Get hour.
auto getMinute () const -> int
Get minute.
auto getSecond () const -> int
Get second.
virtual auto toString () const -> std::string override
Converts the Datetime to std::string.
Public Member Functions inherited from samchon::library::Date
Date ()
Default Constructor.
Date (const super &)
Copy Constructor.
Date (super &&)
Date (int year, int month, int date)
Construct from date elements.
Date (const std::string &)
Construct from string.
Date (const WeakString &)
Construct from WeakString.
Date (long long linuxTime)
Construct from linux_time.
void set (const std::string &)
Setter by string.
void set (int year, int month, int date)
Setter by elements of date.
void set (long long linuxTime)
Setter by linux_time.
auto getYear () const -> int
Get year of the Date.
auto getMonth () const -> int
Get month of the Date.
auto getDate () const -> int
Get the day in month of the Date.
auto getDay () const -> int
Get the day in week of the Date.
auto toLinuxTime () const -> long long
Converts the Date to linux_time.
Additional Inherited Members
Protected Member Functions inherited from samchon::library::Date
auto toTM () const -> struct::tm
Converts the Date to struct tm.
Static Protected Member Functions inherited from samchon::library::Date
static auto calcSeconds (int year, int month, int date) -> long long
Calculates how many seconds have flowen since 0000-01-01 00:00:00.
static auto calcLastDates (int year) -> std::array< int, 12 >
Calculates and gets an array of final date of each month for that year.
Static Protected Attributes inherited from samchon::library::Date
static std::chrono::system_clock::time_point TP_1970 = chrono::system_clock::from_time_t(0)
time_point for 1970-01-01 09:00:00
Detailed Description
Date and time.
Datetime is a Date having hours, minutes and seconds addictionally.
[Inherited]
Date class is a chrono::time_point<std::chrono::system_clock>.
Date represents the date with year, month and day in month. The basic date (local time) is from your operating system.
[Inherited]
A time_point object expresses a point in time relative to a clock's epoch.
Internally, the object stores an object of a duration type, and uses the Clock type as a reference for its epoch.
Referenced comments of std::chrono::time_point
http://www.cplusplus.com/reference/chrono/time_point/
See also
samchon::library
Author
Jeongho Nam
Definition at line 19 of file Datetime.hpp.
Constructor & Destructor Documentation
Datetime::Datetime ()
Default Constructor
The datetime will be now (Now from operating system)
Definition at line 15 of file Datetime.cpp.
samchon::library::Datetime::Datetime (const std::chrono::system_clock::time_point &)
Copy Constructor.
Copy the date from another Date
Parameters
date Target to be copied
samchon::library::Datetime::Datetime (std::chrono::system_clock::time_point &&)
Move Constructor
Gets the date from other and truncate the other
Parameters
date Target to be moved
Datetime::Datetime (int year, int month, int date, int hour = 0, int min = 0, int sec = 0)
Construct from datetime elements.
Parameters
year ex) 2015
month January to December. 1 ~ 12
date Day in month. 1 ~ 31
hour Hours (0-23)
min Minutes (0-59)
sec Seconds (0-59)
Exceptions
invalid_argument parameter is out of its own range.
Definition at line 27 of file Datetime.cpp.
References set().
samchon::library::Datetime::Datetime (const std::string &)
Construct from string.
Parameters
str A string representing the date. (1991-01-01 09:27:03)
Exceptions
invalid_argument parameter is out of its own range.
Datetime::Datetime (const WeakString & wStr)
Construct from WeakString.
Parameters
wstr A weak_string expressing the date. (1991-01-01 09:27:03)
Exceptions
invalid_argument parameter is out of its own range.
Definition at line 36 of file Datetime.cpp.
References set().
Datetime::Datetime (long long linuxTime)
Construct from linux_time.
Parameters
linuxTime linux_time to be converted
Definition at line 41 of file Datetime.cpp.
References set().
Member Function Documentation
void samchon::library::Datetime::set (const std::string &)
Setter by string.
Parameters
str wstr A string expressing the date. (1991-01-01 09:27:03)
Exceptions
invalid_argument parameter is out of its own range.
Referenced by addDate(), addMonth(), addWeek(), addYear(), Datetime(), set(), setDate(), setHour(), setMinute(), setMonth(), setSecond(), and setYear().
void Datetime::set (const WeakString & wStr) override virtual
Set by weak_string.
Parameters
wstr A weak_string expressing the date. (1991-01-01 09:27:03)
Exceptions
invalid_argument parameter is out of its own range.
Reimplemented from samchon::library::Date.
Definition at line 52 of file Datetime.cpp.
References samchon::WeakString::between(), samchon::WeakString::find(), getMinute(), getSecond(), samchon::library::Date::getYear(), set(), and samchon::library::Date::set().
void Datetime::set (int year, int month, int date, int hours = 0, int minutes = 0, int seconds = 0)
Exceptions
invalid_argument parameter is out of range (ex: month -> 13)
Definition at line 70 of file Datetime.cpp.
References addSecond(), and samchon::library::Date::set().
void Datetime::set (long long linuxTime)
Definition at line 75 of file Datetime.cpp.
References samchon::library::Date::set().
void Datetime::setYear (int val) virtual
Set year of the Date.
If previous date is leaf month's expiration date and target year what you want is not leaf, the date will be 28
2000-02-29 -> setYear(2001) -> 2001-02-28
2001-02-28 -> setYear(2000) -> 2000-02-08
Parameters
val Target year
Reimplemented from samchon::library::Date.
Definition at line 84 of file Datetime.cpp.
References samchon::library::Date::getDate(), getHour(), getMinute(), samchon::library::Date::getMonth(), getSecond(), samchon::library::Date::getYear(), set(), and samchon::library::Date::setYear().
void Datetime::setMonth (int val) virtual
Set month of the Date.
If the expiration date of the month will be shrinked, the date will be changed to the expiration date
2000-03-31 -> setMonth(4) -> 2000-04-30
2007-08-31 -> setMonth(9) -> 2007-09-30
Parameters
val Target month (1 - 12)
Exceptions
invalid_argument month is out of range
Reimplemented from samchon::library::Date.
Definition at line 93 of file Datetime.cpp.
References samchon::library::Date::getDate(), getHour(), getMinute(), samchon::library::Date::getMonth(), getSecond(), samchon::library::Date::getYear(), set(), and samchon::library::Date::setMonth().
void Datetime::setDate (int val) virtual
Set date of the Date
Parameters
val Target day in month
Exceptions
invalid_argument When date is over expiration date in month
Reimplemented from samchon::library::Date.
Definition at line 102 of file Datetime.cpp.
References samchon::library::Date::getDate(), getHour(), getMinute(), samchon::library::Date::getMonth(), getSecond(), samchon::library::Date::getYear(), set(), and samchon::library::Date::setDate().
void Datetime::setHour (int val)
Set hour.
Parameters
val Target hour (0 - 23)
Exceptions
invalid_argument When hour is out of range
Definition at line 111 of file Datetime.cpp.
References samchon::library::Date::getDate(), getMinute(), samchon::library::Date::getMonth(), getSecond(), samchon::library::Date::getYear(), and set().
void Datetime::setMinute (int val)
Set minute.
Parameters
val Target minute (0 - 59)
Exceptions
invalid_argument When minute is out of range
Definition at line 115 of file Datetime.cpp.
References samchon::library::Date::getDate(), getHour(), samchon::library::Date::getMonth(), getSecond(), samchon::library::Date::getYear(), and set().
void Datetime::setSecond (int val)
Set hour.
Parameters
val Target second (0 - 59)
Exceptions
invalid_argument When second is out of range
Definition at line 119 of file Datetime.cpp.
References samchon::library::Date::getDate(), getHour(), getMinute(), samchon::library::Date::getMonth(), samchon::library::Date::getYear(), and set().
void Datetime::addYear (int val) override virtual
Add years to the Date.
Parameters
val Years to add
Reimplemented from samchon::library::Date.
Definition at line 125 of file Datetime.cpp.
References samchon::library::Date::addYear(), samchon::library::Date::getDate(), getHour(), getMinute(), samchon::library::Date::getMonth(), getSecond(), samchon::library::Date::getYear(), and set().
void Datetime::addMonth (int val) override virtual
Add months to the Date.
Not a matter to val is over 12. If the month is over 12, then years will be added.
Parameters
val Months to add
Reimplemented from samchon::library::Date.
Definition at line 134 of file Datetime.cpp.
References samchon::library::Date::addMonth(), samchon::library::Date::getDate(), getHour(), getMinute(), samchon::library::Date::getMonth(), getSecond(), samchon::library::Date::getYear(), and set().
void Datetime::addWeek (int val) override virtual
Add weeks to the Date.
Not a matter that val is too huge. If the adding weeks derives modification in month or year, then it will be.
Parameters
val Weeks to add
Reimplemented from samchon::library::Date.
Definition at line 143 of file Datetime.cpp.
References samchon::library::Date::addWeek(), samchon::library::Date::getDate(), getHour(), getMinute(), samchon::library::Date::getMonth(), getSecond(), samchon::library::Date::getYear(), and set().
void Datetime::addDate (int val) override virtual
Add days to the Date.
Not a matter that val is too huge. If the adding dates derives modification in month or year, then it will be.
Parameters
val Days to add
Reimplemented from samchon::library::Date.
Definition at line 152 of file Datetime.cpp.
References samchon::library::Date::addDate(), samchon::library::Date::getDate(), getHour(), getMinute(), samchon::library::Date::getMonth(), getSecond(), samchon::library::Date::getYear(), and set().
void Datetime::addHour (int val)
Add hours.
It's same with operator+=(chrono::hours(val))
Do not worry about the out of range of the hour(val) Parent items like date, month and years will be adjusted automatically.
Parameters
val hours to add
Definition at line 161 of file Datetime.cpp.
void Datetime::addMinute (int val)
Add minutes.
It's same with operator+=(chrono::minutes(val))
Do not worry about the out of range of the minutes(val) Parent items like date, month and years will be adjusted automatically.
Parameters
val minutes to add
Definition at line 165 of file Datetime.cpp.
void Datetime::addSecond (int val)
Add seconds.
It's same with operator+=(chrono::seconds(val))
Do not worry about the out of range of the seconds(val) Parent items like date, month and years will be adjusted automatically.
Parameters
val seconds to add
Definition at line 169 of file Datetime.cpp.
Referenced by set().
int Datetime::getHour () const -> int
Get hour.
Returns
hour of the Datetime to integer
Definition at line 175 of file Datetime.cpp.
References samchon::library::Date::toTM().
Referenced by addDate(), addMonth(), addWeek(), addYear(), setDate(), setMinute(), setMonth(), setSecond(), setYear(), and toString().
int Datetime::getMinute () const -> int
Get minute.
Returns
minute of the Datetime to integer
Definition at line 180 of file Datetime.cpp.
References samchon::library::Date::toTM().
Referenced by addDate(), addMonth(), addWeek(), addYear(), set(), setDate(), setHour(), setMonth(), setSecond(), setYear(), and toString().
int Datetime::getSecond () const -> int
Get second.
Returns
second of the Datetime to integer
Definition at line 185 of file Datetime.cpp.
References samchon::library::Date::toTM().
Referenced by addDate(), addMonth(), addWeek(), addYear(), set(), setDate(), setHour(), setMinute(), setMonth(), setYear(), and toString().
auto Datetime::toString () const -> std::string override virtual
Converts the Datetime to std::string.
Returns
std::string expressing the Datetime
Reimplemented from samchon::library::Date.
Definition at line 192 of file Datetime.cpp.
References getHour(), getMinute(), getSecond(), samchon::library::StringUtil::substitute(), and samchon::library::Date::toString().
The documentation for this class was generated from the following files:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/library/Datetime.hpp
D:/OneDrive/Project/Samchon/framework/cpp/samchon/library/Datetime.cpp