Samchon Framework for CPP: samchon::templates::external::ExternalSystemArray Class Reference
samchon::templates::external::ExternalSystemArray Class Reference abstract
#include <ExternalSystemArray.hpp>
Public Member Functions
ExternalSystemArray ()
virtual ~ExternalSystemArray ()
auto hasRole (const std::string &key) const -> bool
auto getRole (const std::string &key) const -> std::shared_ptr< ExternalSystemRole >
virtual void sendData (std::shared_ptr< protocol::Invoke > invoke)
virtual void replyData (std::shared_ptr< protocol::Invoke > invoke)=0
virtual auto CHILD_TAG () const -> std::string override
A tag name of children.
Public Member Functions inherited from samchon::protocol::EntityGroup< Container, T, Key >
virtual void construct (std::shared_ptr< library::XML > xml)
Construct data of the Entity from an XML object.
auto find (const typename child_type::key_type &key) -> typename container_type::iterator
Get iterator to element.
auto find (const typename child_type::key_type &key) const -> typename container_type::const_iterator
Get const iterator to element.
auto has (const typename child_type::key_type &key) const -> bool
Indicates whether a container has an object having the specified identifier.
auto count (const typename child_type::key_type &key) const -> size_t
Count elements with a specific key.
auto get (const typename child_type::key_type &key) -> typename container_type::value_type &
Access the element by specified identifier(key).
auto get (const typename child_type::key_type &key) const -> const typename container_type::value_type &
Access the const element by specified identifier(key).
virtual auto toXML () const -> std::shared_ptr< library::XML >
Get an XML object represents the EntityGroup.
Public Member Functions inherited from samchon::protocol::Entity< Key >
virtual auto key () const -> Key
Get a key that can identify the Entity uniquely.
Public Member Functions inherited from samchon::protocol::IProtocol
virtual void replyData (std::shared_ptr< Invoke >)=0
virtual void sendData (std::shared_ptr< Invoke >)=0
Additional Inherited Members
Protected Member Functions inherited from samchon::protocol::EntityGroup< Container, T, Key >
virtual auto createChild (std::shared_ptr< library::XML >) -> child_type *=0
Factory method of a child Entity.
Detailed Description
An array and manager of external system drivers.
The ExternalSystemArray is an abstract class containing and managing external system drivers, ExternalSystem objects. Within framewokr of network, ExternalSystemArray represents your system and children ExternalSystem objects represent remote, external systems connected with your system. With this ExternalSystemArray, you can manage multiple external systems as a group.
You can specify this ExternalSystemArray class to be a server accepting external clients or a client connecting to external servers. Even both of them is also possible.
ExternalClientArray: A server accepting external clients.
ExternalServerArray: A client connecting to external servers.
ExternalServerClientArray: Both of them. Accepts external clients and connects to external servers at the same time.
Proxy Pattern
The ExternalSystemArray class can use Proxy Pattern. In framework within user, which external system is connected with this system, it's not important. Only interested in user's perspective is which can be done.
By using the logical proxy, user dont't need to know which role is belonged to which system. Just access to a role directly from ExternalSystemArray.getRole. Sends and receives Invoke message via the role.
ExternalSystemRole can be accessed from ExternalSystemArray directly, without inteferring from ExternalSystem, with ExternalSystemArray.getRole.
When you want to send an Invoke message to the belonged system, just call ExternalSystemRole.sendData(). Then, the message will be sent to the external system.
Those strategy is called Proxy Pattern.
Templates - External System
Author
Jeongho Nam http://samchon.org
Definition at line 64 of file ExternalSystemArray.hpp.
Constructor & Destructor Documentation
ExternalSystemArray::ExternalSystemArray ()
Default Constructor.
Definition at line 12 of file ExternalSystemArray.cpp.
ExternalSystemArray::~ExternalSystemArray () virtual
Default Destructor.
Definition at line 16 of file ExternalSystemArray.cpp.
Member Function Documentation
auto samchon::templates::external::ExternalSystemArray::hasRole (const std::string & key) const -> bool inline
Test whether the role exists.
Parameters
name Name, identifier of target role.
Returns
Whether the role has or not.
Definition at line 96 of file ExternalSystemArray.hpp.
auto samchon::templates::external::ExternalSystemArray::getRole (const std::string & key) const -> std::shared_ptr<ExternalSystemRole> inline
Get a role.
Parameters
name Name, identifier of target role.
Returns
The specified role.
Definition at line 113 of file ExternalSystemArray.hpp.
void ExternalSystemArray::sendData (std::shared_ptr< protocol::Invoke > invoke) virtual
Send an Invoke message.
Parameters
invoke An Invoke message to send.
Definition at line 23 of file ExternalSystemArray.cpp.
Referenced by samchon::templates::external::ExternalSystemRole::sendData(), and samchon::templates::parallel::MediatorSystem::~MediatorSystem().
virtual void samchon::templates::external::ExternalSystemArray::replyData (std::shared_ptr< protocol::Invoke > invoke) pure virtual
Handle an {} message have received.
Parameters
invoke An Invoke message have received.
Referenced by samchon::templates::external::ExternalSystem::replyData().
virtual auto samchon::templates::external::ExternalSystemArray::CHILD_TAG () const -> std::string inline override virtual
A tag name of children.
< TAG>
<CHILD_TAG />
<CHILD_TAG />
</TAG>
Implements samchon::protocol::EntityGroupBase.
Definition at line 147 of file ExternalSystemArray.hpp.
The documentation for this class was generated from the following files:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/templates/external/ExternalSystemArray.hpp
D:/OneDrive/Project/Samchon/framework/cpp/samchon/templates/external/ExternalSystemArray.cpp