Samchon Framework for CPP: samchon::example::packer::WrapperArray Class Reference
samchon::example::packer::WrapperArray Class Reference
An array of wrapper with same category (name).
#include <WrapperArray.hpp>
Public Member Functions
WrapperArray (Wrapper *)
Construct from a sample wrapper.
auto tryInsert (Product *) -> bool
Try to insert a product into reserved list.
void optimize ()
Optimize to retrieve the best solution.
auto calcPrice () const -> int
Calculate price of the Wrapper(s)
auto toString () const -> std::string
Return a string represents Wrapper(s) of same type.
Private Attributes
std::vector< Product * > reserved
A list for reserved Product(s).
Wrapper * sample
A sample wrapper used to copy.
Detailed Description
An array of wrapper with same category (name).
WrapperArray reserves Product(s) and generates enough number of Wrapper(s).
WrapperArray will retrieve the best arrange and packaging method for reserved Product(s).
Author
Jeongho Nam
Definition at line 26 of file WrapperArray.hpp.
Constructor & Destructor Documentation
WrapperArray::WrapperArray (Wrapper * sample)
Construct from a sample wrapper.
Parameters
sample A sample wrapper used to copy wrappers.
Definition at line 15 of file WrapperArray.cpp.
References sample.
Referenced by optimize().
Member Function Documentation
auto WrapperArray::tryInsert (Product * product) -> bool
Try to insert a product into reserved list.
If the Product's volume and weight is equal or less than the Wrapper categorized so that enable to insert in a Wrapper, reserve the Product and returns true. If not, does not reserve and just return false.
Returns
Whether the Product's volume and weight is equal or less than the Wrapper.
Definition at line 24 of file WrapperArray.cpp.
Referenced by optimize().
void WrapperArray::optimize ()
Optimize to retrieve the best solution.
Retrieve the best solution of packaging in level of WrapperArray.
Shuffles sequence of reserved Product(s) by samchon::library::FactorialGenerator and insert the reserved Products(s) following the sequence creating Wrapper(s) as needed. Between the sequences from FactorialGenerator, retrieve and determine the best solution.
Note
Sequence of inserting Product can affeact to numbers of Wrapper(s) to be used.
It's the reason why even WrapperArray has the optimize() method.
See also
samchon::library::FactorialGenerator
Definition at line 35 of file WrapperArray.cpp.
References reserved, sample, samchon::example::packer::Wrapper::tryInsert(), tryInsert(), and WrapperArray().
auto WrapperArray::calcPrice () const -> int
Calculate price of the Wrapper(s)
Calculate price of all wrapppers'. The price does not contain inserted products'
Definition at line 75 of file WrapperArray.cpp.
References samchon::example::packer::Instance::getPrice(), and sample.
auto WrapperArray::toString () const -> std::string
Return a string represents Wrapper(s) of same type.
Definition at line 83 of file WrapperArray.cpp.
References samchon::example::packer::Instance::getName(), and sample.
Member Data Documentation
std::vector<Product*> samchon::example::packer::WrapperArray::reserved private
A list for reserved Product(s).
Definition at line 35 of file WrapperArray.hpp.
Referenced by optimize().
Wrapper* samchon::example::packer::WrapperArray::sample private
A sample wrapper used to copy.
Definition at line 40 of file WrapperArray.hpp.
Referenced by calcPrice(), optimize(), toString(), and WrapperArray().
The documentation for this class was generated from the following files:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/examples/packer/WrapperArray.hpp
D:/OneDrive/Project/Samchon/framework/cpp/samchon/examples/packer/WrapperArray.cpp