Samchon Framework for CPP: samchon::example::packer::Instance Class Reference
samchon::example::packer::Instance Class Reference
A physical instance.
#include <Instance.hpp>
Public Member Functions
Instance ()
Default Constructor.
Instance (const std::string &name, int price, int volume, int weight)
Construct from instance.
virtual void construct (std::shared_ptr< library::XML > xml) override
Construct data of the Entity from an XML object.
auto getName () const -> std::string
Get name.
auto getPrice () const -> int
Get price.
auto getVolume () const -> int
Get volume.
auto getWeight () const -> int
Get weight.
virtual auto toXML () const -> std::shared_ptr< library::XML > override
Get an XML object represents the Entity.
virtual auto toString () const -> std::string
Return a string represents the Instance.
Public Member Functions inherited from samchon::protocol::Entity
virtual auto TAG () const -> std::string=0
A tag name when represented by XML.
Entity ()
Default Constructor.
virtual auto key () const -> std::string
Get a key that can identify the Entity uniquely.
Protected Attributes
std::string name
Name represent the Instance.
int price
Price of an instance -> 1,000 won.
int volume
Volume of an instance -> 130 cm^3.
int weight
Weight of an instance -> 1,200 g.
Detailed Description
A physical instance.
A physical instance having its own name, price, volume and weight.
Author
Jeongho Nam
Definition at line 24 of file Instance.hpp.
Constructor & Destructor Documentation
samchon::example::packer::Instance::Instance () inline
Default Constructor.
Definition at line 58 of file Instance.hpp.
samchon::example::packer::Instance::Instance (const std::string & name, int price, int volume, int weight) inline
Construct from instance.
Parameters
name Name of the instance
price Price of the instance
volume Volume of the instance
weight Weight of the instance
Definition at line 71 of file Instance.hpp.
References name, price, volume, and weight.
Member Function Documentation
virtual void samchon::example::packer::Instance::construct (std::shared_ptr< library::XML >) inline override virtual
Construct data of the Entity from an XML object.
Overrides the construct() method and fetch data of member variables from the XML.
By recommended guidance, data representing member variables are contained in properties of the put XML object.
Parameters
xml An xml used to construct data of entity
Implements samchon::protocol::Entity.
Reimplemented in samchon::example::packer::Wrapper.
Definition at line 82 of file Instance.hpp.
Referenced by samchon::example::packer::Wrapper::construct().
auto samchon::example::packer::Instance::getName () const -> std::string inline
Get name.
Definition at line 96 of file Instance.hpp.
References name.
auto samchon::example::packer::Instance::getPrice () const -> int inline
Get price.
Definition at line 104 of file Instance.hpp.
References price.
auto samchon::example::packer::Instance::getVolume () const -> int inline
Get volume.
Definition at line 112 of file Instance.hpp.
References volume.
auto samchon::example::packer::Instance::getWeight () const -> int inline
Get weight.
Definition at line 120 of file Instance.hpp.
References weight.
virtual auto samchon::example::packer::Instance::toXML () const -> std::shared_ptr<library::XML> inline override virtual
Get an XML object represents the Entity.
Returns an XML object that can represents the Entity containing member variables into properties.
A member variable (not object, but atomic value like number, string or date) is categorized as a property within the framework of entity side. Thus, when overriding a toXML() method and archiving member variables to an XML object to return, puts each variable to be a property belongs to only an XML object.
Don't archive the member variable of atomic value to XML::value causing enormouse creation of XML objects to number of member variables. An Entity must be represented by only an XML instance (tag).
Standard Usage Non-standard usage abusing value
<memberList>
<member id='jhnam88' name='Jeongho+Nam' birthdate='1988-03-11' />
<member id='master' name='Administartor' birthdate='2011-07-28' />
</memberList> <member>
<id>jhnam88</id>
<name>Jeongho+Nam</name>
<birthdate>1988-03-11</birthdate>
</member>
Returns
An XML object representing the Entity.
Reimplemented from samchon::protocol::Entity.
Reimplemented in samchon::example::packer::Wrapper.
Definition at line 128 of file Instance.hpp.
References samchon::protocol::Entity::toXML().
Referenced by samchon::example::packer::Wrapper::toXML().
virtual auto samchon::example::packer::Instance::toString () const -> std::string inline virtual
Return a string represents the Instance.
Reimplemented in samchon::example::packer::Wrapper, and samchon::example::packer::Product.
Definition at line 142 of file Instance.hpp.
References samchon::library::StringUtil::substitute().
Referenced by samchon::example::packer::Product::toString(), and samchon::example::packer::Wrapper::toString().
Member Data Documentation
std::string samchon::example::packer::Instance::name protected
Name represent the Instance.
Definition at line 34 of file Instance.hpp.
Referenced by getName(), and Instance().
int samchon::example::packer::Instance::price protected
Price of an instance -> 1,000 won.
Definition at line 39 of file Instance.hpp.
Referenced by getPrice(), and Instance().
int samchon::example::packer::Instance::volume protected
Volume of an instance -> 130 cm^3.
Definition at line 44 of file Instance.hpp.
Referenced by getVolume(), Instance(), and samchon::example::packer::Wrapper::tryInsert().
int samchon::example::packer::Instance::weight protected
Weight of an instance -> 1,200 g.
Definition at line 49 of file Instance.hpp.
Referenced by getWeight(), Instance(), and samchon::example::packer::Wrapper::tryInsert().
The documentation for this class was generated from the following file:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/example/packer/Instance.hpp