Samchon Framework for CPP: samchon::protocol::IWebClient Class Reference
samchon::protocol::IWebClient Class Reference
An interface for a web-client.
#include <IWebClient.hpp>
Public Member Functions
IWebClient ()
Default Constructor.
virtual void listen () override
Listens message from a related system.
virtual void sendData (std::shared_ptr< Invoke >) override
Sends message to a related system.
Public Member Functions inherited from samchon::protocol::IClient
IClient ()
Default Constructor.
Public Member Functions inherited from samchon::protocol::IProtocol
virtual void replyData (std::shared_ptr< Invoke >)=0
Reply a message.
Additional Inherited Members
Protected Member Functions inherited from samchon::protocol::IClient
virtual auto BUFFER_SIZE () const -> size_t
Buffer size of network I/O.
virtual void _replyData (std::shared_ptr< Invoke >)
A method for pre-processing replied Invoke message.
Protected Attributes inherited from samchon::protocol::IClient
Socket * socket
Socket for network I/O.
std::mutex * sendMtx
A mutex for sending message.
Detailed Description
An interface for a web-client.
IWebClient is a IClient following web-socket protocol.
[Inherited]
IClient is an interface not only for a physical client, but also a driver for a client in a physical server.
IServer:addClient()
service::Server -> service::User -> service::Client
ExternalClientArray (A physical server) -> ExternalClient (A driver of a client)
IClient is one of the basic 3 + 1 components that can make any type of network system in Samchon Framework with IProtocol and IServer. Looking around classes in Samchon Framework, you can see all classes related with client are implemented from the IClient.
IClient takes a role of real network I/O. IClient sends data to otherside network system from IProtocol::sendData(). IClient also gets data from otherside network system, generates standard Invoke message from parsing the replied data and shift the Invoke message to IProtocol::replyData().
Author
Jeongho Nam http://samchon.org
Definition at line 26 of file IWebClient.hpp.
Constructor & Destructor Documentation
IWebClient::IWebClient ()
Default Constructor.
Definition at line 23 of file IWebClient.cpp.
References samchon::protocol::IClient::socket.
Member Function Documentation
void IWebClient::listen () override virtual
Listens message from a related system.
Note
It holds (monopolies) a thread.
Reimplemented from samchon::protocol::IClient.
Definition at line 140 of file IWebClient.cpp.
References samchon::protocol::IClient::_replyData(), and samchon::protocol::IClient::socket.
void IWebClient::sendData (std::shared_ptr< Invoke >) override virtual
Sends message to a related system.
Parameters
invoke Invoke message to send
Reimplemented from samchon::protocol::IClient.
Definition at line 308 of file IWebClient.cpp.
References samchon::protocol::IClient::sendMtx, samchon::protocol::IClient::socket, samchon::ByteArray::write(), and samchon::ByteArray::writeReversely().
The documentation for this class was generated from the following files:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/protocol/IWebClient.hpp
D:/OneDrive/Project/Samchon/framework/cpp/samchon/protocol/IWebClient.cpp