Samchon Framework for CPP: samchon::example::interaction::PackerSlave Class Reference
samchon::example::interaction::PackerSlave Class Reference
A slave system for solving Packer.
#include <PackerSlave.hpp>
Public Member Functions
PackerSlave (const string &ip, int port)
Construct from ip and port of the master.
Public Member Functions inherited from samchon::example::interaction::Slave
Slave (const string &ip, int port)
Construct from ip address and port number of master.
Public Member Functions inherited from samchon::protocol::slave::ParallelClient
ParallelClient ()
Default Constructor.
Public Member Functions inherited from samchon::protocol::slave::ParallelSystem
ParallelSystem ()
Default Constructor.
virtual void replyPieceData (std::shared_ptr< Invoke >, size_t, size_t)=0
Handle requested processes which are segmented.
Public Member Functions inherited from samchon::protocol::slave::SlaveSystem
SlaveSystem ()
Default Constructor.
Public Member Functions inherited from samchon::protocol::ExternalSystem
ExternalSystem ()
Default Constructor.
virtual auto key () const -> std::string override
Get a key that can identify the Entity uniquely.
virtual void replyData (std::shared_ptr< Invoke >) override
Handling replied message from an external system.
virtual auto TAG () const -> std::string override
A tag name when represented by XML.
virtual auto CHILD_TAG () const -> std::string override
A tag name of children.
Public Member Functions inherited from samchon::protocol::EntityGroup< Container, T >
auto find (const std::string &key) -> typename container_type::iterator
Get iterator to element.
auto find (const std::string &key) const -> typename container_type::const_iterator
Get const iterator to element.
auto has (const std::string &key) const -> bool
Indicates whether a container has an object having the specified identifier.
auto count (const std::string &key) const -> size_t
Count elements with a specific key.
auto get (const std::string &key) -> typename container_type::value_type &
Access the element by specified identifier(key).
auto get (const std::string &key) const -> const typename container_type::value_type &
Access the const element by specified identifier(key).
Public Member Functions inherited from samchon::protocol::IClient
IClient ()
Default Constructor.
virtual void listen ()
Listens message from a related system.
virtual void sendData (std::shared_ptr< Invoke >)
Sends message to a related system.
Public Member Functions inherited from samchon::protocol::slave::SlaveClient
SlaveClient ()
Default Constructor.
Public Member Functions inherited from samchon::protocol::ExternalServer
ExternalServer ()
Default Constructor.
virtual void construct (std::shared_ptr< library::XML >) override
Construct data of the Entity from an XML object.
virtual void start () override
Start interaction.
virtual auto getIP () const -> std::string override
Destinatio IP.
virtual auto getPort () const -> int override
Destination port.
virtual auto getMyIP () const -> std::string override
(optional) My IP, if you want to bind
virtual auto toXML () const -> std::shared_ptr< library::XML > override
Get an XML object represents the EntityGroup.
Public Member Functions inherited from samchon::protocol::ServerConnector
ServerConnector ()
Default Constructor.
virtual void connect ()
Connect to a server.
Static Public Member Functions
static void main ()
Main function.
Protected Member Functions
virtual void optimize (shared_ptr< XML > xml, size_t index, size_t size) override
Optimize TSP and report the result.
Protected Member Functions inherited from samchon::example::interaction::Slave
void sendOptimization (shared_ptr< XML > xml)
Send (report) optimization result to its master system.
Protected Member Functions inherited from samchon::protocol::slave::ParallelSystem
virtual auto createChild (std::shared_ptr< library::XML >) -> ExternalSystemRole *override
Factory method of a child Entity.
virtual void _replyData (std::shared_ptr< Invoke >) override
Pre-processor for segmented processes and reporting elapsed time.
Protected Member Functions inherited from samchon::protocol::IClient
virtual auto BUFFER_SIZE () const -> size_t
Buffer size of network I/O.
Additional Inherited Members
Protected Attributes inherited from samchon::protocol::ExternalSystem
std::string name
A name can identify an external system.
std::string ip
An ip address of an external system.
int port
A port number of an external system.
Protected Attributes inherited from samchon::protocol::IClient
Socket * socket
Socket for network I/O.
std::mutex * sendMtx
A mutex for sending message.
Protected Attributes inherited from samchon::protocol::ExternalServer
std::string myIP
A custom ip address of my system to bind.
Protected Attributes inherited from samchon::protocol::ServerConnector
boost::asio::io_service * ioService
An io_service of Boost.Asio's own.
EndPoint * endPoint
An endpoint directing a server.
EndPoint * localEndPoint
(Optional) An local endpoint of the client (my system)
Detailed Description
A slave system for solving Packer.
[Inherited]
Author
Jeongho Nam http://samchon.org
Definition at line 27 of file PackerSlave.hpp.
Constructor & Destructor Documentation
samchon::example::interaction::PackerSlave::PackerSlave (const string & ip, int port) inline
Construct from ip and port of the master.
Parameters
ip IP address of the master.
port Port number of the master.
Definition at line 43 of file PackerSlave.hpp.
Member Function Documentation
virtual void samchon::example::interaction::PackerSlave::optimize (shared_ptr< XML > xml, size_t index, size_t size) inline override protected virtual
Optimize TSP and report the result.
Parameters
xml XML object representing a Travel.
index Starting index of a segmentation allocated to the Slave.
size Size of the segmentation.
Reimplemented from samchon::example::interaction::Slave.
Definition at line 60 of file PackerSlave.hpp.
References samchon::example::packer::Packer::optimize(), samchon::example::packer::Packer::toString(), and samchon::example::packer::Packer::toXML().
static void samchon::example::interaction::PackerSlave::main () inline static
Main function.
Definition at line 79 of file PackerSlave.hpp.
References samchon::protocol::ExternalServer::start().
The documentation for this class was generated from the following file:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/example/interaction/PackerSlave.hpp