Samchon Framework for CPP: samchon::protocol::IServer Class Reference
samchon::protocol::IServer Class Reference abstract
An interface of a physical server.
#include <IServer.hpp>
Public Member Functions
IServer ()
Default Constructor.
virtual void open ()
Open the server.
virtual void close ()
Close the server.
Protected Member Functions
virtual auto MY_IP () const -> std::string
(optional) Server's IP
virtual auto PORT () const -> int=0
Port number of the server.
virtual void addClient (Socket *)=0
Handling connection of a physical client.
Protected Attributes
Acceptor * acceptor
An acceptor for clients.
Detailed Description
An interface of a physical server.
IServer provides methods for opening a server.
IServer is one of the basic 3 + 1 components that can make any type of network system in Samchon Framework with IProtocol and IClient. Looking around classes in Samchon Framework, you can see all servers are implemented from the IServer.
When a client connects to the server, the abstract method IServer::addClient() is called with a new thread. If you want to accept only a client at a time, use OneToOneServer instead.
Example source
A simple chat server running on console
example/console_chat_server/ChatServer.hpp
 #pragma once
 #include <samchon/protocol/IServer.hpp>
 #include <samchon/protocol/IProtocol.hpp>
 #include <set>
 #include <samchon/library/RWMutex.hpp>
 namespace samchon
 {
     namespace example
     {
         namespace console_chat_server
         {
             class ChatClient;
             class ChatServer
                 : public protocol::IServer,
                 public protocol::IProtocol
             {
             private:
                 typedef protocol::IServer super;
                 std::set<ChatClient*> clientSet;
                 library::RWMutex rwMutex;
             public:
                 ChatServer();
                 virtual ~ChatServer() = default;
                 void eraseClient(ChatClient *client);
             protected:
                 virtual auto PORT() const -> int override
                 {
                     return 37749;
                 };
                 virtual void addClient(protocol::Socket *socket) override;
             public:
                 virtual void replyData(std::shared_ptr<protocol::Invoke>) override;
                 virtual void sendData(std::shared_ptr<protocol::Invoke>) override;
             };
         };
     };
 };
example/console_chat_server/ChatServer.cpp
 #include <samchon/examples/console_chat_server/ChatServer.hpp>
 #include <samchon/examples/console_chat_server/ChatClient.hpp>
 #include <thread>
 #include <samchon/protocol/Invoke.hpp>
 using namespace std;
 using namespace samchon::library;
 using namespace samchon::protocol;
 using namespace samchon::example::console_chat_server;
 ChatServer::ChatServer()
     : super()
 {
 }
 void ChatServer::addClient(Socket *socket)
 {
     ChatClient *client = new ChatClient(this, socket);
     UniqueWriteLock uk(rwMutex);
     clientSet.insert(client);
     thread(&ChatClient::listen, client).detach();
 }
 void ChatServer::eraseClient(ChatClient *client)
 {
     UniqueWriteLock uk(rwMutex);
     clientSet.erase(client);
 }
 void ChatServer::replyData(shared_ptr<Invoke> invoke)
 {
     sendData(invoke);
 }
 void ChatServer::sendData(shared_ptr<Invoke> invoke)
 {
     UniqueReadLock uk(rwMutex);
     for(auto it = clientSet.begin(); it != clientSet.end(); it++)
         (*it)->sendData(invoke);
 }
example/console_chat_server/ChatClient.hpp
 #pragma once
 #include <samchon/protocol/IClient.hpp>
 namespace samchon
 {
     namespace example
     {
         namespace console_chat_server
         {
             class ChatServer;
             class ChatClient
                 : public protocol::IClient
             {
             private:
                 typedef protocol::IClient super;
                 ChatServer *server;
             public:
                 ChatClient(ChatServer*, protocol::Socket*);
                 virtual ~ChatClient();
                 virtual void replyData(std::shared_ptr<protocol::Invoke>) override;
             };
         };
     };
 };
example/console_chat_server/ChatClient.cpp
 #include <samchon/examples/console_chat_server/ChatClient.hpp>
 #include <samchon/examples/console_chat_server/ChatServer.hpp>
 #include <samchon/protocol/Invoke.hpp>
 using namespace std;
 using namespace samchon::library;
 using namespace samchon::protocol;
 using namespace samchon::example::console_chat_server;
 ChatClient::ChatClient(ChatServer *server, Socket *socket)
     : super()
 {
     this->server = server;
     this->socket = socket;
 }
 ChatClient::~ChatClient()
 {
     server->eraseClient(this);
 }
 void ChatClient::replyData(shared_ptr<Invoke> invoke)
 {
     server->replyData(invoke);
 }
example/console_chat_server/main.cpp
 #include <iostream>
 #include <samchon/examples/console_chat_server/ChatServer.hpp>
 #ifdef _WIN64
 #   ifdef _DEBUG
 #       pragma comment(lib, "x64/Debug/SamchonFramework.lib")
 #   else
 #       pragma comment(lib, "x64/Release/SamchonFramework.lib")
 #   endif
 #else
 #   ifdef _DEBUG
 #       pragma comment(lib, "Debug/SamchonFramework.lib")
 #   else
 #       pragma comment(lib, "Release/SamchonFramework.lib")
 #   endif
 #endif
 using namespace samchon::example::console_chat_server;
 void main()
 {
     ChatServer chatServer;
     chatServer.open();
     system("pause");
 }
Author
Jeongho Nam http://samchon.org
Definition at line 43 of file IServer.hpp.
Constructor & Destructor Documentation
IServer::IServer ()
Default Constructor.
Definition at line 18 of file IServer.cpp.
Member Function Documentation
auto IServer::MY_IP () const -> std::string protected virtual
(optional) Server's IP
Reimplemented in samchon::protocol::ExternalClientArray.
Definition at line 16 of file IServer.cpp.
Referenced by samchon::protocol::IWebServer::open().
virtual auto samchon::protocol::IServer::PORT () const -> int protected pure virtual
Port number of the server.
Implemented in samchon::example::interaction::ChiefDriver, samchon::example::console_chat_server::ChatServer, samchon::protocol::ExternalClientArray, and samchon::example::chat_service::ChatServer.
Referenced by samchon::protocol::IWebServer::open().
void IServer::open () virtual
Open the server.
Note
It holds (monopolies) a thread.
Reimplemented in samchon::protocol::IWebServer.
Definition at line 30 of file IServer.cpp.
References addClient().
Referenced by samchon::example::interaction::Reporter::main(), and samchon::protocol::ExternalClientArray::start().
void IServer::close () virtual
Close the server.
Definition at line 66 of file IServer.cpp.
virtual void samchon::protocol::IServer::addClient (Socket *) protected pure virtual
Handling connection of a physical client.
Implemented in samchon::example::interaction::Master, samchon::protocol::service::Server, samchon::example::interaction::PackerMediator, samchon::example::interaction::ChiefDriver, samchon::example::console_chat_server::ChatServer, samchon::example::interaction::Reporter, samchon::protocol::ExternalClientArray, and samchon::protocol::IWebServer.
Referenced by open().
Member Data Documentation
Acceptor* samchon::protocol::IServer::acceptor protected
An acceptor for clients.
Definition at line 49 of file IServer.hpp.
Referenced by samchon::protocol::IWebServer::open().
The documentation for this class was generated from the following files:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/protocol/IServer.hpp
D:/OneDrive/Project/Samchon/framework/cpp/samchon/protocol/IServer.cpp