Samchon Framework for CPP: samchon::IndexPair< T > Class Template Reference
samchon::IndexPair< T > Class Template Reference
A pair of index and its value(T)
#include <IndexPair.hpp>
Public Member Functions
IndexPair ()
Default Constructor.
template<class U >
IndexPair (const IndexPair< U > &obj)
Copy Constructor.
template<class U >
IndexPair (const IndexPair< U > &&obj)
Move Constructor.
IndexPair (size_t index, const T &val)
Construct from members.
auto get_index () const -> size_t
Get index.
auto getValue () -> T &
Get reference of value.
auto getValue () const -> const T &
Get const reference of const value.
Detailed Description
template<class T>
class samchon::IndexPair< T >
A pair of index and its value(T)
Template Parameters
T Type of value.
IndexPair is a std::pair<size_t, T> class.
IndexPair expresses index and value. It's useful for expressing finding literals, specified object, calculating mininum or maximum with its position.
[Inherited]
This class couples together a pair of values, which may be of different types (T1 and T2). The individual values can be accessed through its public members first and second.
Pairs are a particular case of tuple.
Referenced comments of std::pair
http://www.cplusplus.com/reference/utility/pair/
Author
Jeongho Nam http://samchon.org
Definition at line 30 of file IndexPair.hpp.
Constructor & Destructor Documentation
template<class T> samchon::IndexPair< T >::IndexPair () inline
Default Constructor.
Definition at line 45 of file IndexPair.hpp.
template<class T> template<class U > samchon::IndexPair< T >::IndexPair (const IndexPair< U > & obj) inline
Copy Constructor.
Definition at line 53 of file IndexPair.hpp.
template<class T> template<class U > samchon::IndexPair< T >::IndexPair (const IndexPair< U > && obj) inline
Move Constructor.
Definition at line 61 of file IndexPair.hpp.
template<class T> samchon::IndexPair< T >::IndexPair (size_t index, const T & val) inline
Construct from members.
Definition at line 69 of file IndexPair.hpp.
Member Function Documentation
template<class T> auto samchon::IndexPair< T >::get_index () const -> size_t inline
Get index.
Returns
Index of the pair
Definition at line 82 of file IndexPair.hpp.
Referenced by samchon::WeakString::finds(), samchon::library::StringUtil::finds(), samchon::WeakString::rfinds(), samchon::library::StringUtil::rfinds(), and samchon::WeakString::rtrim().
template<class T> auto samchon::IndexPair< T >::getValue () -> T& inline
Get reference of value.
Returns
Reference of value of the pair
Definition at line 92 of file IndexPair.hpp.
Referenced by samchon::WeakString::finds(), samchon::library::StringUtil::finds(), samchon::WeakString::rfinds(), samchon::library::StringUtil::rfinds(), and samchon::WeakString::rtrim().
template<class T> auto samchon::IndexPair< T >::getValue () const -> const T& inline
Get const reference of const value.
Returns
Const reference of value of the pair
Definition at line 102 of file IndexPair.hpp.
The documentation for this class was generated from the following file:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/IndexPair.hpp