Samchon Framework for CPP: samchon::protocol::ExternalServer Class Reference
samchon::protocol::ExternalServer Class Reference
A network driver for an external server.
#include <ExternalServer.hpp>
Public Member Functions
ExternalServer ()
Default Constructor.
virtual void construct (std::shared_ptr< library::XML >) override
Construct data of the Entity from an XML object.
virtual void start () override
Start interaction.
virtual auto getIP () const -> std::string override
Destinatio IP.
virtual auto getPort () const -> int override
Destination port.
virtual auto getMyIP () const -> std::string override
(optional) My IP, if you want to bind
virtual auto toXML () const -> std::shared_ptr< library::XML > override
Get an XML object represents the EntityGroup.
Public Member Functions inherited from samchon::protocol::ExternalSystem
ExternalSystem ()
Default Constructor.
virtual auto key () const -> std::string override
Get a key that can identify the Entity uniquely.
virtual void replyData (std::shared_ptr< Invoke >) override
Handling replied message from an external system.
virtual auto TAG () const -> std::string override
A tag name when represented by XML.
virtual auto CHILD_TAG () const -> std::string override
A tag name of children.
Public Member Functions inherited from samchon::protocol::EntityGroup< _Container, _ETy, T >
EntityGroup ()
Default Constructor.
auto has (const std::string &key) const -> bool
Indicates whether a container has an object having the specified identifier.
auto get (const std::string &key) -> value_type &
Access the element by specified identifier(key).
auto get (const std::string &key) const -> const value_type &
Access the const element by specified identifier(key).
Public Member Functions inherited from samchon::protocol::Entity
Entity ()
Default Constructor.
Public Member Functions inherited from samchon::protocol::IEntityGroup
IEntityGroup ()
Default Constructor.
Public Member Functions inherited from samchon::protocol::IClient
IClient ()
Default Constructor.
virtual void listen ()
Listens message from a related system.
virtual void sendData (std::shared_ptr< Invoke >)
Sends message to a related system.
Public Member Functions inherited from samchon::protocol::IProtocol
IProtocol ()
Default Constructor.
Public Member Functions inherited from samchon::protocol::ServerConnector
ServerConnector ()
Default Constructor.
virtual void connect ()
Connect to a server.
Protected Attributes
std::string myIP
A custom ip address of my system to bind.
Protected Attributes inherited from samchon::protocol::ExternalSystem
std::string name
A name can identify an external system.
std::string ip
An ip address of an external system.
int port
A port number of an external system.
Protected Attributes inherited from samchon::protocol::IClient
Socket * socket
Socket for network I/O.
std::mutex * sendMtx
A mutex for sending message.
Protected Attributes inherited from samchon::protocol::ServerConnector
boost::asio::io_service * ioService
An io_service of Boost.Asio's own.
EndPoint * endPoint
An endpoint directing a server.
EndPoint * localEndPoint
(Optional) An local endpoint of the client (my system)
Additional Inherited Members
Protected Member Functions inherited from samchon::protocol::EntityGroup< _Container, _ETy, T >
virtual auto createChild (std::shared_ptr< library::XML >) -> entity_type *=0
Factory method of a child Entity.
Protected Member Functions inherited from samchon::protocol::IClient
virtual auto BUFFER_SIZE () const -> size_t
Buffer size of network I/O.
virtual void _replyData (std::shared_ptr< Invoke >)
A method for pre-processing replied Invoke message.
Detailed Description
A network driver for an external server.
ExternalServer is an ExternalSystem specialized in server driver.
[Inherited]
ExternalSystem is a boundary class interacting with an external system by network communication. Also, ExternalSystem is an abstract class that a network role, which one is server and which one is client, is not determined yet.
The ExternalSystem has ExternalSystemRole(s) groupped methods, handling Invoke message interacting with the external system, by subject or unit of a moudle. The ExternalSystemRole is categorized in a 'control'.
Example Sources
example::interaction
Note
The ExternalSystem class takes a role of interaction with external system in network level. However, within a framework of Samchon Framework, a boundary class like the ExternalSystem is not such important. You can find some evidence in a relationship between ExternalSystemArray, ExternalSystem and ExternalSystemRole.
Of course, the ExternalSystemRole is belonged to an ExternalSystem. However, if you access an ExternalSystemRole from an ExternalSystemArray directly, not passing by a belonged ExternalSystem, and send an Invoke message even you're not knowing which ExternalSystem is related in, it's called "Proxy pattern".
Like the explanation of "Proxy pattern", you can utilize an ExternalSystemRole as a proxy of an ExternalSystem. With the pattern, you can only concentrate on ExternalSystemRole itself, what to do with Invoke message, irrespective of the ExternalSystemRole is belonged to which ExternalSystem.
See also
samchon::protocol
Author
Jeongho Nam http://samchon.org
Definition at line 20 of file ExternalServer.hpp.
Constructor & Destructor Documentation
ExternalServer::ExternalServer ()
Default Constructor.
Definition at line 13 of file ExternalServer.cpp.
Member Function Documentation
void ExternalServer::construct (std::shared_ptr< library::XML > xml) override virtual
Construct data of the Entity from an XML object.
Constructs the EntityGroup's own member variables only from the input XML object.
Do not consider about constructing children Entity objects' data in EntityGroup::construct(). Those children Entity objects' data will constructed by their own construct() method. Even insertion of XML objects representing children are done by abstract method of EntityGroup::toXML().
Constructs only data of EntityGroup's own.
[Inherited]
Construct data of the Entity from an XML object.
Overrides the construct() method and fetch data of member variables from the XML.
By recommended guidance, data representing member variables are contained in properties of the put XML object.
Parameters
xml An xml used to construct data of entity
Reimplemented from samchon::protocol::ExternalSystem.
Reimplemented in samchon::protocol::master::DistributedServer, and samchon::protocol::master::ParallelServer.
Definition at line 18 of file ExternalServer.cpp.
References samchon::protocol::ExternalSystem::construct(), and myIP.
void ExternalServer::start () override virtual
Start interaction.
An abstract method starting interaction with an external system.
If an external systems are a server, starts connection and listening Inovoke message, else clients, just starts listening only. You also can addict your own procudures of starting the driver, but if you directly override method of abstract ExternalSystem, be careful about virtual inheritance.
Implements samchon::protocol::ExternalSystem.
Definition at line 28 of file ExternalServer.cpp.
References samchon::protocol::ServerConnector::connect(), and samchon::protocol::IClient::listen().
Referenced by samchon::example::interaction::TSPSlave::main(), and samchon::example::interaction::PackerSlave::main().
auto ExternalServer::getIP () const -> std::string override virtual
Destinatio IP.
Implements samchon::protocol::ServerConnector.
Definition at line 37 of file ExternalServer.cpp.
References samchon::protocol::ExternalSystem::ip.
auto ExternalServer::getPort () const -> int override virtual
Destination port.
Implements samchon::protocol::ServerConnector.
Definition at line 41 of file ExternalServer.cpp.
References samchon::protocol::ExternalSystem::port.
auto ExternalServer::getMyIP () const -> std::string override virtual
(optional) My IP, if you want to bind
Reimplemented from samchon::protocol::ServerConnector.
Definition at line 46 of file ExternalServer.cpp.
References myIP.
auto ExternalServer::toXML () const -> std::shared_ptr<library::XML> override virtual
Get an XML object represents the EntityGroup.
Archives the EntityGroup's own member variables only to the returned XML object.
Do not consider about archiving children Entity objects' data in EntityGroup::toXML(). Those children Entity objects will converted to XML object by their own toXML() method. The insertion of XML objects representing children are done by abstract method of EntityGroup::toXML().
Archives only data of EntityGroup's own.
[Inherited]
Get an XML object represents the Entity.
Returns an XML object that can represents the Entity containing member variables into properties.
A member variable (not object, but atomic value like number, string or date) is categorized as a property within the framework of entity side. Thus, when overriding a toXML() method and archiving member variables to an XML object to return, puts each variable to be a property belongs to only an XML object.
Don't archive the member variable of atomic value to XML::value causing enormouse creation of XML objects to number of member variables. An Entity must be represented by only an XML instance (tag).
Standard Usage Non-standard usage abusing value
<memberList>
<member id='jhnam88' name='Jeongho+Nam' birthdate='1988-03-11' />
<member id='master' name='Administartor' birthdate='2011-07-28' />
</memberList> <member>
<id>jhnam88</id>
<name>Jeongho+Nam</name>
<birthdate>1988-03-11</birthdate>
</member>
Returns
An XML object representing the Entity.
Reimplemented from samchon::protocol::ExternalSystem.
Reimplemented in samchon::protocol::master::DistributedServer, and samchon::protocol::master::ParallelServer.
Definition at line 54 of file ExternalServer.cpp.
References myIP, and samchon::protocol::ExternalSystem::toXML().
Member Data Documentation
std::string samchon::protocol::ExternalServer::myIP protected
A custom ip address of my system to bind.
Definition at line 31 of file ExternalServer.hpp.
Referenced by samchon::protocol::master::ParallelServer::construct(), construct(), getMyIP(), samchon::protocol::master::ParallelSlaveClientMediator::ParallelSlaveClientMediator(), samchon::protocol::master::ParallelServer::toXML(), and toXML().
The documentation for this class was generated from the following files:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/protocol/ExternalServer.hpp
D:/OneDrive/Project/Samchon/framework/cpp/samchon/protocol/ExternalServer.cpp