Samchon Framework for CPP: samchon::protocol::IEntityGroup Class Reference
samchon::protocol::IEntityGroup Class Reference abstract
An iternface for entity group.
#include <IEntityGroup.hpp>
Public Member Functions
IEntityGroup ()
Default Constructor.
Protected Member Functions
virtual auto CHILD_TAG () const -> std::string=0
A tag name of children.
Detailed Description
An iternface for entity group.
IEntityGroup is an interface for a container of entity. It does not have any special role or function. The IEntityGorup is only for discriminate an entity is single instance or gorup of entity.
Group of entity is divided into EntityArray and EntityGroup.
Even they are template classes so that cannot be discriminated globally.
dynamic_cast<IEntityGroup>(some entity instance)
If true then, it's not single entity instance, but group of entity.
False then, it's a single instance.
Author
Jeongho Nam http://samchon.org
Definition at line 32 of file IEntityGroup.hpp.
Constructor & Destructor Documentation
IEntityGroup::IEntityGroup ()
Default Constructor.
Definition at line 5 of file IEntityGroup.cpp.
Member Function Documentation
virtual auto samchon::protocol::IEntityGroup::CHILD_TAG () const -> std::string protected pure virtual
A tag name of children.
< TAG>
<CHILD_TAG />
<CHILD_TAG />
</TAG>
Implemented in samchon::example::packer::WrapperArray, samchon::example::packer::Packer, samchon::protocol::Invoke, samchon::example::tsp::Travel, samchon::namtree::NTCriteria, samchon::protocol::ExternalSystemArray, samchon::protocol::ExternalSystem, samchon::namtree::NTParameter, samchon::example::packer::ProductArray, samchon::example::chat_service::ChatRoomArray, samchon::protocol::InvokeHistoryArray, samchon::namtree::NTParameterArray, and samchon::library::FTFolder.
Referenced by samchon::protocol::EntityArray< T >::construct(), samchon::protocol::EntityList< T >::construct(), samchon::protocol::EntityGroup< _Container, _ETy, T >::construct(), samchon::protocol::EntityArray< T >::toXML(), samchon::protocol::EntityList< T >::toXML(), and samchon::protocol::EntityGroup< _Container, _ETy, T >::toXML().
The documentation for this class was generated from the following files:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/protocol/IEntityGroup.hpp
D:/OneDrive/Project/Samchon/framework/cpp/samchon/protocol/IEntityGroup.cpp