Samchon Framework for CPP: samchon::example::chat_service::ChatRoomArray Class Reference
samchon::example::chat_service::ChatRoomArray Class Reference
A manager of chat rooms.
#include <ChatRoomArray.hpp>
Public Member Functions
ChatRoomArray (ChatServer *)
Construct from a chat server.
void notify ()
Notify changes of chat rooms.
Protected Member Functions
virtual auto CHILD_TAG () const -> std::string
A tag name of children.
Private Member Functions
auto toXML () const -> std::shared_ptr< library::XML >
Get an XML object representing the ChatRoomArray.
auto toInvoke () const -> std::shared_ptr< protocol::Invoke >
Get an Invoke message used to notifying change.
Private Attributes
ChatServer * server
A chat server that rooms are belonged to.
Detailed Description
A manager of chat rooms.
An entity list of chat rooms and a manager of chat rooms taking a responsibility of notifying changes of children chat rooms to a related chat server.
Author
Jeongho Nam
Definition at line 31 of file ChatRoomArray.hpp.
Constructor & Destructor Documentation
ChatRoomArray::ChatRoomArray (ChatServer * server)
Construct from a chat server.
Definition at line 18 of file ChatRoomArray.cpp.
References server.
Member Function Documentation
virtual auto samchon::example::chat_service::ChatRoomArray::CHILD_TAG () const -> std::string inline protected virtual
A tag name of children.
< TAG>
<CHILD_TAG />
<CHILD_TAG />
</TAG>
Implements samchon::protocol::IEntityGroup.
Definition at line 39 of file ChatRoomArray.hpp.
void ChatRoomArray::notify ()
Notify changes of chat rooms.
Notify changes of chat rooms to all clients in the chat server.
Definition at line 25 of file ChatRoomArray.cpp.
References samchon::protocol::service::Server::begin(), samchon::protocol::service::Server::end(), server, and toInvoke().
Referenced by samchon::example::chat_service::ChatRoom::eraseClient(), and samchon::example::chat_service::ChatRoom::registerClient().
auto ChatRoomArray::toXML () const -> std::shared_ptr<library::XML> private
Get an XML object representing the ChatRoomArray.
Definition at line 45 of file ChatRoomArray.cpp.
Referenced by toInvoke().
auto ChatRoomArray::toInvoke () const -> std::shared_ptr<protocol::Invoke> private
Get an Invoke message used to notifying change.
Definition at line 56 of file ChatRoomArray.cpp.
References toXML().
Referenced by notify().
Member Data Documentation
ChatServer* samchon::example::chat_service::ChatRoomArray::server private
A chat server that rooms are belonged to.
Definition at line 39 of file ChatRoomArray.hpp.
Referenced by ChatRoomArray(), and notify().
The documentation for this class was generated from the following files:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/example/chat_service/ChatRoomArray.hpp
D:/OneDrive/Project/Samchon/framework/cpp/samchon/example/chat_service/ChatRoomArray.cpp