Samchon Framework for CPP: samchon::example::packer::Packer Class Reference
samchon::example::packer::Packer Class Reference
A packer planning the best packaging.
#include <Packer.hpp>
Public Member Functions
Packer ()
Default Constructor.
Packer (std::shared_ptr< ProductArray > productArray)
Construct from products and wrapper.
Packer (const Packer &packer)
Copy Constructor.
virtual void construct (std::shared_ptr< library::XML > xml) override
Construct data of the Entity from an XML object.
auto productSize () const -> size_t
Get number of products to package.
auto calcPrice () const -> int
Calculate price of the wrappers.
void optimize (size_t start=0, size_t size=-1)
Find the best packaging method.
virtual auto TAG () const -> std::string override
A tag name when represented by XML.
virtual auto CHILD_TAG () const -> std::string override
A tag name of children.
virtual auto toXML () const -> std::shared_ptr< library::XML > override
Get an XML object represents the EntityGroup.
auto toString () const -> std::string
Return a string represents an packaging method.
Public Member Functions inherited from samchon::protocol::EntityGroup< _Container, _ETy, _Ty >
EntityGroup ()
Default Constructor.
auto has (const std::string &key) const -> bool
Indicates whether a container has an object having the specified identifier.
auto get (const std::string &key) -> value_type &
Access the element by specified identifier(key).
auto get (const std::string &key) const -> const value_type &
Access the const element by specified identifier(key).
Public Member Functions inherited from samchon::protocol::Entity
Entity ()
Default Constructor.
virtual auto key () const -> std::string
Get a key that can identify the Entity uniquely.
Public Member Functions inherited from samchon::protocol::IEntityGroup
IEntityGroup ()
Default Constructor.
Protected Member Functions
virtual auto createChild (std::shared_ptr< library::XML >) -> WrapperArray *override
Factory method of a child Entity.
Protected Attributes
std::shared_ptr< ProductArray > productArray
Prodcut(s) to package in some Wrapper(s)
Detailed Description
A packer planning the best packaging.
Retrieves the solution of packaging by combination permuation and factorial case.
Warning
Be careful about number of products and wrappers.
The time complexity of Packer overs O(m^n). Elapsed time of calculation increases enourmously. Do not use Packer if the digits of number of products or wrappers overs 2.
Author
Jeongho Nam
Definition at line 31 of file Packer.hpp.
Constructor & Destructor Documentation
samchon::example::packer::Packer::Packer () inline
Default Constructor.
Definition at line 50 of file Packer.hpp.
Referenced by optimize().
samchon::example::packer::Packer::Packer (std::shared_ptr< ProductArray > productArray) inline
Construct from products and wrapper.
Parameters
productArray Product(s) to input some Wrapper
wrapperArray Type of Wrapper(s) to be used
Definition at line 62 of file Packer.hpp.
References productArray.
samchon::example::packer::Packer::Packer (const Packer & packer) inline
Copy Constructor.
Copy constructor of Packer does not copy children items.
Only copies member variables(productArray, wrapperArray) of Packer's.
Definition at line 75 of file Packer.hpp.
Member Function Documentation
virtual void samchon::example::packer::Packer::construct (std::shared_ptr< library::XML > xml) inline override virtual
Construct data of the Entity from an XML object.
Constructs the EntityGroup's own member variables only from the input XML object.
Do not consider about constructing children Entity objects' data in EntityGroup::construct(). Those children Entity objects' data will constructed by their own construct() method. Even insertion of XML objects representing children are done by abstract method of EntityGroup::toXML().
Constructs only data of EntityGroup's own.
[Inherited]
Reimplemented from samchon::protocol::EntityGroup< _Container, _ETy, _Ty >.
Definition at line 84 of file Packer.hpp.
References samchon::protocol::EntityGroup< _Container, _ETy, _Ty >::construct().
Referenced by samchon::example::interaction::PackerSlave::optimize(), and samchon::example::interaction::Reporter::printPacker().
virtual auto samchon::example::packer::Packer::createChild (std::shared_ptr< library::XML >) -> WrapperArray *override inline override protected virtual
Factory method of a child Entity.
EntityGroup::createChild() is a factory method creating a new child Entity which is belonged to the EntityGroup. This method is called by EntityGroup::construct(). The children construction methods Entity::construct() will be called by abstract method of the EntityGroup::construct().
Returns
A new child Entity belongs to EntityGroup.
Implements samchon::protocol::EntityGroup< _Container, _ETy, _Ty >.
Definition at line 92 of file Packer.hpp.
auto samchon::example::packer::Packer::productSize () const -> size_t inline
Get number of products to package.
Definition at line 104 of file Packer.hpp.
auto samchon::example::packer::Packer::calcPrice () const -> int inline
Calculate price of the wrappers.
Definition at line 112 of file Packer.hpp.
Referenced by toString().
void samchon::example::packer::Packer::optimize (size_t start = 0, size_t size = -1) inline
Find the best packaging method.
Definition at line 127 of file Packer.hpp.
References Packer(), and samchon::library::CaseGenerator::size().
Referenced by samchon::example::interaction::PackerSlave::optimize().
virtual auto samchon::example::packer::Packer::TAG () const -> std::string inline override virtual
A tag name when represented by XML.
Returns
A tag name
Implements samchon::protocol::Entity.
Definition at line 178 of file Packer.hpp.
virtual auto samchon::example::packer::Packer::CHILD_TAG () const -> std::string inline override virtual
A tag name of children.
< TAG>
<CHILD_TAG />
<CHILD_TAG />
</TAG>
Implements samchon::protocol::IEntityGroup.
Definition at line 182 of file Packer.hpp.
virtual auto samchon::example::packer::Packer::toXML () const -> std::shared_ptr<library::XML> inline override virtual
Get an XML object represents the EntityGroup.
Archives the EntityGroup's own member variables only to the returned XML object.
Do not consider about archiving children Entity objects' data in EntityGroup::toXML(). Those children Entity objects will converted to XML object by their own toXML() method. The insertion of XML objects representing children are done by abstract method of EntityGroup::toXML().
Archives only data of EntityGroup's own.
[Inherited]
Reimplemented from samchon::protocol::EntityGroup< _Container, _ETy, _Ty >.
Definition at line 187 of file Packer.hpp.
References samchon::protocol::EntityGroup< _Container, _ETy, _Ty >::toXML().
Referenced by samchon::example::interaction::Chief::callPacker(), and samchon::example::interaction::PackerSlave::optimize().
auto samchon::example::packer::Packer::toString () const -> std::string inline
Return a string represents an packaging method.
Definition at line 198 of file Packer.hpp.
References calcPrice().
Referenced by samchon::example::interaction::PackerSlave::optimize(), and samchon::example::interaction::Reporter::printPacker().
Member Data Documentation
std::shared_ptr<ProductArray> samchon::example::packer::Packer::productArray protected
Prodcut(s) to package in some Wrapper(s)
Definition at line 41 of file Packer.hpp.
Referenced by Packer().
The documentation for this class was generated from the following file:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/example/packer/Packer.hpp