Samchon Framework for CPP: samchon::library::FTFactory Class Reference
samchon::library::FTFactory Class Reference abstract
A Factory and manager for file-tree.
#include <FTFactory.hpp>
Public Member Functions
FTFactory ()
Default Constructor.
virtual auto createFile (FTFolder *, std::shared_ptr< XML >) -> FTFile *=0
Factory method of a file.
void registerInstance (FTInstance *)
Register file instance to map.
Protected Attributes
int application
An application id.
int category
A categori id.
std::string member
Account id of a member.
Map< int, FTInstance * > instanceMap
Map of files.
Detailed Description
A Factory and manager for file-tree.
FTFactory is a class taking a role of creating FTFile instances and managing them by having their direct pointers. FTFactory also has a role of archiving and loading from DB.
See also
samchon::library
Author
Jeongho Nam
Definition at line 29 of file FTFactory.hpp.
Constructor & Destructor Documentation
FTFactory::FTFactory ()
Default Constructor.
Definition at line 12 of file FTFactory.cpp.
Member Function Documentation
virtual auto samchon::library::FTFactory::createFile (FTFolder * , std::shared_ptr< XML >) -> FTFile * pure virtual
Factory method of a file.
Referenced by samchon::library::FTFolder::FTFolder().
void FTFactory::registerInstance (FTInstance * instance)
Register file instance to map.
Definition at line 16 of file FTFactory.cpp.
References samchon::library::FTInstance::getUID().
Referenced by samchon::library::FTFolder::FTFolder().
Member Data Documentation
int samchon::library::FTFactory::application protected
An application id.
An enumeration code of an application that managed FTInstance(s) are belonged to.
Definition at line 37 of file FTFactory.hpp.
int samchon::library::FTFactory::category protected
A categori id.
An enumeration code of a category that managed FTInstance(s) are belonged to.
Definition at line 44 of file FTFactory.hpp.
std::string samchon::library::FTFactory::member protected
Account id of a member.
Definition at line 51 of file FTFactory.hpp.
Map<int, FTInstance*> samchon::library::FTFactory::instanceMap protected
Map of files.
key: uid
value: pointer of file
Definition at line 60 of file FTFactory.hpp.
The documentation for this class was generated from the following files:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/library/FTFactory.hpp
D:/OneDrive/Project/Samchon/framework/cpp/samchon/library/FTFactory.cpp