Samchon Framework for CPP: samchon::library::URLVariables Class Reference
samchon::library::URLVariables Class Reference
URLVariables class is for representing variables of HTTP.
#include <URLVariables.hpp>
Public Member Functions
URLVariables ()
Default Constructor.
URLVariables (const WeakString &flashVars)
Constructor by a string representing encoded properties.
auto toString () const -> std::string
Get the string representing URLVariables.
Public Member Functions inherited from samchon::HashMap< std::string, std::string >
auto has (const std::string &key) const -> bool
Whether have the item or not.
auto get (const std::string &key) -> std::string &
Get element.
void set (const std::string &key, const std::string &val)
Set element.
auto pop (const std::string &key) -> std::string
Pop item.
Static Public Member Functions
static auto encode (const WeakString &wstr) -> std::string
Encode a string into a valid URI.
static auto decode (const WeakString &wstr) -> std::string
Decode a URI string.
Detailed Description
URLVariables class is for representing variables of HTTP.
URLVariables class allows you to transfer variables between an application and server. When transfering, URLVariables will be converted to a URI string.
URI: Uniform Resource Identifier
Use URLVariabels objects with methods of HTTPLoader class.
Example code
Author
Jeongho Nam http://samchon.org
Definition at line 28 of file URLVariables.hpp.
Constructor & Destructor Documentation
samchon::library::URLVariables::URLVariables () inline
Default Constructor.
Definition at line 41 of file URLVariables.hpp.
samchon::library::URLVariables::URLVariables (const WeakString & flashVars) inline
Constructor by a string representing encoded properties.
Converts the variable string to properties of the specified URLVariables object.
URLVariables("id=jhnam88&name=Jeongho+Nam") => {{\"id", "jhnam88"}, {"name", "Jeongho Nam http://samchon.org"}}
Parameters
A uri-encoded string containing pair of properties
Definition at line 53 of file URLVariables.hpp.
References decode(), samchon::WeakString::find(), samchon::WeakString::split(), and samchon::WeakString::substr().
Member Function Documentation
static auto samchon::library::URLVariables::encode (const WeakString & wstr) -> std::string inline static
Encode a string into a valid URI.
Encodes a string to follow URI standard format.
Parameters
A string to encode to URI
Returns
A string converted to URI
Definition at line 79 of file URLVariables.hpp.
Referenced by samchon::library::HTTPLoader::load(), and toString().
static auto samchon::library::URLVariables::decode (const WeakString & wstr) -> std::string inline static
Decode a URI string.
Decodes a URI string to its original
Parameters
A string encoded
Returns
A string decoded from URI
Definition at line 116 of file URLVariables.hpp.
Referenced by URLVariables().
auto samchon::library::URLVariables::toString () const -> std::string inline
Get the string representing URLVariables.
Returns a string object representing URLVariables following the URI
URLVariables({{"id", "jhnam88"}, {"name", "Jeongho Nam <http://samchon.org>"}}).toString() => "id=jhnam88&name=Jeongho+Nam"
Returns
A string representing URLVariables following the URI
Definition at line 177 of file URLVariables.hpp.
References encode().
The documentation for this class was generated from the following file:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/library/URLVariables.hpp