Samchon Framework for CPP: samchon::library::Math Class Reference
samchon::library::Math Class Reference
Utility of Math.
#include <Math.hpp>
Static Public Member Functions
static auto E () -> double
Exponent.
static auto PI () -> double
¥ð, Number Pi
static auto LN2 () -> double
loge2
static auto LN10 () -> double
loge10
static auto LOG2E () -> double
log2e
static auto LOG10E () -> double
log10e
static auto SQRT1_2 () -> double
Squart root of 0.5.
static auto SQRT2 () -> double
Squart root of 2.
static auto random () -> double
Get a random value.
static auto degree_to_radian (double val) -> double
Convert degree to radian.
static auto radian_to_degree (double val) -> double
Convert radian to degree.
template<typename _Cont , typename T = _Cont::value_type>
static auto minimum (const _Cont &container) -> IndexPair< T >
Calculate minimum value with its index.
template<typename _Cont , typename T = _Cont::value_type>
static auto maximum (const _Cont &container) -> IndexPair< T >
Calculate maximum value with its index.
template<typename _Cont , typename T = _Cont::value_type>
static auto mean (const _Cont &container) -> double
Calculate average.
template<typename _Cont , typename T = _Cont::value_type>
static auto median (const _Cont &container) -> double
Get median value.
template<typename _Cont , typename T = _Cont::value_type>
static auto mode (const _Cont &container) -> T
Find mode value.
template<typename _Cont , typename T = _Cont::value_type>
static auto stdev_p (const _Cont &container) -> double
Square root of a variance_p.
template<typename _Cont , typename T = _Cont::value_type>
static auto stdev_s (const _Cont &container) -> double
Square root of a variance_s.
template<typename _Cont , typename T = _Cont::value_type>
static auto variance_p (const _Cont &container) -> double
Calculate standard deviation for all population.
template<typename _Cont , typename T = _Cont::value_type>
static auto variance_s (const _Cont &container) -> double
Calculate variance for sample.
Detailed Description
Utility of Math.
Provides some static values and mathmatical methods.
See also
samchon::library
Author
Jeongho Nam http://samchon.org
Definition at line 24 of file Math.hpp.
Member Function Documentation
static auto samchon::library::Math::E () -> double inline static
Exponent.
A mathematical constant for the base of natural logarithms, expressed as e. The approximate value of e is 2.71828182845905.
Definition at line 37 of file Math.hpp.
Referenced by LN10(), LN2(), LOG10E(), and LOG2E().
static auto samchon::library::Math::PI () -> double inline static
¥ð, Number Pi
A mathematical constant for the ratio of the circumference of a circle to its diameter, expressed as pi, with a value of 3.141592653589793.
Definition at line 49 of file Math.hpp.
Referenced by degree_to_radian(), and radian_to_degree().
static auto samchon::library::Math::LN2 () -> double inline static
loge2
A mathematical constant for the natural logarithm of 2, expressed as loge2, with an approximate value of 0.6931471805599453.
Definition at line 61 of file Math.hpp.
References E().
static auto samchon::library::Math::LN10 () -> double inline static
loge10
A mathematical constant for the natural logarithm of 10, expressed as loge10, with an approximate value of 2.302585092994046.
Definition at line 73 of file Math.hpp.
References E().
static auto samchon::library::Math::LOG2E () -> double inline static
log2e
A mathematical constant for the base-2 logarithm of the constant e, expressed as log2e, with an approximate value of 1.442695040888963387.
Definition at line 85 of file Math.hpp.
References E().
static auto samchon::library::Math::LOG10E () -> double inline static
log10e
A mathematical constant for the base-10 logarithm of the constant e (Math.E), expressed as log10e, with an approximate value of 0.4342944819032518. The Math.log() method computes the natural logarithm of a number. Multiply the result of Math.log() by Math.LOG10E to obtain the base-10 logarithm.
Definition at line 99 of file Math.hpp.
References E().
static auto samchon::library::Math::SQRT1_2 () -> double inline static
Squart root of 0.5.
A mathematical constant for the square root of one-half, with an approximate value of 0.7071067811865476.
Definition at line 111 of file Math.hpp.
static auto samchon::library::Math::SQRT2 () -> double inline static
Squart root of 2.
A mathematical constant for the square root of 2, with an approximate value of 1.4142135623730951.
Definition at line 123 of file Math.hpp.
static auto samchon::library::Math::random () -> double inline static
Get a random value.
Returns a random value following uniform distribution
Returns
The random value
Definition at line 137 of file Math.hpp.
Referenced by samchon::library::GeneticAlgorithm< GeneArray, Compare >::crossover(), samchon::example::tsp::GeometryPoint::GeometryPoint(), samchon::library::GeneticAlgorithm< GeneArray, Compare >::mutate(), and samchon::library::GeneticAlgorithm< GeneArray, Compare >::selection().
static auto samchon::library::Math::degree_to_radian (double val) -> double inline static
Convert degree to radian.
Definition at line 151 of file Math.hpp.
References PI().
Referenced by samchon::example::tsp::GeometryPoint::calcDistance().
static auto samchon::library::Math::radian_to_degree (double val) -> double inline static
Convert radian to degree.
Definition at line 159 of file Math.hpp.
References PI().
Referenced by samchon::example::tsp::GeometryPoint::calcDistance().
template<typename _Cont , typename T = _Cont::value_type> static auto samchon::library::Math::minimum (const _Cont & container) -> IndexPair<T> inline static
Calculate minimum value with its index.
Template Parameters
_Cont Type of the container
_Ty
Value type of the container.
Do not modify the default template argument.
Parameters
container Container to find its minimum value
Returns
Pair of minimum value and its index
Definition at line 179 of file Math.hpp.
Referenced by samchon::WeakString::finds(), samchon::WeakString::rtrim(), and samchon::library::StringUtil::substituteSQL().
template<typename _Cont , typename T = _Cont::value_type> static auto samchon::library::Math::maximum (const _Cont & container) -> IndexPair<T> inline static
Calculate maximum value with its index.
Template Parameters
_Cont Type of the container
_Ty
Value type of the container.
Do not modify the default template argument.
Parameters
container Container to find its minimum value
Returns
Pair of maximum value and its index
Definition at line 210 of file Math.hpp.
Referenced by samchon::WeakString::rfinds(), and samchon::WeakString::rtrim().
template<typename _Cont , typename T = _Cont::value_type> static auto samchon::library::Math::mean (const _Cont & container) -> double inline static
Calculate average.
Template Parameters
_Cont Type of the container
_Ty
Value type of the container.
Do not modify the default template argument.
Parameters
container Container to find its mean
Returns
Average(mean) of the contaier
Definition at line 241 of file Math.hpp.
Referenced by variance_p(), and variance_s().
template<typename _Cont , typename T = _Cont::value_type> static auto samchon::library::Math::median (const _Cont & container) -> double inline static
Get median value.
Template Parameters
_Cont Type of the container
_Ty
Value type of the container.
Do not modify the default template argument.
Parameters
container Container to find its median
Returns
Median value of the container
Definition at line 262 of file Math.hpp.
template<typename _Cont , typename T = _Cont::value_type> static auto samchon::library::Math::mode (const _Cont & container) -> T inline static
Find mode value.
Template Parameters
_Cont Type of the container
_Ty
Value type of the container.
Do not modify the default template argument.
Parameters
container Container to find its mode
Returns
Most appeared value in the container
Definition at line 294 of file Math.hpp.
template<typename _Cont , typename T = _Cont::value_type> static auto samchon::library::Math::stdev_p (const _Cont & container) -> double inline static
Square root of a variance_p.
Template Parameters
_Cont Type of the container
_Ty
Value type of the container.
Do not modify the default template argument.
Parameters
container Container to find its standard deviation
Returns
Standard deviation of the container
Definition at line 318 of file Math.hpp.
References variance_p().
template<typename _Cont , typename T = _Cont::value_type> static auto samchon::library::Math::stdev_s (const _Cont & container) -> double inline static
Square root of a variance_s.
Template Parameters
_Cont Type of the container
_Ty
Value type of the container.
Do not modify the default template argument.
Parameters
container Container to find its variance
Returns
Variance of the container
Definition at line 329 of file Math.hpp.
References variance_s().
template<typename _Cont , typename T = _Cont::value_type> static auto samchon::library::Math::variance_p (const _Cont & container) -> double inline static
Calculate standard deviation for all population.
Template Parameters
_Cont Type of the container
_Ty
Value type of the container.
Do not modify the default template argument.
Parameters
container Container to find its standard deviation
Returns
Standard deviation of the container
Definition at line 346 of file Math.hpp.
References mean().
Referenced by stdev_p().
template<typename _Cont , typename T = _Cont::value_type> static auto samchon::library::Math::variance_s (const _Cont & container) -> double inline static
Calculate variance for sample.
Template Parameters
_Cont Type of the container
_Ty
Value type of the container.
Do not modify the default template argument.
Parameters
container Container to find its variance
Returns
Variance of the container
Definition at line 369 of file Math.hpp.
References mean().
Referenced by stdev_s().
The documentation for this class was generated from the following file:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/library/Math.hpp