Samchon Framework for CPP: samchon::example::tsp::Scheduler Class Reference
samchon::example::tsp::Scheduler Class Reference
A scheduler.
#include <Scheduler.hpp>
Public Member Functions
Scheduler ()
Default Constructor.
Scheduler (std::shared_ptr< Travel > travel, const struct GAParameters &gaParameteres)
Construct from points and parameter of genetic algorithm.
virtual void construct (std::shared_ptr< library::XML > xml) override
Construct data of the Entity from an XML object.
auto optimize () -> std::shared_ptr< Travel >
Derive optimized schedule.
virtual auto TAG () const -> std::string override
A tag name when represented by XML.
virtual auto toXML () const -> std::shared_ptr< library::XML > override
Get an XML object represents the Entity.
Public Member Functions inherited from samchon::protocol::Entity
Entity ()
Default Constructor.
virtual auto key () const -> std::string
Get a key that can identify the Entity uniquely.
Protected Attributes
std::shared_ptr< Travel > travel
A travel to optimize or optimized.
struct GAParameters gaParameters
Parameters for Genetic-Algorithm.
Detailed Description
A scheduler.
Scheduler deducts an optimal schdule(Travel) by genetic algorithm.
Author
Jeongho Nam
Definition at line 41 of file Scheduler.hpp.
Constructor & Destructor Documentation
samchon::example::tsp::Scheduler::Scheduler () inline
Default Constructor.
Definition at line 65 of file Scheduler.hpp.
References gaParameters.
samchon::example::tsp::Scheduler::Scheduler (std::shared_ptr< Travel > travel, const struct GAParameters & gaParameteres) inline
Construct from points and parameter of genetic algorithm.
Definition at line 75 of file Scheduler.hpp.
References gaParameters, and travel.
Member Function Documentation
virtual void samchon::example::tsp::Scheduler::construct (std::shared_ptr< library::XML >) inline override virtual
Construct data of the Entity from an XML object.
Overrides the construct() method and fetch data of member variables from the XML.
By recommended guidance, data representing member variables are contained in properties of the put XML object.
Parameters
xml An xml used to construct data of entity
Implements samchon::protocol::Entity.
Definition at line 84 of file Scheduler.hpp.
References samchon::protocol::Entity::construct(), and gaParameters.
Referenced by samchon::example::interaction::TSPSlave::optimize(), and samchon::example::interaction::Reporter::printTSP().
auto samchon::example::tsp::Scheduler::optimize () -> std::shared_ptr<Travel> inline
Derive optimized schedule.
Returns
An optimized travel schedule.
Definition at line 103 of file Scheduler.hpp.
References samchon::library::GeneticAlgorithm< GeneArray, Compare >::evolveGeneArray(), gaParameters, and travel.
Referenced by samchon::example::interaction::TSPSlave::optimize().
virtual auto samchon::example::tsp::Scheduler::TAG () const -> std::string inline override virtual
A tag name when represented by XML.
Returns
A tag name
Implements samchon::protocol::Entity.
Definition at line 131 of file Scheduler.hpp.
virtual auto samchon::example::tsp::Scheduler::toXML () const -> std::shared_ptr<library::XML> inline override virtual
Get an XML object represents the Entity.
Returns an XML object that can represents the Entity containing member variables into properties.
A member variable (not object, but atomic value like number, string or date) is categorized as a property within the framework of entity side. Thus, when overriding a toXML() method and archiving member variables to an XML object to return, puts each variable to be a property belongs to only an XML object.
Don't archive the member variable of atomic value to XML::value causing enormouse creation of XML objects to number of member variables. An Entity must be represented by only an XML instance (tag).
Standard Usage Non-standard usage abusing value
<memberList>
<member id='jhnam88' name='Jeongho+Nam' birthdate='1988-03-11' />
<member id='master' name='Administartor' birthdate='2011-07-28' />
</memberList> <member>
<id>jhnam88</id>
<name>Jeongho+Nam</name>
<birthdate>1988-03-11</birthdate>
</member>
Returns
An XML object representing the Entity.
Reimplemented from samchon::protocol::Entity.
Definition at line 136 of file Scheduler.hpp.
References gaParameters, and samchon::protocol::Entity::toXML().
Referenced by samchon::example::interaction::Chief::callTSP(), and samchon::example::interaction::TSPSlave::optimize().
Member Data Documentation
std::shared_ptr<Travel> samchon::example::tsp::Scheduler::travel protected
A travel to optimize or optimized.
Definition at line 51 of file Scheduler.hpp.
Referenced by optimize(), and Scheduler().
struct GAParameters samchon::example::tsp::Scheduler::gaParameters protected
Parameters for Genetic-Algorithm.
Definition at line 56 of file Scheduler.hpp.
Referenced by construct(), optimize(), Scheduler(), and toXML().
The documentation for this class was generated from the following file:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/example/tsp/Scheduler.hpp