Samchon Framework for CPP: samchon::protocol::master::ParallelSystemArray Class Reference
samchon::protocol::master::ParallelSystemArray Class Reference
An array of parallel system drivers.
#include <ParallelSystemArray.hpp>
Public Member Functions
ParallelSystemArray ()
Default Constructor.
void sendSegmentData (std::shared_ptr< Invoke >, size_t)
Send a message with segmentation size.
virtual void sendPieceData (std::shared_ptr< Invoke >, size_t, size_t)
Send a message with piece index and size.
Public Member Functions inherited from samchon::protocol::ExternalSystemArray
ExternalSystemArray ()
Default Constructor.
virtual void start ()=0
Start interaction.
auto hasRole (const std::string &) const -> bool
Test whether has a role.
auto getRole (const std::string &) const -> std::shared_ptr< ExternalSystemRole >
Get a role.
virtual void sendData (std::shared_ptr< Invoke >) override
Sends an Invoke message to related ExternalSystem(s).
virtual void replyData (std::shared_ptr< Invoke >) override
Handle replied Invoke message.
virtual auto TAG () const -> std::string override
A tag name when represented by XML.
virtual auto CHILD_TAG () const -> std::string override
A tag name of children.
Public Member Functions inherited from samchon::protocol::EntityGroup< _Container, _ETy, T >
EntityGroup ()
Default Constructor.
virtual void construct (std::shared_ptr< library::XML > xml)
Construct data of the Entity from an XML object.
auto has (const std::string &key) const -> bool
Indicates whether a container has an object having the specified identifier.
auto get (const std::string &key) -> value_type &
Access the element by specified identifier(key).
auto get (const std::string &key) const -> const value_type &
Access the const element by specified identifier(key).
virtual auto toXML () const -> std::shared_ptr< library::XML >
Get an XML object represents the EntityGroup.
Public Member Functions inherited from samchon::protocol::Entity
Entity ()
Default Constructor.
virtual auto key () const -> std::string
Get a key that can identify the Entity uniquely.
Public Member Functions inherited from samchon::protocol::IEntityGroup
IEntityGroup ()
Default Constructor.
Public Member Functions inherited from samchon::protocol::IProtocol
IProtocol ()
Default Constructor.
Protected Member Functions
virtual void notifyEnd (PRMasterHistory *)
Notify end of a master history.
Protected Member Functions inherited from samchon::protocol::EntityGroup< _Container, _ETy, T >
virtual auto createChild (std::shared_ptr< library::XML >) -> entity_type *=0
Factory method of a child Entity.
Private Attributes
std::atomic< size_t > uid
Sequence of uid allocating for history.
PRMasterHistoryArray * historyArray
An array of history have occured.
PRMasterHistoryArray * progressArray
An array of history on progress.
Detailed Description
An array of parallel system drivers.
ParallelSystemArray is an ExternalSystemArray and an abstract class containing. and managing parallel system drvers within framework of master. The ParallelSystemArray class allocates segmented processes (Invoke message containing segmentation size) following by each system's performance index.
Unlike DistributedSystemArray, ParallelSystemArray does not have such complicate relationships and logics. All segmentation sent by sendData(Invoke, size_t) requires uniform performance. ParallelSystemArray just calculates each system's performance index by elapsing time such easily.
Of course, DistributedSystemArray determines which size of segmentation allocation will be suitable for each system by the performance index
.
Each segmentation in requested process (Invoke message) is equivalent. Thus, role of ParallelSystem objects in a ParallelSystemArray are almost same and does not need to specify ExternalSystemRole on each ParallelSystem.
Not a matter to specifying ExternalSystemRole objects to each ParallelSystem. In that case, Invoke messages having segmentation size will be processed by ParallelSystemArray's own logic and Invoke messages without segmentation size will be handled by ordinary logic of ExternalSystemArray's own.
[Inherited]
ExternalSystemArray is an abstract class containing and managing external system drivers.
Also, ExternalSystemArray can access to ExternalSystemRole(s) directly. With the method, you can use an ExternalSystemRole as "logical proxy" of an ExternalSystem. Of course, the ExternalSystemRole is belonged to an ExternalSystem. However, if you access an ExternalSystemRole from an ExternalSystemArray directly, not passing by a belonged ExternalSystem, and send an Invoke message even you're not knowing which ExternalSystem is related in, the ExternalSystemRole acted a role of proxy.
It's called as "Proxy pattern". With the pattern, you can only concentrate on ExternalSystemRole itself, what to do with Invoke message, irrespective of the ExternalSystemRole is belonged to which ExternalSystem.
ExternalSystemArray::getRole("something")->sendData(invoke);
Example Sources
example::interaction
See also
samchon::protocol
Author
Jeongho Nam http://samchon.org
Definition at line 50 of file ParallelSystemArray.hpp.
Constructor & Destructor Documentation
ParallelSystemArray::ParallelSystemArray ()
Default Constructor.
Definition at line 18 of file ParallelSystemArray.cpp.
Member Function Documentation
void ParallelSystemArray::sendSegmentData (std::shared_ptr< Invoke > , size_t)
Send a message with segmentation size.
Parameters
invoke An invoke message requesting a process.
size Size of segmentation.
Definition at line 37 of file ParallelSystemArray.cpp.
void ParallelSystemArray::sendPieceData (std::shared_ptr< Invoke > , size_t , size_t) virtual
Send a message with piece index and size.
Parameters
invoke An invoke message requesting a process.
index Starting index number of segmentation.
size Size of segmentation.
Definition at line 42 of file ParallelSystemArray.cpp.
Referenced by samchon::example::interaction::PackerMediator::addClient(), and samchon::protocol::master::ParallelSlaveSystemMediator::replyPieceData().
void ParallelSystemArray::notifyEnd (PRMasterHistory * masterHistory) protected virtual
Notify end of a master history.
Estimates performance of each system by a master history containing their elapsed times.
The estimation is done by normalizing performances of children systems. The estimation of performance is divided by averagae elapsed time of each segmentation.
Reimplemented in samchon::protocol::master::ParallelSystemArrayMediator.
Definition at line 80 of file ParallelSystemArray.cpp.
References samchon::protocol::master::PRInvokeHistory::calcAverageElapsedTime(), samchon::protocol::master::PRMasterHistory::historyArray, samchon::protocol::master::ParallelSystem::performance, and samchon::protocol::master::PRInvokeHistory::system.
Referenced by samchon::protocol::master::ParallelSystemArrayMediator::notifyEnd().
Member Data Documentation
std::atomic<size_t> samchon::protocol::master::ParallelSystemArray::uid private
Sequence of uid allocating for history.
Definition at line 62 of file ParallelSystemArray.hpp.
PRMasterHistoryArray* samchon::protocol::master::ParallelSystemArray::historyArray private
An array of history have occured.
Definition at line 67 of file ParallelSystemArray.hpp.
PRMasterHistoryArray* samchon::protocol::master::ParallelSystemArray::progressArray private
An array of history on progress.
Definition at line 72 of file ParallelSystemArray.hpp.
The documentation for this class was generated from the following files:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/protocol/master/ParallelSystemArray.hpp
D:/OneDrive/Project/Samchon/framework/cpp/samchon/protocol/master/ParallelSystemArray.cpp