Samchon Framework for CPP: samchon::library::SharedReadLock Class Reference
samchon::library::SharedReadLock Class Reference
Shared lock from a RWMutex.
#include <SharedReadLock.hpp>
Public Member Functions
SharedReadLock (const RWMutex &rw_mutex, bool lock=true)
Construct from RWMutex.
SharedReadLock (const SharedReadLock &obj)
Copy Constructor.
SharedReadLock (SharedReadLock &&obj)
Move Constructor.
~SharedReadLock ()
Default Destructor.
void lock () const
Lock on read.
void unlock () const
Unlock of read.
Private Attributes
const RWMutex * rw_mutex
Managed RWMutex.
std::atomic< size_t > * reference
Referencing count sharing same RWMutex.
std::atomic< bool > * locked
Whether the mutex was locked by SharedReadLock.
Detailed Description
Shared lock from a RWMutex.
A SharedReadLock is an object manages a RWMutex with shared ownership in both states.
locked
unlocked
On default construction, the object acquires a RWMutex object, for whose locking and unlocking operations becomes responsible. When copy constructions, responsibilities of locking and unlocking RWMutex are shared with copied with those SharedReadLock objects.
The class shared_lock is a general-purpose shared mutex ownership wrapper allowing deferred locking, timed locking and transfer of lock ownership. Locking a shared_lock locks the associated shared mutex in shared mode (to lock it in exclusive mode, std::unique_lock can be used)
This class guarantees a unlocked status on destruction of all shared objects (even if not called explicitly). Therefore it is especially useful as an object with automatic duration, as it guarantees the RWMutex object is properly unlocked in case an exception is thrown.
Referenced comments of std::unique_lock
http://www.cplusplus.com/reference/mutex/unique_lock/
Note
Though, that the SharedReadLock object does not manage the lifetime of the RWMutex object in any way: the duration of the RWMutex object shall extend at least until the destruction of the SharedReadLock that manages it.
See also
library::UniqueAcquire
samchon::library
Author
Jeongho Nam http://samchon.org
Definition at line 45 of file SharedReadLock.hpp.
Constructor & Destructor Documentation
samchon::library::SharedReadLock::SharedReadLock (const RWMutex & rw_mutex, bool lock = true) inline
Construct from RWMutex.
Parameters
rw_mutex RWMutex to manage
lock Whether to lock directly or not
Definition at line 73 of file SharedReadLock.hpp.
References lock(), samchon::library::RWMutex::readLock(), and rw_mutex.
samchon::library::SharedReadLock::SharedReadLock (const SharedReadLock & obj) inline
Copy Constructor.
Definition at line 86 of file SharedReadLock.hpp.
References locked, reference, and rw_mutex.
samchon::library::SharedReadLock::SharedReadLock (SharedReadLock && obj) inline
Move Constructor.
Definition at line 98 of file SharedReadLock.hpp.
samchon::library::SharedReadLock::~SharedReadLock () inline
Default Destructor.
Definition at line 114 of file SharedReadLock.hpp.
References locked, samchon::library::RWMutex::readUnlock(), and reference.
Member Function Documentation
void samchon::library::SharedReadLock::lock () const inline
Lock on read.
Increases a reading count.
When write_lock is on a progress, wait until write_unlock to be called.
Reading can be done by multiple sections.
Reading can't be done when writing.
Warning
You've to call read_unlock when the reading work is terminated.
Definition at line 132 of file SharedReadLock.hpp.
References samchon::library::RWMutex::readLock().
Referenced by SharedReadLock().
void samchon::library::SharedReadLock::unlock () const inline
Unlock of read.
Decreases a reading count.
When write_lock had done after read_lock, it continues by read_unlock if the reading count was 1 (read_unlock makes the count to be zero).
Definition at line 144 of file SharedReadLock.hpp.
References samchon::library::RWMutex::readUnlock().
Member Data Documentation
const RWMutex* samchon::library::SharedReadLock::rw_mutex private
Managed RWMutex.
Definition at line 51 of file SharedReadLock.hpp.
Referenced by SharedReadLock().
std::atomic<size_t>* samchon::library::SharedReadLock::reference private
Referencing count sharing same RWMutex.
Definition at line 56 of file SharedReadLock.hpp.
Referenced by SharedReadLock(), and ~SharedReadLock().
std::atomic<bool>* samchon::library::SharedReadLock::locked private
Whether the mutex was locked by SharedReadLock.
Definition at line 61 of file SharedReadLock.hpp.
Referenced by SharedReadLock(), and ~SharedReadLock().
The documentation for this class was generated from the following file:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/library/SharedReadLock.hpp