Samchon Framework for CPP: samchon::library::SharedWriteLock Class Reference
samchon::library::SharedWriteLock Class Reference
Shared lock from a RWMutex.
#include <SharedWriteLock.hpp>
Public Member Functions
SharedWriteLock (RWMutex &rw_mutex, bool lock=true)
Construct from RWMutex.
SharedWriteLock (const SharedWriteLock &obj)
Copy Constructor.
SharedWriteLock (SharedWriteLock &&obj)
Move Constructor.
~SharedWriteLock ()
Default Destructor.
void lock ()
Lock on writing.
void unlock ()
Unlock on writing.
Private Attributes
RWMutex * rw_mutex
Managed RWMutex.
std::atomic< size_t > * reference
Referencing count sharing same RWMutex.
std::atomic< bool > * locked
Whether the mutex was locked by SharedWriteLock.
Detailed Description
Shared lock from a RWMutex.
A SharedWriteLock is an object manages a RWMutex with shared ownership in both states.
locked
unlocked
On default construction, the object acquires a RWMutex object, for whose locking and unlocking operations becomes responsible. When copy constructions, responsibilities of locking and unlocking RWMutex are shared with copied with those SharedWriteLock objects.
The class shared_lock is a general-purpose shared mutex ownership wrapper allowing deferred locking, timed locking and transfer of lock ownership. Locking a shared_lock locks the associated shared mutex in shared mode (to lock it in exclusive mode, std::unique_lock can be used)
This class guarantees a unlocked status on destruction of all shared objects (even if not called explicitly). Therefore it is especially useful as an object with automatic duration, as it guarantees the RWMutex object is properly unlocked in case an exception is thrown.
Referenced comments of std::unique_lock
http://www.cplusplus.com/reference/mutex/unique_lock/
Note
Though, that the SharedWriteLock object does not manage the lifetime of the RWMutex object in any way: the duration of the RWMutex object shall extend at least until the destruction of the SharedWriteLock that manages it.
Library - Critical Section
Author
Jeongho Nam http://samchon.org
Definition at line 43 of file SharedWriteLock.hpp.
Constructor & Destructor Documentation
samchon::library::SharedWriteLock::SharedWriteLock (RWMutex & rw_mutex, bool lock = true) inline
Construct from RWMutex.
Parameters
rw_mutex RWMutex to manage
lock Whether to lock directly or not
Definition at line 71 of file SharedWriteLock.hpp.
References lock(), and rw_mutex.
samchon::library::SharedWriteLock::SharedWriteLock (const SharedWriteLock & obj) inline
Copy Constructor.
Definition at line 84 of file SharedWriteLock.hpp.
References locked, reference, and rw_mutex.
samchon::library::SharedWriteLock::SharedWriteLock (SharedWriteLock && obj) inline
Move Constructor.
Definition at line 96 of file SharedWriteLock.hpp.
samchon::library::SharedWriteLock::~SharedWriteLock () inline
Default Destructor.
Definition at line 112 of file SharedWriteLock.hpp.
References locked, reference, and samchon::library::RWMutex::writeUnlock().
Member Function Documentation
void samchon::library::SharedWriteLock::lock () inline
Lock on writing.
Changes writing flag to true.
If another write_lock or read_lock is on a progress, wait until them to be unlocked.
Writing can be done by only a section at once.
Writing can't be done when reading.
Note
You've to call write_unlock when writing work was terminated.
Definition at line 130 of file SharedWriteLock.hpp.
References samchon::library::RWMutex::writeLock().
Referenced by SharedWriteLock().
void samchon::library::SharedWriteLock::unlock () inline
Unlock on writing.
Definition at line 142 of file SharedWriteLock.hpp.
References samchon::library::RWMutex::writeUnlock().
Member Data Documentation
RWMutex* samchon::library::SharedWriteLock::rw_mutex private
Managed RWMutex.
Definition at line 49 of file SharedWriteLock.hpp.
Referenced by SharedWriteLock().
std::atomic<size_t>* samchon::library::SharedWriteLock::reference private
Referencing count sharing same RWMutex.
Definition at line 54 of file SharedWriteLock.hpp.
Referenced by SharedWriteLock(), and ~SharedWriteLock().
std::atomic<bool>* samchon::library::SharedWriteLock::locked private
Whether the mutex was locked by SharedWriteLock.
Definition at line 59 of file SharedWriteLock.hpp.
Referenced by SharedWriteLock(), and ~SharedWriteLock().
The documentation for this class was generated from the following file:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/library/SharedWriteLock.hpp