Samchon Framework for CPP: samchon::protocol::EntityGroup< _Container, _ETy, _Ty > Class Template Reference
samchon::protocol::EntityGroup< _Container, _ETy, _Ty > Class Template Reference abstract
An Entity and a container of children Entity objects.
#include <EntityGroup.hpp>
Public Member Functions
EntityGroup ()
Default Constructor.
virtual void construct (std::shared_ptr< library::XML > xml)
Construct data of the Entity from an XML object.
auto has (const std::string &key) const -> bool
Indicates whether a container has an object having the specified identifier.
auto get (const std::string &key) -> value_type &
Access the element by specified identifier(key).
auto get (const std::string &key) const -> const value_type &
Access the const element by specified identifier(key).
virtual auto toXML () const -> std::shared_ptr< library::XML >
Get an XML object represents the EntityGroup.
Public Member Functions inherited from samchon::protocol::Entity
virtual auto TAG () const -> std::string=0
A tag name when represented by XML.
Entity ()
Default Constructor.
virtual auto key () const -> std::string
Get a key that can identify the Entity uniquely.
Public Member Functions inherited from samchon::protocol::IEntityGroup
IEntityGroup ()
Default Constructor.
Protected Member Functions
virtual auto createChild (std::shared_ptr< library::XML >) -> entity_type *=0
Factory method of a child Entity.
Protected Member Functions inherited from samchon::protocol::IEntityGroup
virtual auto CHILD_TAG () const -> std::string=0
A tag name of children.
Detailed Description
template<typename _Container, typename _ETy = Entity, typename _Ty = _Container::value_type>
class samchon::protocol::EntityGroup< _Container, _ETy, _Ty >
An Entity and a container of children Entity objects.
Template Parameters
_Container A type of container containing children entity objects.
_Ety A type of children entity. It must be a class derived from an Entity class, or Entity class itself.
_Ty A type of children element of _Container. Using default template parameter is recommended.
EntityGroup is a template class for containinig children Entity objects, and also another type of an Entity, too. You can realize hierarchical relationship. Although some entities have complicated hierarchical relationship, you can deduct a optimal solution easily with EntityGroup and Entity.
If an entity has some subordinate entities of same type, they are in "Composite relationship". Make the entity to be EmntityGroup and subordinate entities to be children of the entity. When those relationships are continued, continue to create classes dervied from EntityGroup. When those relationshiop meets a terminal node, then make the terminal node to be an Entity.
EntityGroup is an Entity, and a container of children Entity objects at the same time. If children type, of a class derived from an EntityGroup, is itself, you can realize hierarchical and recursive relationship. The relationship is called as "Composite pattern".
FTFolder extends FTInstance and SharedEntityArray<FTInstance>
NTCriteria extends SharedEntityArray<NTCriteria>
Note
As a freelancer developer and architect I am, I even design DB I/O to follow the format representing Entity and EntityGroup by XML. Below T-SQL script also follows the standard format of expressing Entity with XML by procedure and "FOR XML AUTO" statement.
 SET
   ANSI_NULLS,
   QUOTED_IDENTIFIER,
   CONCAT_NULL_YIELDS_NULL,
   ANSI_WARNINGS,
   ANSI_PADDING
 ON;
 USE OraQ;
 IF OBJECT_ID('v_studyStatus') IS NOT NULL          DROP VIEW v_studyStatus;
 IF OBJECT_ID('v_nonDicomFileStatus') IS NOT NULL   DROP VIEW v_nonDicomFileStatus;
 IF OBJECT_ID('v_candidateStudy') IS NOT NULL       DROP VIEW v_candidateStudy;
 IF OBJECT_ID('v_candidateFile') IS NOT NULL            DROP VIEW v_candidateFile;
 IF OBJECT_ID('goCandidateInspectList') IS NOT NULL DROP PROCEDURE goCandidateInspectList;
 GO
 CREATE VIEW v_studyStatus
 AS
    WITH cte AS
    (
        SELECT S.studyUID uid, S.type type, ROW_NUMBER() OVER (PARTITION BY S.studyUID ORDER BY H.datetime DESC) no
        FROM History.history H, History.study S
        WHERE
            H.uid = S.uid AND type <> 1
    )
    SELECT
        A.uid,
        CASE WHEN B.type IS NULL THEN
            A.type
            ELSE 1
        END status
    FROM
    (
        SELECT uid, type
        FROM cte
        WHERE no = 1
    ) A LEFT OUTER JOIN
    (
        SELECT studyUID uid, 1 type
        FROM History.study
        GROUP BY studyUID
        HAVING MAX(type) = 1
    ) B ON A.uid = B.uid
 GO
 CREATE VIEW v_nonDicomFileStatus
 AS
    WITH cte AS
    (
        SELECT
            F.fileUID uid, F.type type,
            ROW_NUMBER() OVER (PARTITION BY F.fileUID ORDER BY H.datetime DESC) no
        FROM History.history H, History.nonDicomFile F
        WHERE
            H.uid = F.uid AND type <> 1
    )
    SELECT
        A.uid,
        CASE WHEN B.type IS NULL THEN
            A.type
            ELSE 1
        END status
    FROM
    (
        SELECT uid, type
        FROM cte
        WHERE no = 1
    ) A LEFT OUTER JOIN
    (
        SELECT fileUID uid, 1 type
        FROM History.nonDicomFile
        GROUP BY fileUID
        HAVING MAX(type) = 1
    ) B ON A.uid = B.uid
 GO
 CREATE VIEW v_candidateStudy
 AS
    SELECT DISTINCT
        P.id patientID,
            P.name patientName, P.gender patientGender,
            CAST(P.birthdate AS DATE) patientBirthdate,
        S.uid,
            S.description,
            CONVERT(VARCHAR, CAST(S.datetime AS DATETIME), 120) AS datetime,
            H.status
    FROM
        Hospital.patient P, Inspect.media M, Inspect.mediaStudyPair A,
        Inspect.study S, v_studyStatus H
    WHERE
        P.id = M.patientID AND M.uid = A.mediaUID AND A.studyUID = S.uid AND
        S.uid = H.uid
 GO
 CREATE VIEW v_candidateFile
 AS
    SELECT DISTINCT
        P.id patientID,
            P.name patientName, P.gender patientGender,
            CAST(P.birthdate AS DATE) patientBirthdate,
        M.uid mediaUID,
            F.uid, F.name, F.extension,
            CONVERT(VARCHAR, CAST(F.datetime AS DATETIME), 120) AS datetime,
            H.status
    FROM
        Hospital.patient P, Inspect.media M,
        Inspect.nonDicomFile F, v_nonDicomFileStatus H
    WHERE
        P.id = M.patientID AND M.uid = F.mediaUID AND F.uid = H.uid
 GO
 CREATE PROCEDURE goCandidateInspectList
 AS
    DECLARE @xml XML =
    (
        SELECT *
        FROM
        (
            SELECT N'candidate' service
        ) inspect
        FOR XML AUTO
    )
    DECLARE @studyList XML =
    (
        SELECT study.*, series.*, image.*
        FROM
            v_candidateStudy study
                LEFT OUTER JOIN Inspect.series series
                    ON study.uid = series.studyUID
                LEFT OUTER JOIN Inspect.image image
                    ON series.uid = image.seriesUID
        FOR XML AUTO, ROOT(N'studyList')
    )
    DECLARE @fileList XML =
    (
        SELECT * FROM v_candidateFile
        FOR XML RAW(N'file'), ROOT(N'fileList')
    )
    IF(@studyList IS NOT NULL)  SET @xml.modify('insert sql:variable("@studyList") into (/inspect)[1]')
    IF(@fileList IS NOT NULL)   SET @xml.modify('insert sql:variable("@fileList") into (/inspect)[1]')
    SELECT @xml;
 GO
Warning
EntityGroup contains children entity elements as type of pointer. Because children entity objects are not serialized and referenced by pointer, its iteration and accessment is not fast. If it needs higher performance, then use EntityArray (static array for children entity) instead.
[Inherited]
Entity is a class for standardization of expression method using on network I/O by XML. If Invoke is a standard message protocol of Samchon Framework which must be kept, Entity is a recommended semi-protocol of message for expressing a data class. Following the semi-protocol Entity is not imposed but encouraged.
As we could get advantages from standardization of message for network I/O with Invoke, we can get additional advantage from standardizing expression method of data class with Entity. We do not need to know a part of network communication. Thus, with the Entity, we can only concentrate on entity's own logics and relationships between another entities. Entity does not need to how network communications are being done.
Example Sources
example::entity
example::packer
example::tsp
Note
I say repeatedly. Expression method of Entity is recommended, but not imposed. It's a semi protocol for network I/O but not a essential protocol must be kept. The expression method of Entity, using on network I/O, is expressed by XML string.
If your own network system has a critical performance issue on communication data class, it would be better to using binary communication (with ByteArray or boost::serialization). Don't worry about the problem! Invoke also provides methods for binary data (ByteArray).
See also
protocol
Author
Jeongho Nam
Definition at line 54 of file EntityGroup.hpp.
Constructor & Destructor Documentation
template<typename _Container, typename _ETy = Entity, typename _Ty = _Container::value_type> samchon::protocol::EntityGroup< _Container, _ETy, _Ty >::EntityGroup () inline
Default Constructor.
Definition at line 71 of file EntityGroup.hpp.
Member Function Documentation
template<typename _Container, typename _ETy = Entity, typename _Ty = _Container::value_type> virtual void samchon::protocol::EntityGroup< _Container, _ETy, _Ty >::construct (std::shared_ptr< library::XML > xml) inline virtual
Construct data of the Entity from an XML object.
Constructs the EntityGroup's own member variables only from the input XML object.
Do not consider about constructing children Entity objects' data in EntityGroup::construct(). Those children Entity objects' data will constructed by their own construct() method. Even insertion of XML objects representing children are done by abstract method of EntityGroup::toXML().
Constructs only data of EntityGroup's own.
[Inherited]
Construct data of the Entity from an XML object.
Overrides the construct() method and fetch data of member variables from the XML.
By recommended guidance, data representing member variables are contained in properties of the put XML object.
Parameters
xml An xml used to construct data of entity
Implements samchon::protocol::Entity.
Reimplemented in samchon::protocol::master::DistributedSystem, samchon::namtree::NTCriteria, samchon::protocol::master::ParallelSystem, samchon::example::packer::WrapperArray, samchon::example::packer::Packer, samchon::protocol::ExternalSystem, samchon::protocol::Invoke, samchon::example::tsp::Travel, samchon::example::packer::Wrapper, samchon::protocol::master::DistributedSystemArray, samchon::protocol::master::ParallelSystemArrayMediator, samchon::protocol::master::DistributedSystemArrayMediator, samchon::namtree::NTParameter, samchon::protocol::ExternalClientArray, samchon::protocol::ExternalServer, samchon::protocol::master::DistributedClientArrayMediator, samchon::protocol::master::ParallelClientArrayMediator, samchon::protocol::master::DistributedClientArray, samchon::protocol::master::DistributedServer, and samchon::protocol::master::ParallelServer.
Definition at line 92 of file EntityGroup.hpp.
Referenced by samchon::protocol::ExternalClientArray::construct(), samchon::namtree::NTParameter::construct(), samchon::protocol::master::ParallelSystemArrayMediator::construct(), samchon::example::packer::Wrapper::construct(), samchon::example::tsp::Travel::construct(), samchon::protocol::Invoke::construct(), samchon::protocol::ExternalSystem::construct(), samchon::example::packer::Packer::construct(), samchon::example::packer::WrapperArray::construct(), samchon::protocol::master::ParallelSystem::construct(), samchon::namtree::NTFile::construct(), and samchon::namtree::NTCriteria::construct().
template<typename _Container, typename _ETy = Entity, typename _Ty = _Container::value_type> virtual auto samchon::protocol::EntityGroup< _Container, _ETy, _Ty >::createChild (std::shared_ptr< library::XML >) -> entity_type * protected pure virtual
Factory method of a child Entity.
EntityGroup::createChild() is a factory method creating a new child Entity which is belonged to the EntityGroup. This method is called by EntityGroup::construct(). The children construction methods Entity::construct() will be called by abstract method of the EntityGroup::construct().
Returns
A new child Entity belongs to EntityGroup.
Implemented in samchon::namtree::NTCriteria, samchon::example::interaction::Master, samchon::example::packer::WrapperArray, samchon::protocol::master::ParallelSystem, samchon::example::packer::Packer, samchon::example::interaction::Chief, samchon::example::interaction::PackerMediator, samchon::example::tsp::Travel, samchon::protocol::Invoke, samchon::example::interaction::MasterDriver, samchon::namtree::NTParameter, samchon::namtree::NTParameterArray, samchon::protocol::slave::ParallelSystem, samchon::protocol::master::DSInvokeHistoryList, samchon::protocol::master::PRInvokeHistoryArray, samchon::example::packer::ProductArray, and samchon::protocol::InvokeHistoryArray.
Referenced by samchon::protocol::ExternalClientArray::addClient(), and samchon::protocol::EntityGroup< _Container, Entity * >::construct().
template<typename _Container, typename _ETy = Entity, typename _Ty = _Container::value_type> auto samchon::protocol::EntityGroup< _Container, _ETy, _Ty >::has (const std::string & key) const -> bool inline
Indicates whether a container has an object having the specified identifier.
Parameters
key An identifier of an Entity
Returns
If there's the object then true, otherwise false
Definition at line 157 of file EntityGroup.hpp.
Referenced by samchon::protocol::ExternalSystemArray::sendData().
template<typename _Container, typename _ETy = Entity, typename _Ty = _Container::value_type> auto samchon::protocol::EntityGroup< _Container, _ETy, _Ty >::get (const std::string & key) -> value_type& inline
Access the element by specified identifier(key).
Parameters
key the identifier of the element wants to access
Returns
The element having the key, or throw exception if there is none.
Definition at line 172 of file EntityGroup.hpp.
Referenced by samchon::protocol::master::PRMasterHistory::PRMasterHistory().
template<typename _Container, typename _ETy = Entity, typename _Ty = _Container::value_type> auto samchon::protocol::EntityGroup< _Container, _ETy, _Ty >::get (const std::string & key) const -> const value_type& inline
Access the const element by specified identifier(key).
Parameters
key the identifier of the element wants to access
Returns
The const element having the key, or throw exception if there is none.
Definition at line 187 of file EntityGroup.hpp.
template<typename _Container, typename _ETy = Entity, typename _Ty = _Container::value_type> virtual auto samchon::protocol::EntityGroup< _Container, _ETy, _Ty >::toXML () const -> std::shared_ptr<library::XML> inline virtual
Get an XML object represents the EntityGroup.
Archives the EntityGroup's own member variables only to the returned XML object.
Do not consider about archiving children Entity objects' data in EntityGroup::toXML(). Those children Entity objects will converted to XML object by their own toXML() method. The insertion of XML objects representing children are done by abstract method of EntityGroup::toXML().
Archives only data of EntityGroup's own.
[Inherited]
Get an XML object represents the Entity.
Returns an XML object that can represents the Entity containing member variables into properties.
A member variable (not object, but atomic value like number, string or date) is categorized as a property within the framework of entity side. Thus, when overriding a toXML() method and archiving member variables to an XML object to return, puts each variable to be a property belongs to only an XML object.
Don't archive the member variable of atomic value to XML::value causing enormouse creation of XML objects to number of member variables. An Entity must be represented by only an XML instance (tag).
Standard Usage Non-standard usage abusing value
<memberList>
<member id='jhnam88' name='Jeongho+Nam' birthdate='1988-03-11' />
<member id='master' name='Administartor' birthdate='2011-07-28' />
</memberList> <member>
<id>jhnam88</id>
<name>Jeongho+Nam</name>
<birthdate>1988-03-11</birthdate>
</member>
Returns
An XML object representing the Entity.
Reimplemented from samchon::protocol::Entity.
Reimplemented in samchon::example::packer::WrapperArray, samchon::example::packer::Packer, samchon::protocol::Invoke, samchon::example::tsp::Travel, samchon::protocol::master::DistributedSystem, samchon::namtree::NTCriteria, samchon::protocol::ExternalSystem, samchon::example::packer::Wrapper, samchon::protocol::master::ParallelSystem, samchon::protocol::master::DistributedSystemArray, samchon::namtree::NTParameter, samchon::protocol::master::ParallelSystemArrayMediator, samchon::protocol::master::DistributedSystemArrayMediator, samchon::protocol::ExternalClientArray, samchon::protocol::ExternalServer, samchon::library::FTFolder, samchon::protocol::master::DistributedClientArrayMediator, samchon::protocol::master::ParallelClientArrayMediator, samchon::protocol::master::DistributedClientArray, samchon::protocol::master::DistributedServer, and samchon::protocol::master::ParallelServer.
Definition at line 214 of file EntityGroup.hpp.
Referenced by samchon::library::FTFolder::toXML(), samchon::protocol::ExternalClientArray::toXML(), samchon::protocol::master::ParallelSystemArrayMediator::toXML(), samchon::namtree::NTParameter::toXML(), samchon::example::packer::Wrapper::toXML(), samchon::protocol::ExternalSystem::toXML(), samchon::namtree::NTFile::toXML(), samchon::namtree::NTCriteria::toXML(), samchon::example::tsp::Travel::toXML(), samchon::protocol::Invoke::toXML(), samchon::example::packer::Packer::toXML(), and samchon::example::packer::WrapperArray::toXML().
The documentation for this class was generated from the following file:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/protocol/EntityGroup.hpp