Samchon Framework for CPP: samchon::example::console_chat_server::ChatServer Class Reference
samchon::example::console_chat_server::ChatServer Class Reference
A chat server.
#include <ChatServer.hpp>
Public Member Functions
ChatServer ()
Default Constructor.
void eraseClient (ChatClient *client)
Erase client when disconnected.
virtual void replyData (std::shared_ptr< protocol::Invoke >) override
Handling replied message.
virtual void sendData (std::shared_ptr< protocol::Invoke >) override
Sending a message.
Public Member Functions inherited from samchon::protocol::IServer
IServer ()
Default Constructor.
virtual void open ()
Open the server.
virtual void close ()
Close the server.
Public Member Functions inherited from samchon::protocol::IProtocol
IProtocol ()
Default Constructor.
virtual void replyData (std::shared_ptr< Invoke >)
Reply a message.
virtual void sendData (std::shared_ptr< Invoke >)
Send a message.
Protected Member Functions
virtual auto PORT () const -> int override
Port number: #33749.
virtual void addClient (protocol::Socket *socket) override
Add a client.
Protected Member Functions inherited from samchon::protocol::IServer
virtual auto MY_IP () const -> std::string
(optional) Server's IP
Private Attributes
std::set< ChatClient * > clientSet
List of clients.
library::RWMutex rwMutex
A rw_mutex managing clientSet.
Additional Inherited Members
Protected Attributes inherited from samchon::protocol::IServer
Acceptor * acceptor
An acceptor for clients.
Detailed Description
A chat server.
Author
Jeongho Nam
Definition at line 30 of file ChatServer.hpp.
Constructor & Destructor Documentation
ChatServer::ChatServer ()
Default Constructor.
Definition at line 12 of file ChatServer.cpp.
Member Function Documentation
void ChatServer::eraseClient (ChatClient * client)
Erase client when disconnected.
Definition at line 25 of file ChatServer.cpp.
References clientSet, and rwMutex.
Referenced by samchon::example::console_chat_server::ChatClient::~ChatClient().
virtual auto samchon::example::console_chat_server::ChatServer::PORT () const -> int inline override protected virtual
Port number: #33749.
Reimplemented from samchon::protocol::IServer.
Definition at line 63 of file ChatServer.hpp.
References addClient(), replyData(), and sendData().
void ChatServer::addClient (protocol::Socket * socket) override protected virtual
Add a client.
Implements samchon::protocol::IServer.
Definition at line 16 of file ChatServer.cpp.
References clientSet, samchon::protocol::IClient::listen(), and rwMutex.
Referenced by PORT().
void ChatServer::replyData (std::shared_ptr< protocol::Invoke >) override virtual
Handling replied message.
When got a message from a client, sends the message to all clients.
Parameters
invoke An invoke message represents a chat.
Definition at line 31 of file ChatServer.cpp.
References sendData().
Referenced by PORT(), and samchon::example::console_chat_server::ChatClient::replyData().
void ChatServer::sendData (std::shared_ptr< protocol::Invoke >) override virtual
Sending a message.
Send a message to all clients. Called by replyData().
Parameters
invoke An invoke message represents a chat.
Definition at line 35 of file ChatServer.cpp.
References clientSet, and rwMutex.
Referenced by PORT(), and replyData().
Member Data Documentation
std::set<ChatClient*> samchon::example::console_chat_server::ChatServer::clientSet private
List of clients.
Definition at line 40 of file ChatServer.hpp.
Referenced by addClient(), eraseClient(), and sendData().
library::RWMutex samchon::example::console_chat_server::ChatServer::rwMutex private
A rw_mutex managing clientSet.
Definition at line 45 of file ChatServer.hpp.
Referenced by addClient(), eraseClient(), and sendData().
The documentation for this class was generated from the following files:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/example/console_chat_server/ChatServer.hpp
D:/OneDrive/Project/Samchon/framework/cpp/samchon/example/console_chat_server/ChatServer.cpp