Samchon Framework for CPP: samchon::protocol::service::Server Class Reference
samchon::protocol::service::Server Class Reference abstract
A server for (cloud) service.
#include <Server.hpp>
Public Member Functions
Server ()
Default Constructor.
auto size () const -> size_t
Size of User(s).
auto begin () const -> const_iterator
A const iterator of begin.
auto end () const -> const_iterator
A const iterator of end.
Public Member Functions inherited from samchon::protocol::IServer
IServer ()
Default Constructor.
virtual void open ()
Open the server.
virtual void close ()
Close the server.
Protected Member Functions
virtual auto NAME () const -> std::string=0
A name can be an identifier of a cloud server.
virtual auto createUser () -> User *=0
Factory method of User.
virtual void addClient (Socket *) override
Handling connection of a client.
Protected Member Functions inherited from samchon::protocol::IServer
virtual auto MY_IP () const -> std::string
(optional) Server's IP
virtual auto PORT () const -> int=NULL
Port number of the server.
Protected Attributes
library::SQLi * sqli
SQLi for archiving log.
Protected Attributes inherited from samchon::protocol::IServer
Acceptor * acceptor
An acceptor for clients.
Private Attributes
Dictionary< std::shared_ptr< IPUserPair > > ipMap
Dictionary of issuer of session ID of each ip.
size_t sequence
Sequence for issuing session ID.
Additional Inherited Members
Private Member Functions inherited from samchon::Map< _Kty, _Ty, _Pr, _Alloc >
auto has (const _Kty &key) const -> bool
Whether have the item or not.
auto get (const _Kty &key) -> _Ty &
Get element.
void set (const _Kty &key, const _Ty &val)
Set element.
auto pop (const _Kty &key) -> _Ty
Pop item.
Detailed Description
A server for (cloud) service.
A server class representing the real physical server of a cloud.
The Server is very good for development of a cloud server. You can use web or flex as (physical) client. The usage is very simple. In the class Server, what you need to do are overriding getter of port number and factory method creating an User.
Note
Override those methods.
Server::NAME()
Server::PORT()
Server::createUser()
See also
samchon::protocol
samchon::protocol::service
Author
Jeongho Nam http://samchon.org
Definition at line 48 of file Server.hpp.
Constructor & Destructor Documentation
Server::Server ()
Default Constructor.
Definition at line 31 of file Server.cpp.
References sequence, and sqli.
Member Function Documentation
virtual auto samchon::protocol::service::Server::NAME () const -> std::string protected pure virtual
A name can be an identifier of a cloud server.
auto Server::size () const -> size_t
Size of User(s).
Definition at line 53 of file Server.cpp.
auto Server::begin () const -> const_iterator
A const iterator of begin.
Note
Be careful about concurrency
Definition at line 57 of file Server.cpp.
Referenced by samchon::example::chat_service::ChatRoomArray::notify().
auto Server::end () const -> const_iterator
A const iterator of end.
Note
Be careful about concurrency
Definition at line 61 of file Server.cpp.
Referenced by addClient(), and samchon::example::chat_service::ChatRoomArray::notify().
virtual auto samchon::protocol::service::Server::createUser () -> User * protected pure virtual
Factory method of User.
Implemented in samchon::example::chat_service::ChatServer.
Referenced by addClient().
void Server::addClient (Socket * socket) override protected virtual
Handling connection of a client.
Implements samchon::protocol::IServer.
Definition at line 69 of file Server.cpp.
References createUser(), end(), samchon::SmartPointer< _Ty >::get(), samchon::Map< _Kty, _Ty, _Pr, _Alloc >::has(), samchon::protocol::service::IPUserPair::ip, ipMap, sequence, and samchon::protocol::service::IPUserPair::userSet.
Member Data Documentation
library::SQLi* samchon::protocol::service::Server::sqli protected
SQLi for archiving log.
Definition at line 67 of file Server.hpp.
Referenced by Server().
Dictionary<std::shared_ptr<IPUserPair> > samchon::protocol::service::Server::ipMap private
Dictionary of issuer of session ID of each ip.
Definition at line 75 of file Server.hpp.
Referenced by addClient().
size_t samchon::protocol::service::Server::sequence private
Sequence for issuing session ID.
Definition at line 80 of file Server.hpp.
Referenced by addClient(), and Server().
The documentation for this class was generated from the following files:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/protocol/service/Server.hpp
D:/OneDrive/Project/Samchon/framework/cpp/samchon/protocol/service/Server.cpp