Samchon Framework for CPP: samchon::example::interaction::PackerMediator Class Reference
samchon::example::interaction::PackerMediator Class Reference
A mediator of parallel system solving packaging problem.
#include <PackerMediator.hpp>
Public Member Functions
PackerMediator ()
Default Constructor.
Public Member Functions inherited from samchon::protocol::master::ParallelClientArrayMediator
ParallelClientArrayMediator ()
Default Constructor.
virtual void construct (std::shared_ptr< library::XML >) override
Construct data of the Entity from an XML object.
virtual void start () override
Start interaction.
virtual auto toXML () const -> std::shared_ptr< library::XML > override
Get an XML object represents the EntityGroup.
Public Member Functions inherited from samchon::protocol::master::ParallelSystemArrayMediator
ParallelSystemArrayMediator ()
Default Constructor.
Public Member Functions inherited from samchon::protocol::master::ParallelSystemArray
ParallelSystemArray ()
Default Constructor.
void sendSegmentData (std::shared_ptr< Invoke >, size_t)
Send a message with segmentation size.
virtual void sendPieceData (std::shared_ptr< Invoke >, size_t, size_t)
Send a message with piece index and size.
Public Member Functions inherited from samchon::protocol::ExternalSystemArray
ExternalSystemArray ()
Default Constructor.
auto hasRole (const std::string &) const -> bool
Test whether has a role.
auto getRole (const std::string &) const -> std::shared_ptr< ExternalSystemRole >
Get a role.
virtual void sendData (std::shared_ptr< Invoke >) override
Sends an Invoke message to related ExternalSystem(s).
virtual void replyData (std::shared_ptr< Invoke >) override
Handle replied Invoke message.
virtual auto TAG () const -> std::string override
A tag name when represented by XML.
virtual auto CHILD_TAG () const -> std::string override
A tag name of children.
Public Member Functions inherited from samchon::protocol::EntityGroup< Container, T >
auto has (const std::string &key) const -> bool
Indicates whether a container has an object having the specified identifier.
auto get (const std::string &key) -> typename Container::value_type &
Access the element by specified identifier(key).
auto get (const std::string &key) const -> const typename Container::value_type &
Access the const element by specified identifier(key).
Public Member Functions inherited from samchon::protocol::Entity
Entity ()
Default Constructor.
virtual auto key () const -> std::string
Get a key that can identify the Entity uniquely.
Public Member Functions inherited from samchon::protocol::IEntityGroup
IEntityGroup ()
Default Constructor.
Public Member Functions inherited from samchon::protocol::IProtocol
IProtocol ()
Default Constructor.
Public Member Functions inherited from samchon::protocol::master::ParallelClientArray
ParallelClientArray ()
Default Constructor.
Public Member Functions inherited from samchon::protocol::ExternalClientArray
ExternalClientArray ()
Default Constructor.
Static Public Member Functions
static void main ()
Main functino.
Protected Member Functions
virtual void addClient (protocol::Socket *socket) override
Handling connection of a physical client.
void replyOptimization (std::shared_ptr< library::XML > xml)
Handle (replied) optimized value from a slave system.
Protected Member Functions inherited from samchon::protocol::master::ParallelSystemArrayMediator
virtual void notifyEnd (PRMasterHistory *)
Notify end of a master history.
Protected Member Functions inherited from samchon::protocol::EntityGroup< Container, T >
virtual auto createChild (std::shared_ptr< library::XML >) -> T *=0
Factory method of a child Entity.
Protected Member Functions inherited from samchon::protocol::ExternalClientArray
virtual auto PORT () const -> int
Port number of the server.
virtual auto MY_IP () const -> std::string
(optional) Server's IP
Protected Attributes
std::shared_ptr< packer::Packer > packer
A packer solver.
std::mutex mtx
A mutex for optimization.
size_t optimized
Number of slaves who'd completed an optimization.
Protected Attributes inherited from samchon::protocol::master::ParallelSystemArrayMediator
ParallelSlaveSystemMediator * slave
A slave system for mediation.
Protected Attributes inherited from samchon::protocol::ExternalClientArray
std::string myIP
A custom ip address of my system to bind.
int port
A port number for accepting external clients.
Detailed Description
A mediator of parallel system solving packaging problem.
PackerMediator is a class representing mediator class of tree-structured parallel processing system solving packaging problem.
Packer mediator system is placed on between master and slave systems. It can be a slave system for its master, and also can be a master system for its own slave systems. Mediator is a class representing mediator class of parallel processing system.
The PackerMediator is built for providing a guidance of building a mediator system in a tree-structured parallel processing system. You can also learn how to utilize master module in protocol by following the example.
[Inherited] PackerMaster
[Inherited]
Master is an abstract and example class, for providing guidance of realizing parallel processing system for users, within framework of master. The Master class represents a master of parallel processing system in the master side.
A master system (represented by Master and MasterDriver) is associated with a chief system (represented by Cheif and CheifDriver) and slave systems (Slave and SlaveDriver). The master system gets optimization order from chief system and shifts and distributes orders to its slave systems. When slave systems report optimization result, the master system aggregates those results and reports the aggregated results to chief system.
[Inherited]
See also
master
Author
Jeongho Nam http://samchon.org
Jeongho Nam http://samchon.org
[Inherited] ParallelClientArrayMediator
Author
Jeongho Nam http://samchon.org
Definition at line 44 of file PackerMediator.hpp.
Constructor & Destructor Documentation
samchon::example::interaction::PackerMediator::PackerMediator () inline
Default Constructor.
Definition at line 76 of file PackerMediator.hpp.
References samchon::protocol::ExternalClientArray::port, and samchon::protocol::master::ParallelSystemArrayMediator::slave.
Member Function Documentation
virtual void samchon::example::interaction::PackerMediator::addClient (protocol::Socket *) inline override protected virtual
Handling connection of a physical client.
Reimplemented from samchon::protocol::ExternalClientArray.
Definition at line 93 of file PackerMediator.hpp.
References samchon::protocol::ExternalClientArray::addClient(), replyOptimization(), and samchon::protocol::master::ParallelSystemArray::sendPieceData().
void samchon::example::interaction::PackerMediator::replyOptimization (std::shared_ptr< library::XML > xml) inline protected
Handle (replied) optimized value from a slave system.
When gets optimization result from Slave systems, Master aggregates them and derives the best solution between those results and reports the best solution to the Cheif system.
Parameters
xml XML object representing the optimized value.
Definition at line 132 of file PackerMediator.hpp.
References packer, samchon::protocol::IClient::sendData(), and samchon::protocol::master::ParallelSystemArrayMediator::slave.
Referenced by addClient().
static void samchon::example::interaction::PackerMediator::main () inline static
Main functino.
Definition at line 162 of file PackerMediator.hpp.
References samchon::protocol::ExternalClientArray::port, and samchon::protocol::master::ParallelClientArrayMediator::start().
Member Data Documentation
std::shared_ptr<packer::Packer> samchon::example::interaction::PackerMediator::packer protected
A packer solver.
Definition at line 54 of file PackerMediator.hpp.
Referenced by replyOptimization().
std::mutex samchon::example::interaction::PackerMediator::mtx protected
A mutex for optimization.
The mutex exists for ensuring concurrency of aggregation of optimization reported from slave systems.
Definition at line 62 of file PackerMediator.hpp.
size_t samchon::example::interaction::PackerMediator::optimized protected
Number of slaves who'd completed an optimization.
Definition at line 67 of file PackerMediator.hpp.
The documentation for this class was generated from the following file:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/example/interaction/PackerMediator.hpp