Samchon Framework for CPP: samchon::protocol::master::ParallelSlaveSystemMediator Class Reference
samchon::protocol::master::ParallelSlaveSystemMediator Class Reference
A parallel slave system for mediation.
#include <ParallelSlaveSystemMediator.hpp>
Public Member Functions
ParallelSlaveSystemMediator ()
Default Constructor.
virtual void replyPieceData (std::shared_ptr< Invoke >, size_t, size_t) override
Handle requested processes which are segmented.
virtual auto TAG () const -> std::string override
A tag name when represented by XML.
Public Member Functions inherited from samchon::protocol::slave::ParallelSystem
ParallelSystem ()
Default Constructor.
Public Member Functions inherited from samchon::protocol::slave::SlaveSystem
SlaveSystem ()
Default Constructor.
virtual void sendData (std::shared_ptr< Invoke >) override
Sends message to a related system.
Public Member Functions inherited from samchon::protocol::ExternalSystem
ExternalSystem ()
Default Constructor.
virtual void construct (std::shared_ptr< library::XML >) override
Construct data of the Entity from an XML object.
virtual void start ()=0
Start interaction.
virtual auto key () const -> std::string override
Get a key that can identify the Entity uniquely.
virtual void replyData (std::shared_ptr< Invoke >) override
Handling replied message from an external system.
virtual auto CHILD_TAG () const -> std::string override
A tag name of children.
virtual auto toXML () const -> std::shared_ptr< library::XML > override
Get an XML object represents the EntityGroup.
Public Member Functions inherited from samchon::protocol::EntityGroup< _Container, _ETy, _Ty >
EntityGroup ()
Default Constructor.
auto has (const std::string &key) const -> bool
Indicates whether a container has an object having the specified identifier.
auto get (const std::string &key) -> value_type &
Access the element by specified identifier(key).
auto get (const std::string &key) const -> const value_type &
Access the const element by specified identifier(key).
Public Member Functions inherited from samchon::protocol::Entity
Entity ()
Default Constructor.
Public Member Functions inherited from samchon::protocol::IEntityGroup
IEntityGroup ()
Default Constructor.
Public Member Functions inherited from samchon::protocol::IClient
IClient ()
Default Constructor.
virtual void listen ()
Listens message from a related system.
Public Member Functions inherited from samchon::protocol::IProtocol
IProtocol ()
Default Constructor.
Private Attributes
ParallelSystemArrayMediator * master
A master system for mediation.
Additional Inherited Members
Protected Member Functions inherited from samchon::protocol::slave::ParallelSystem
virtual auto createChild (std::shared_ptr< library::XML >) -> ExternalSystemRole *override
Factory method of a child Entity.
virtual void _replyData (std::shared_ptr< Invoke >) override
Pre-processor for segmented processes and reporting elapsed time.
Protected Member Functions inherited from samchon::protocol::IClient
virtual auto BUFFER_SIZE () const -> size_t
Buffer size of network I/O.
Protected Attributes inherited from samchon::protocol::ExternalSystem
std::string name
A name can identify an external system.
std::string ip
An ip address of an external system.
int port
A port number of an external system.
Protected Attributes inherited from samchon::protocol::IClient
Socket * socket
Socket for network I/O.
std::mutex * sendMtx
A mutex for sending message.
Detailed Description
A parallel slave system for mediation.
ParallelSlaveSystemMediator is an abstract class derived from slave::ParallelSystem for realizing tree-structured distriuted processins system. ParallelSlaveSystemMediator acts a slave system's role for its master, on the above level.
ParallelSystemArrayMediator and ParallelSlaveSystemMediator classes are paired to act a mediator system role by acting their own role, master system role for below slaves and slave system role for above master system.
[Inherited]
SlaveSystem, literally, means a slave system belongs to a maste system.
The SlaveSystem class is used in opposite side system of master::DistributedSystem and master::ParallelSystem and reports elapsed time of each commmand (by Invoke message) for estimation of its performance.
[Inherited]
ExternalSystem is a boundary class interacting with an external system by network communication. Also, ExternalSystem is an abstract class that a network role, which one is server and which one is client, is not determined yet.
The ExternalSystem has ExternalSystemRole(s) groupped methods, handling Invoke message interacting with the external system, by subject or unit of a moudle. The ExternalSystemRole is categorized in a 'control'.
Note
The ExternalSystem class takes a role of interaction with external system in network level. However, within a framework of Samchon Framework, a boundary class like the ExternalSystem is not such important. You can find some evidence in a relationship between ExternalSystemArray, ExternalSystem and ExternalSystemRole.
Of course, the ExternalSystemRole is belonged to an ExternalSystem. However, if you access an ExternalSystemRole from an ExternalSystemArray directly, not passing by a belonged ExternalSystem, and send an Invoke message even you're not knowing which ExternalSystem is related in, it's called "Proxy pattern".
Like the explanation of "Proxy pattern", you can utilize an ExternalSystemRole as a proxy of an ExternalSystem. With the pattern, you can only concentrate on ExternalSystemRole itself, what to do with Invoke message, irrespective of the ExternalSystemRole is belonged to which ExternalSystem.
See also
samchon::protocol
Author
Jeongho Nam
Definition at line 35 of file ParallelSlaveSystemMediator.hpp.
Constructor & Destructor Documentation
ParallelSlaveSystemMediator::ParallelSlaveSystemMediator ()
Default Constructor.
Definition at line 12 of file ParallelSlaveSystemMediator.cpp.
References master.
Member Function Documentation
void ParallelSlaveSystemMediator::replyPieceData (std::shared_ptr< Invoke > , size_t , size_t) override virtual
Handle requested processes which are segmented.
Parameters
invoke An invoke message containing segmented process requestments.
startIndex Starting index number of segmentation.
size Size of segmentation.
Implements samchon::protocol::slave::ParallelSystem.
Definition at line 17 of file ParallelSlaveSystemMediator.cpp.
References master, and samchon::protocol::master::ParallelSystemArray::sendPieceData().
auto ParallelSlaveSystemMediator::TAG () const -> std::string override virtual
A tag name when represented by XML.
Returns
A tag name
Reimplemented from samchon::protocol::ExternalSystem.
Definition at line 25 of file ParallelSlaveSystemMediator.cpp.
Referenced by samchon::protocol::master::ParallelClientArrayMediator::construct(), and samchon::protocol::master::ParallelSystemArrayMediator::construct().
Member Data Documentation
ParallelSystemArrayMediator* samchon::protocol::master::ParallelSlaveSystemMediator::master private
A master system for mediation.
Definition at line 46 of file ParallelSlaveSystemMediator.hpp.
Referenced by ParallelSlaveSystemMediator(), and replyPieceData().
The documentation for this class was generated from the following files:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/protocol/master/ParallelSlaveSystemMediator.hpp
D:/OneDrive/Project/Samchon/framework/cpp/samchon/protocol/master/ParallelSlaveSystemMediator.cpp