Samchon Framework for CPP: samchon::example::packer::Wrapper Class Reference
samchon::example::packer::Wrapper Class Reference
A wrapper can contain products.
#include <Wrapper.hpp>
Public Member Functions
Wrapper ()
Default Constructor.
Wrapper (const std::string &name, int price, int volume, int weight)
Construct from argument of a wrapper.
Wrapper (const Wrapper &wrapper)
Copy Constructor.
virtual void construct (std::shared_ptr< library::XML > xml) override
Construct data of the Entity from an XML object.
auto tryInsert (std::shared_ptr< Product > product) -> bool
Try to insert a product into the wrapper.
virtual auto TAG () const -> std::string override
A tag name when represented by XML.
virtual auto toXML () const -> std::shared_ptr< library::XML > override
Get an XML object represents the Entity.
virtual auto toString () const -> std::string override
Return a string represent the wrapper.
Public Member Functions inherited from samchon::example::packer::ProductArray
virtual auto CHILD_TAG () const -> std::string override
A tag name of children.
Public Member Functions inherited from samchon::protocol::EntityGroup< _Container, _ETy, _Ty >
EntityGroup ()
Default Constructor.
auto has (const std::string &key) const -> bool
Indicates whether a container has an object having the specified identifier.
auto get (const std::string &key) -> value_type &
Access the element by specified identifier(key).
auto get (const std::string &key) const -> const value_type &
Access the const element by specified identifier(key).
Public Member Functions inherited from samchon::protocol::Entity
Entity ()
Default Constructor.
virtual auto key () const -> std::string
Get a key that can identify the Entity uniquely.
Public Member Functions inherited from samchon::protocol::IEntityGroup
IEntityGroup ()
Default Constructor.
Public Member Functions inherited from samchon::example::packer::Instance
Instance ()
Default Constructor.
Instance (const std::string &name, int price, int volume, int weight)
Construct from instance.
auto getName () const -> std::string
Get name.
auto getPrice () const -> int
Get price.
auto getVolume () const -> int
Get volume.
auto getWeight () const -> int
Get weight.
Additional Inherited Members
Protected Member Functions inherited from samchon::example::packer::ProductArray
virtual auto createChild (std::shared_ptr< library::XML >) -> Product *override
Factory method of a child Entity.
Protected Attributes inherited from samchon::example::packer::Instance
std::string name
Name represent the Instance.
int price
Price of an instance -> 1,000 won.
int volume
Volume of an instance -> 130 cm^3.
int weight
Weight of an instance -> 1,200 g.
Detailed Description
A wrapper can contain products.
A wrapper containing products with its limitation of weight and volume.
Author
Jeongho Nam
Definition at line 24 of file Wrapper.hpp.
Constructor & Destructor Documentation
samchon::example::packer::Wrapper::Wrapper () inline
Default Constructor.
Definition at line 38 of file Wrapper.hpp.
samchon::example::packer::Wrapper::Wrapper (const std::string & name, int price, int volume, int weight) inline
Construct from argument of a wrapper.
Parameters
name Category name of a wrapper, can be identified
price Price of a wrapper
volume Limited volume of a wrapper can put in.
weight Limited weight of a wrapper can put in.
Definition at line 52 of file Wrapper.hpp.
samchon::example::packer::Wrapper::Wrapper (const Wrapper & wrapper) inline
Copy Constructor.
Copy constructor of wrapper does not copy children items. Only copies arguments of Instance's.
Definition at line 62 of file Wrapper.hpp.
Member Function Documentation
virtual void samchon::example::packer::Wrapper::construct (std::shared_ptr< library::XML >) inline override virtual
Construct data of the Entity from an XML object.
Overrides the construct() method and fetch data of member variables from the XML.
By recommended guidance, data representing member variables are contained in properties of the put XML object.
Parameters
xml An xml used to construct data of entity
Reimplemented from samchon::example::packer::Instance.
Definition at line 70 of file Wrapper.hpp.
References samchon::example::packer::Instance::construct(), and samchon::protocol::EntityGroup< _Container, _ETy, _Ty >::construct().
auto samchon::example::packer::Wrapper::tryInsert (std::shared_ptr< Product > product) -> bool inline
Try to insert a product into the wrapper.
If the Wrapper has enough volume and limit of weight, inserts the Product into the Wrapper and returns true. If not enough, does not insert and just return false.
Parameters
product A product try to insert in.
Returns
Whether to success put in
Definition at line 87 of file Wrapper.hpp.
References samchon::example::packer::Instance::volume, and samchon::example::packer::Instance::weight.
Referenced by samchon::example::packer::WrapperArray::optimize().
virtual auto samchon::example::packer::Wrapper::TAG () const -> std::string inline override virtual
A tag name when represented by XML.
Returns
A tag name
Reimplemented from samchon::example::packer::ProductArray.
Definition at line 111 of file Wrapper.hpp.
virtual auto samchon::example::packer::Wrapper::toXML () const -> std::shared_ptr<library::XML> inline override virtual
Get an XML object represents the Entity.
Returns an XML object that can represents the Entity containing member variables into properties.
A member variable (not object, but atomic value like number, string or date) is categorized as a property within the framework of entity side. Thus, when overriding a toXML() method and archiving member variables to an XML object to return, puts each variable to be a property belongs to only an XML object.
Don't archive the member variable of atomic value to XML::value causing enormouse creation of XML objects to number of member variables. An Entity must be represented by only an XML instance (tag).
Standard Usage Non-standard usage abusing value
<memberList>
<member id='jhnam88' name='Jeongho+Nam' birthdate='1988-03-11' />
<member id='master' name='Administartor' birthdate='2011-07-28' />
</memberList> <member>
<id>jhnam88</id>
<name>Jeongho+Nam</name>
<birthdate>1988-03-11</birthdate>
</member>
Returns
An XML object representing the Entity.
Reimplemented from samchon::example::packer::Instance.
Definition at line 116 of file Wrapper.hpp.
References samchon::example::packer::Instance::toXML(), and samchon::protocol::EntityGroup< _Container, _ETy, _Ty >::toXML().
virtual auto samchon::example::packer::Wrapper::toString () const -> std::string inline override virtual
Return a string represent the wrapper.
Returns a string of the Wrapper and Product(s) packaged in.
Returns
A string represents the Wrapper and contained Product(s).
Reimplemented from samchon::example::packer::Instance.
Definition at line 130 of file Wrapper.hpp.
References samchon::example::packer::Instance::toString().
The documentation for this class was generated from the following file:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/example/packer/Wrapper.hpp