.TH "D:/OneDrive/Project/Samchon/framework/cpp/samchon/protocol Directory Reference" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Project/Samchon/framework/cpp/samchon/protocol Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBmaster\fP"
.br
.ti -1c
.RI "directory \fBservice\fP"
.br
.ti -1c
.RI "directory \fBslave\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAPI\&.hpp\fP"
.br
.ti -1c
.RI "file \fBEntity\&.cpp\fP"
.br
.ti -1c
.RI "file \fBEntity\&.hpp\fP"
.br
.ti -1c
.RI "file \fBEntityArray\&.hpp\fP"
.br
.ti -1c
.RI "file \fBEntityGroup\&.cpp\fP"
.br
.ti -1c
.RI "file \fBEntityGroup\&.hpp\fP"
.br
.ti -1c
.RI "file \fBEntityList\&.hpp\fP"
.br
.ti -1c
.RI "file \fBExternalClient\&.cpp\fP"
.br
.ti -1c
.RI "file \fBExternalClient\&.hpp\fP"
.br
.ti -1c
.RI "file \fBExternalClientArray\&.cpp\fP"
.br
.ti -1c
.RI "file \fBExternalClientArray\&.hpp\fP"
.br
.ti -1c
.RI "file \fBExternalServer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBExternalServer\&.hpp\fP"
.br
.ti -1c
.RI "file \fBExternalServerArray\&.cpp\fP"
.br
.ti -1c
.RI "file \fBExternalServerArray\&.hpp\fP"
.br
.ti -1c
.RI "file \fBExternalSystem\&.cpp\fP"
.br
.ti -1c
.RI "file \fBExternalSystem\&.hpp\fP"
.br
.ti -1c
.RI "file \fBExternalSystemArray\&.cpp\fP"
.br
.ti -1c
.RI "file \fBExternalSystemArray\&.hpp\fP"
.br
.ti -1c
.RI "file \fBExternalSystemRole\&.cpp\fP"
.br
.ti -1c
.RI "file \fBExternalSystemRole\&.hpp\fP"
.br
.ti -1c
.RI "file \fBFlashPolicyServer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBFlashPolicyServer\&.hpp\fP"
.br
.ti -1c
.RI "file \fBIClient\&.cpp\fP"
.br
.ti -1c
.RI "file \fBIClient\&.hpp\fP"
.br
.ti -1c
.RI "file \fBIEntityChain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBIEntityChain\&.hpp\fP"
.br
.ti -1c
.RI "file \fBIEntityGroup\&.cpp\fP"
.br
.ti -1c
.RI "file \fBIEntityGroup\&.hpp\fP"
.br
.ti -1c
.RI "file \fBIEntityPtrGroup\&.hpp\fP"
.br
.ti -1c
.RI "file \fBIEntitySharedPtrGroup\&.hpp\fP"
.br
.ti -1c
.RI "file \fBIEntityUniquePtrGroup\&.hpp\fP"
.br
.ti -1c
.RI "file \fBIHTMLEntity\&.cpp\fP"
.br
.ti -1c
.RI "file \fBIHTMLEntity\&.hpp\fP"
.br
.ti -1c
.RI "file \fBInvoke\&.cpp\fP"
.br
.ti -1c
.RI "file \fBInvoke\&.hpp\fP"
.br
.ti -1c
.RI "file \fBInvokeHistory\&.cpp\fP"
.br
.ti -1c
.RI "file \fBInvokeHistory\&.hpp\fP"
.br
.ti -1c
.RI "file \fBInvokeHistoryArray\&.cpp\fP"
.br
.ti -1c
.RI "file \fBInvokeHistoryArray\&.hpp\fP"
.br
.ti -1c
.RI "file \fBInvokeParameter\&.cpp\fP"
.br
.ti -1c
.RI "file \fBInvokeParameter\&.hpp\fP"
.br
.ti -1c
.RI "file \fBIProtocol\&.cpp\fP"
.br
.ti -1c
.RI "file \fBIProtocol\&.hpp\fP"
.br
.ti -1c
.RI "file \fBIServer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBIServer\&.hpp\fP"
.br
.ti -1c
.RI "file \fBISQLEntity\&.cpp\fP"
.br
.ti -1c
.RI "file \fBISQLEntity\&.hpp\fP"
.br
.ti -1c
.RI "file \fBIWebClient\&.hpp\fP"
.br
.ti -1c
.RI "file \fBIWebServer\&.hpp\fP"
.br
.ti -1c
.RI "file \fBPRInvokeHistory\&.cpp\fP"
.br
.ti -1c
.RI "file \fBServerConnector\&.cpp\fP"
.br
.ti -1c
.RI "file \fBServerConnector\&.hpp\fP"
.br
.ti -1c
.RI "file \fBSharedEntityArray\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSharedEntityArray\&.hpp\fP"
.br
.ti -1c
.RI "file \fBSharedEntityList\&.hpp\fP"
.br
.ti -1c
.RI "file \fBSocket\&.hpp\fP"
.br
.ti -1c
.RI "file \fBSystemRole\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSystemRole\&.hpp\fP"
.br
.ti -1c
.RI "file \fBUniqueAcquire\&.cpp\fP"
.br
.ti -1c
.RI "file \fBUniqueEntityArray\&.hpp\fP"
.br
.ti -1c
.RI "file \fBUniqueEntityList\&.hpp\fP"
.br
.ti -1c
.RI "file \fBWebServerConnector\&.hpp\fP"
.br
.in -1c
