.TH "D:/OneDrive/Project/Samchon/framework/cpp/samchon/protocol/slave Directory Reference" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Project/Samchon/framework/cpp/samchon/protocol/slave Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBInvokeHistory\&.cpp\fP"
.br
.ti -1c
.RI "file \fBParallelClient\&.hpp\fP"
.br
.ti -1c
.RI "file \fBParallelServer\&.hpp\fP"
.br
.ti -1c
.RI "file \fBParallelSlaveClientMediator\&.hpp\fP"
.br
.ti -1c
.RI "file \fBParallelSlaveServerMediator\&.hpp\fP"
.br
.ti -1c
.RI "file \fBParallelSystem\&.hpp\fP"
.br
.ti -1c
.RI "file \fBSlaveClient\&.hpp\fP"
.br
.ti -1c
.RI "file \fBSlaveServer\&.hpp\fP"
.br
.ti -1c
.RI "file \fBSlaveSystem\&.hpp\fP"
.br
.in -1c
