.TH "D:/OneDrive/Project/Samchon/framework/cpp/samchon/protocol/master Directory Reference" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Project/Samchon/framework/cpp/samchon/protocol/master Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDistributedClient\&.hpp\fP"
.br
.ti -1c
.RI "file \fBDistributedClientArray\&.hpp\fP"
.br
.ti -1c
.RI "file \fBDistributedClientArrayMediator\&.hpp\fP"
.br
.ti -1c
.RI "file \fBDistributedServer\&.hpp\fP"
.br
.ti -1c
.RI "file \fBDistributedServerArray\&.hpp\fP"
.br
.ti -1c
.RI "file \fBDistributedServerArrayMediator\&.hpp\fP"
.br
.ti -1c
.RI "file \fBDistributedSlaveClientMediator\&.hpp\fP"
.br
.ti -1c
.RI "file \fBDistributedSlaveServerMediator\&.hpp\fP"
.br
.ti -1c
.RI "file \fBDistributedSlaveSystemMediator\&.hpp\fP"
.br
.ti -1c
.RI "file \fBDistributedSystem\&.hpp\fP"
.br
.ti -1c
.RI "file \fBDistributedSystemArray\&.hpp\fP"
.br
.ti -1c
.RI "file \fBDistributedSystemArrayMediator\&.hpp\fP"
.br
.ti -1c
.RI "file \fBDistributedSystemRole\&.hpp\fP"
.br
.ti -1c
.RI "file \fBDSInvokeHistory\&.cpp\fP"
.br
.ti -1c
.RI "file \fBDSInvokeHistory\&.hpp\fP"
.br
.ti -1c
.RI "file \fBDSInvokeHistoryList\&.hpp\fP"
.br
.ti -1c
.RI "file \fBParallelClient\&.hpp\fP"
.br
.ti -1c
.RI "file \fBParallelClientArray\&.cpp\fP"
.br
.ti -1c
.RI "file \fBParallelClientArray\&.hpp\fP"
.br
.ti -1c
.RI "file \fBParallelClientArrayMediator\&.hpp\fP"
.br
.ti -1c
.RI "file \fBParallelServer\&.hpp\fP"
.br
.ti -1c
.RI "file \fBParallelServerArray\&.cpp\fP"
.br
.ti -1c
.RI "file \fBParallelServerArray\&.hpp\fP"
.br
.ti -1c
.RI "file \fBParallelServerArrayMediator\&.hpp\fP"
.br
.ti -1c
.RI "file \fBParallelSlaveSystemMediator\&.hpp\fP"
.br
.ti -1c
.RI "file \fBParallelSystem\&.cpp\fP"
.br
.ti -1c
.RI "file \fBParallelSystem\&.hpp\fP"
.br
.ti -1c
.RI "file \fBParallelSystemArray\&.cpp\fP"
.br
.ti -1c
.RI "file \fBParallelSystemArray\&.hpp\fP"
.br
.ti -1c
.RI "file \fBParallelSystemArrayMediator\&.hpp\fP"
.br
.ti -1c
.RI "file \fBPRInvokeHistory\&.hpp\fP"
.br
.ti -1c
.RI "file \fBPRInvokeHistoryArray\&.hpp\fP"
.br
.ti -1c
.RI "file \fBPRInvokeHistoryList\&.cpp\fP"
.br
.ti -1c
.RI "file \fBPRMasterHistory\&.hpp\fP"
.br
.in -1c
