.TH "samchon::example::console_chat_server" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
samchon::example::console_chat_server \- A chat server\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBChatClient\fP"
.br
.RI "\fIA chat client\&. \fP"
.ti -1c
.RI "class \fBChatServer\fP"
.br
.RI "\fIA chat server\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A chat server\&. 

A simple chat server operates on a console\&.
.PP
 
.PP
\fBAuthor:\fP
.RS 4
Jeongho Nam 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Samchon Framework for CPP from the source code\&.
