.TH "ChatClient" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChatClient \- A client\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ChatClient\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChatClient\fP (\fBprotocol::service::User\fP *)"
.br
.RI "\fIConstruct from an user\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "auto \fBcreateService\fP (const std::string &) \-> \fBprotocol::service::Service\fP *override"
.br
.RI "\fIFactory method of Service\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A client\&. 

 
.PP
\fBAuthor:\fP
.RS 4
Jeongho Nam 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "auto createService (const std::string &) \->  \fBprotocol::service::Service\fP *override\fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Factory method of Service\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP Requested name representing a Service from the (physical) client 
.RE
.PP
\fBReturns:\fP
.RS 4
A new Service belongs the the Client 
.RE
.PP

.PP
Implements \fBClient\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Samchon Framework for CPP from the source code\&.
