.TH "samchon::protocol::slave" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
samchon::protocol::slave \- Package of external system, within the framework of slave\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBParallelClient\fP"
.br
.RI "\fIA slave parallel client\&. \fP"
.ti -1c
.RI "class \fBParallelServer\fP"
.br
.RI "\fIA slave parallel server\&. \fP"
.ti -1c
.RI "class \fBParallelSystem\fP"
.br
.RI "\fIA slave parallel system\&. \fP"
.ti -1c
.RI "class \fBSlaveClient\fP"
.br
.RI "\fIA slave client\&. \fP"
.ti -1c
.RI "class \fBSlaveServer\fP"
.br
.RI "\fIA slave server\&. \fP"
.ti -1c
.RI "class \fBSlaveSystem\fP"
.br
.RI "\fIA slave system\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Package of external system, within the framework of slave\&. 

A package for composing distributed or parallel processing system in slave side\&. 
.PP
Slave system get orders from master, processes the orders and report the result with its elapsed time for estimating performance of the slave system\&. 
.PP
 
.PP
\fBAuthor:\fP
.RS 4
Jeongho Nam 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Samchon Framework for CPP from the source code\&.
