.TH "GAParameters" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GAParameters \- Parameters for Genetic-Algorithm\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Scheduler\&.hpp>\fP
.SH "Detailed Description"
.PP 
Parameters for Genetic-Algorithm\&. 

 
.PP
\fBSee also:\fP
.RS 4
\fBsamchon::library::GeneticAlgorithm\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Jeongho Nam 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Samchon Framework for CPP from the source code\&.
