.TH "ServiceKeeper" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ServiceKeeper \- A keeper blocking destrunction of \fBUser\fP and \fBClient\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ServiceKeeper\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBServiceKeeper\fP (const \fBUser\fP *\fBuser\fP, const \fBClient\fP *\fBclient\fP)"
.br
.RI "\fIConstruct from \fBUser\fP and \fBClient\fP\&. \fP"
.ti -1c
.RI "\fBServiceKeeper\fP (const \fBServiceKeeper\fP &)"
.br
.RI "\fICopy Constructor\&. \fP"
.ti -1c
.RI "\fBServiceKeeper\fP (\fBServiceKeeper\fP &&)"
.br
.RI "\fIMovie Constructor\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBSmartPointer\fP< \fBUser\fP > \fBuser\fP"
.br
.RI "\fIA shared pionter of an \fBUser\fP\&. \fP"
.ti -1c
.RI "\fBSmartPointer\fP< \fBClient\fP > \fBclient\fP"
.br
.RI "\fIA shared pointer of a \fBClient\fP\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A keeper blocking destrunction of \fBUser\fP and \fBClient\fP\&. 

Keeps \fBUser\fP, \fBClient\fP and \fBService\fP objects until termination of a stack\&. 
.PP
You can prevent the object to be destructed until the method is in a process\&. \fBUser\fP, \fBClient\fP and \fBService\fP provides a macro instruction for it\&. 
.PP
 
.PP
\fBNote:\fP
.RS 4
Defined macros 
.PD 0

.IP "\(bu" 2
KEEP_USER_ALIVE 
.IP "\(bu" 2
KEEP_CLIENT_ALIVE 
.IP "\(bu" 2
KEEP_SERVICE_ALIVE
.PP
.RE
.PP
\fBSee also:\fP
.RS 4
\fBsamchon::protocol\fP 
.PP
\fBsamchon::protocol::service\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Jeongho Nam 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBServiceKeeper\fP (const \fBUser\fP * user, const \fBClient\fP * client)"

.PP
Construct from \fBUser\fP and \fBClient\fP\&. user An \fBUser\fP to keep client A \fBClient\fP to keep 

.SH "Author"
.PP 
Generated automatically by Doxygen for Samchon Framework for CPP from the source code\&.
