.TH "GAParameters" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GAParameters \- A structure containing parameters of genetic algorithm\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GAParameters\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBgeneration\fP"
.br
.RI "\fIA number of generation of evolution\&. \fP"
.ti -1c
.RI "size_t \fBpopulation\fP"
.br
.RI "\fIA number of population in a generation\&. \fP"
.ti -1c
.RI "size_t \fBtournament\fP"
.br
.RI "\fIA number of tournament in a selection\&. \fP"
.ti -1c
.RI "double \fBmutationRate\fP"
.br
.RI "\fIRate of mutate ocurrence\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A structure containing parameters of genetic algorithm\&. 

The number and rate parameters in the structure affects success of evolution of genetic algorithm\&. 
.PP
\fBSee also:\fP
.RS 4
\fBlibrary::GeneticAlgorithm\fP 
.PP
\fBlibrary::GAPopulation\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Jeongho Nam 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "double mutationRate"

.PP
Rate of mutate ocurrence\&. A mutation rate determines the percentage of occurence of mutation in a sequence list\&. 
.PP
.PD 0
.IP "\(bu" 2
Value from 0\&.0 to 1\&.0
.PP
\fBNote:\fP
.RS 4
.PD 0
.IP "\(bu" 2
When mutationRate is too high, it is hard to ancitipate studying on genetic algorithm\&. 
.IP "\(bu" 2
When mutationRate is too low and initial set of genes(GeneArray) is far away from optimal, the evolution tends to wandering outside of he optimal\&. 
.PP
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Samchon Framework for CPP from the source code\&.
