.TH "Travel" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Travel \- Represent a travel containning Point(s)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Travel\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTravel\fP ()"
.br
.RI "\fIDefault Constructor\&. \fP"
.ti -1c
.RI "\fBTravel\fP (const \fBTravel\fP &)"
.br
.RI "\fICopy Constructor\&. \fP"
.ti -1c
.RI "\fBTravel\fP (\fBTravel\fP &&)"
.br
.RI "\fIMove Constructor\&. \fP"
.ti -1c
.RI "auto \fBoperator<\fP (const \fBTravel\fP &) const  \-> bool"
.br
.RI "\fICompare which object is less\&. \fP"
.ti -1c
.RI "auto \fBtoString\fP () const  \-> std::string"
.br
.RI "\fIConvert the \fBTravel\fP to String\&. \fP"
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "auto \fBcalcDistance\fP () const  \-> double"
.br
.RI "\fICalculate distance to move\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "double \fBdistance\fP"
.br
.RI "\fIEstimated hours to move\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Represent a travel containning Point(s) 

\fBTravel\fP class is not only an array containing Point(s) but also a sequence listing of the Point(s)\&. 
.PP
 
.PP
\fBAuthor:\fP
.RS 4
Jeongho Nam 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBTravel\fP (const \fBTravel\fP & travel)"

.PP
Copy Constructor\&. \fBTravel\fP is an array of Point(s) as gene(s)\&. The copy constructor of \fBTravel\fP doesn't copy member variables which are related to G\&.A\&. because the sequence of gene(Point)s can be shuffled by process of evolution of genetic algorithm\&. 
.SH "Member Function Documentation"
.PP 
.SS "auto operator< (const \fBTravel\fP & travel) const \-> bool"

.PP
Compare which object is less\&. Compares distances to move\&. The result is used to optimize and evolve genes by G\&.A\&.
.PP
\fBParameters:\fP
.RS 4
\fITarget\fP object to compare 
.RE
.PP
\fBReturns:\fP
.RS 4
Whether this object is less than target 
.RE
.PP

.SS "auto toString () const \-> std::string"

.PP
Convert the \fBTravel\fP to String\&. Have of form of tab and enter delimeters for Excel\&. 
.PP
.PP
.nf
 {$uid1}    {$x}    {$y} 
.fi
.PP

.br
 
.PP
.nf
 {$uid2}   {$x}    {$y} 
.fi
.PP

.br
 
.PP
.nf
 {$uid3}   {$x}    {$y} 
.fi
.PP

.br
 \&.\&.\&.
.PP
\fBReturns:\fP
.RS 4
A string can represent the \fBTravel\fP 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "double distance\fC [private]\fP"

.PP
Estimated hours to move\&. A variable for avoiding duplicated calculation 
.PP
\fBSee also:\fP
.RS 4
\fBcalcDistance()\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Samchon Framework for CPP from the source code\&.
