.TH "IEntityPtrGroup< _Container >" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IEntityPtrGroup< _Container > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IEntityPtrGroup\&.hpp>\fP
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename _Container>class samchon::protocol::IEntityPtrGroup< _Container >"
EntityPtrGroup is an \fBEntityGroup\fP having children \fBEntity\fP as their pointers\&.
.br
  

.SH "Author"
.PP 
Generated automatically by Doxygen for Samchon Framework for CPP from the source code\&.
