.TH "FTByteFile" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTByteFile \- A binary file\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FTByteFile\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFTByteFile\fP (\fBFTFolder\fP *)"
.br
.RI "\fIConstruct from parent folder\&. \fP"
.ti -1c
.RI "auto \fBgetData\fP () \-> \fBByteArray\fP"
.br
.RI "\fIGet binaray data of the file\&. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBByteArray\fP \fBdata\fP"
.br
.RI "\fIBinary data of the file\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A binary file\&. 

A file having data as binary\&.
.PP
 
.PP
\fBSee also:\fP
.RS 4
\fBsamchon::library\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Jeongho Nam 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBFTByteFile\fP (\fBFTFolder\fP *)"

.PP
Construct from parent folder\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfolder\fP Belonged folder 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Samchon Framework for CPP from the source code\&.
