.TH "FTFolder" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTFolder \- A folder\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FTFolder\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFTFolder\fP (\fBFTFactory\fP *, \fBFTFolder\fP *)"
.br
.RI "\fIConstruct from factory and parent folder\&. \fP"
.ti -1c
.RI "virtual auto \fBtoXML\fP () const  \-> std::shared_ptr< \fBlibrary::XML\fP > override"
.br
.RI "\fIGet an \fBXML\fP object represents the Entity\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual auto \fBCHILD_TAG\fP () const  \-> std::string override"
.br
.RI "\fIA tag name of children\&. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBFTFactory\fP * \fBfactory\fP"
.br
.RI "\fIFactory instance for creating sub files\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A folder\&. 

A folder object has recursive and hierarchical relationship\&.
.PP
 
.PP
\fBSee also:\fP
.RS 4
\fBsamchon::library\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Jeongho Nam 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBFTFolder\fP (\fBFTFactory\fP * factory, \fBFTFolder\fP * parent)"

.PP
Construct from factory and parent folder\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfactory\fP Factory instance 
.br
\fIparent\fP Parent folder that this folder is belonged to 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "auto CHILD_TAG () const \->  std::string\fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
A tag name of children\&. < TAG>
.br
      <CHILD_TAG />
.br
      <CHILD_TAG />
.br
 </TAG> 
.PP
Implements \fBIEntityGroup\fP\&.
.SS "auto toXML () const \-> std::shared_ptr<\fBlibrary::XML\fP>\fC [override]\fP, \fC [virtual]\fP"

.PP
Get an \fBXML\fP object represents the Entity\&. Returns an \fBXML\fP object that can represents the Entity containing member variables into properties\&. 
.PP
A member variable (not object, but atomic value like number, string or date) is categorized as a property within the framework of entity side\&. Thus, when overriding a \fBtoXML()\fP method and archiving member variables to an \fBXML\fP object to return, puts each variable to be a property belongs to only an \fBXML\fP object\&. 
.PP
Don't archive the member variable of atomic value to \fBXML::value\fP causing enormouse creation of \fBXML\fP objects to number of member variables\&. An Entity must be represented by only an \fBXML\fP instance (tag)\&. 
.PP
Standard Usage  Non-standard usage abusing value   <memberList>
.br
      <member id='jhnam88' name='Jeongho+Nam' birthdate='1988-03-11' />
.br
      <member id='master' name='Administartor' birthdate='2011-07-28' />
.br
 </memberList>  <member>
.br
      <id>jhnam88</id>
.br
      <name>Jeongho+Nam</name>
.br
      <birthdate>1988-03-11</birthdate>
.br
 </member>   
.PP
\fBReturns:\fP
.RS 4
An \fBXML\fP object representing the Entity\&. 
.RE
.PP

.PP
Reimplemented from \fBFTInstance\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Samchon Framework for CPP from the source code\&.
