.TH "ChatUser" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChatUser \- An user in chat server\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ChatUser\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChatUser\fP (\fBprotocol::service::Server\fP *)"
.br
.RI "\fIConstruct from server\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual auto \fBcreateClient\fP () \-> \fBprotocol::service::Client\fP *override"
.br
.RI "\fIFactory method of a Client\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
An user in chat server\&. 

 
.PP
\fBAuthor:\fP
.RS 4
Jeongho Nam 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Samchon Framework for CPP from the source code\&.
