.TH "ChatService" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChatService \- A chat service\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ChatService\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChatService\fP (\fBprotocol::service::Client\fP *)"
.br
.RI "\fIConstruct from a client\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBChatRoom\fP * \fBroom\fP"
.br
.RI "\fIA chat room\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A chat service\&. 

A chat service about a chat room\&.
.PP
 
.PP
\fBAuthor:\fP
.RS 4
Jeongho Nam 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "\fBChatRoom\fP* room\fC [private]\fP"

.PP
A chat room\&. A chat room that related client is participating in\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Samchon Framework for CPP from the source code\&.
