.TH "Scheduler" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Scheduler \- A scheduler\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Scheduler\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScheduler\fP (std::shared_ptr< \fBTravel\fP >, const struct \fBGAParameters\fP &)"
.br
.RI "\fIConstruct from points and parameter of genetic algorithm\&. \fP"
.ti -1c
.RI "auto \fBoptimize\fP () \-> std::shared_ptr< \fBTravel\fP >"
.br
.RI "\fIDerive optimized schedule\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::shared_ptr< \fBTravel\fP > \fBtravel\fP"
.br
.RI "\fIA travel to optimize or optimized\&. \fP"
.ti -1c
.RI "struct \fBGAParameters\fP \fBgaParameters\fP"
.br
.RI "\fIParameters for Genetic-Algorithm\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A scheduler\&. 

\fBScheduler\fP deducts an optimal schdule(Travel) by genetic algorithm\&.
.PP
\fBAuthor:\fP
.RS 4
Jeongho Nam 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "auto optimize () \-> std::shared_ptr<\fBTravel\fP>"

.PP
Derive optimized schedule\&. 
.PP
\fBReturns:\fP
.RS 4
An optimized travel schedule\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Samchon Framework for CPP from the source code\&.
