.TH "FactorialGenerator" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FactorialGenerator \- Factorical case generator\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FactorialGenerator\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFactorialGenerator\fP (size_t \fBsize\fP)"
.br
.RI "\fIConstruct from size N\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Factorical case generator\&. 

n! = nPn 
.PP
 
.PP
\fBSee also:\fP
.RS 4
\fBsamchon::library\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Jeongho Nam 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBFactorialGenerator\fP (size_t size)"

.PP
Construct from size N\&. 
.PP
\fBParameters:\fP
.RS 4
\fIn\fP Size of elements of each case to be arranged\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Samchon Framework for CPP from the source code\&.
