.TH "PermutationGenerator" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PermutationGenerator \- A permutation case generator\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PermutationGenerator\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPermutationGenerator\fP (size_t \fBn\fP, size_t \fBr\fP)"
.br
.RI "\fIConstruct from size of N and R\&. \fP"
.ti -1c
.RI "virtual auto \fBoperator[]\fP (size_t) const  \-> std::vector< size_t > override"
.br
.RI "\fIGet x'th case\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A permutation case generator\&. 

nPr 
.PP
 
.PP
\fBSee also:\fP
.RS 4
\fBsamchon::library\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Jeongho Nam 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBPermutationGenerator\fP (size_t n, size_t r)"

.PP
Construct from size of N and R\&. 
.PP
\fBParameters:\fP
.RS 4
\fIn\fP Size of candidates 
.br
\fIr\fP Size of elements of each case 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "auto operator[] (size_t) const \->  std::vector< size_t >\fC [override]\fP, \fC [virtual]\fP"

.PP
Get x'th case\&. 
.PP
\fBReturns:\fP
.RS 4
The row of the x'th in combined permuation case 
.RE
.PP

.PP
Implements \fBCaseGenerator\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Samchon Framework for CPP from the source code\&.
