.TH "Product" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Product \- A product, merchandise\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Product\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProduct\fP (const std::string &\fBname\fP, int \fBprice\fP, int \fBvolume\fP, int \fBweight\fP)"
.br
.RI "\fIConstruct from arguments\&. \fP"
.ti -1c
.RI "virtual auto \fBtoString\fP () const  \-> std::string override"
.br
.RI "\fIReturn a string represents the \fBInstance\fP\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A product, merchandise\&. 

A merchandise with its price, volume and weight\&. 
.PP
 
.PP
\fBAuthor:\fP
.RS 4
Jeongho Nam 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBProduct\fP (const std::string & name, int price, int volume, int weight)"

.PP
Construct from arguments\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP Name of a product can be an identifier 
.br
\fIprice\fP Price of the product 
.br
\fIvolume\fP Volume of the product 
.br
\fIweight\fP Weight of the product 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Samchon Framework for CPP from the source code\&.
