.TH "ProgressEvent" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProgressEvent \- \fBEvent\fP representing a progress\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ProgressEvent\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProgressEvent\fP (\fBEventDispatcher\fP *, size_t, size_t)"
.br
.RI "\fIConstruct from source and progress\&. \fP"
.ti -1c
.RI "auto \fBgetNumerator\fP () const  \-> size_t"
.br
.RI "\fIGet numerator, number of current progress\&. \fP"
.ti -1c
.RI "auto \fBgetDenominator\fP () const  \-> size_t"
.br
.RI "\fIGet denominator, number of total progress\&. \fP"
.ti -1c
.RI "auto \fBgetPercent\fP () const  \-> double"
.br
.RI "\fIGet percentage of the progress\&. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "size_t \fBnumerator\fP"
.br
.RI "\fIThe number of current progress\&. \fP"
.ti -1c
.RI "size_t \fBdenominator\fP"
.br
.RI "\fIThe number of total progress\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBEvent\fP representing a progress\&. 


.PP
\fB[Inherited]\fP
.RS 4

.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBProgressEvent\fP (\fBEventDispatcher\fP * source, size_t numerator, size_t denominator)"

.PP
Construct from source and progress\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsource\fP Source of the event; who made the event 
.br
\fInumerator\fP The number of current progress 
.br
\fIdenominator\fP The number of total progress
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIexception\fP denominator is zero 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "size_t denominator\fC [protected]\fP"

.PP
The number of total progress\&. 
.PP
\fBWarning:\fP
.RS 4
denominator cannot be zero 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Samchon Framework for CPP from the source code\&.
