.TH "FTTextFile" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTTextFile \- A text file\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FTTextFile\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFTTextFile\fP (\fBFTFolder\fP *)"
.br
.RI "\fIConstruct from parent folder\&. \fP"
.ti -1c
.RI "auto \fBgetData\fP () const  \-> std::string"
.br
.RI "\fIGet string content\&. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fBdata\fP"
.br
.RI "\fIText recorded in the file\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A text file\&. 

A file having data as text\&.
.PP
 
.PP
\fBSee also:\fP
.RS 4
\fBsamchon::library\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Jeongho Nam 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBFTTextFile\fP (\fBFTFolder\fP *)"

.PP
Construct from parent folder\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfolder\fP Belonged folder 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Samchon Framework for CPP from the source code\&.
