.TH "ListService" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ListService \- A list service of chat rooms\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ListService\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBListService\fP (\fBprotocol::service::Client\fP *)"
.br
.RI "\fIConstruct from a client\&. \fP"
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBcreateRoom\fP (const std::string &)"
.br
.RI "\fICreate a chat room\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A list service of chat rooms\&. 

 
.PP
\fBAuthor:\fP
.RS 4
Jeongho Nam 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void createRoom (const std::string &)\fC [private]\fP"

.PP
Create a chat room\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP Name of the candidate room to create\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Samchon Framework for CPP from the source code\&.
