.TH "FlashPolicyServer" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlashPolicyServer \- A flash policy server\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FlashPolicyServer\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFlashPolicyServer\fP ()"
.br
.RI "\fIDefault constructor\&. \fP"
.ti -1c
.RI "\fBFlashPolicyServer\fP (std::shared_ptr< \fBlibrary::XML\fP >)"
.br
.RI "\fIConstruct from custom policy\&. \fP"
.ti -1c
.RI "void \fBopenServer\fP ()"
.br
.RI "\fIOpen server\&. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::shared_ptr< \fBlibrary::XML\fP > \fBpolicy\fP"
.br
.RI "\fIcross-domain-policy \fP"
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBaccept\fP (Socket *)"
.br
.RI "\fIAccept client\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A flash policy server\&. 

\fBFlashPolicyServer\fP is a policy server replying cross-domain-policy to flash clients\&.
.PP
\fBAuthor:\fP
.RS 4
Jeongho Nam 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBFlashPolicyServer\fP ()"

.PP
Default constructor\&. The cross-domain-policy is to accept all, any client\&. 
.SS "\fBFlashPolicyServer\fP (std::shared_ptr< \fBlibrary::XML\fP >)"

.PP
Construct from custom policy\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpolicy\fP Custom cross-domain-policy to adjust 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void accept (Socket *)\fC [private]\fP"

.PP
Accept client\&. Accepts flash client and replies cross-domain-policy 

.SH "Author"
.PP 
Generated automatically by Doxygen for Samchon Framework for CPP from the source code\&.
