.TH "InvokeHistoryArray" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InvokeHistoryArray \- An array of \fBInvokeHistory\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <InvokeHistoryArray\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInvokeHistoryArray\fP ()"
.br
.RI "\fIDefault Constructor\&. \fP"
.ti -1c
.RI "virtual auto \fBTAG\fP () const  \-> std::string"
.br
.RI "\fIA tag name when represented by XML\&. \fP"
.ti -1c
.RI "virtual auto \fBCHILD_TAG\fP () const  \-> std::string"
.br
.RI "\fIA tag name of children\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual auto \fBcreateChild\fP (std::shared_ptr< \fBlibrary::XML\fP >) \-> \fBInvokeHistory\fP *override"
.br
.RI "\fIFactory method of a child \fBEntity\fP\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
An array of \fBInvokeHistory\fP\&. 


.PP
\fBAuthor:\fP
.RS 4
Jeongho Nam 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "auto createChild (std::shared_ptr< \fBlibrary::XML\fP >) \->  \fBInvokeHistory\fP *override\fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Factory method of a child \fBEntity\fP\&. \fBEntityGroup::createChild()\fP is a factory method creating a new child \fBEntity\fP which is belonged to the \fBEntityGroup\fP\&. This method is called by \fBEntityGroup::construct()\fP\&. The children construction methods \fBEntity::construct()\fP will be called by abstract method of the \fBEntityGroup::construct()\fP\&. 
.PP
\fBReturns:\fP
.RS 4
A new child \fBEntity\fP belongs to \fBEntityGroup\fP\&. 
.RE
.PP

.PP
Implements \fBEntityGroup< _Container, _ETy, _Ty >\fP\&.
.PP
Reimplemented in \fBPRInvokeHistoryArray\fP\&.
.SS "auto TAG () const \->  std::string\fC [virtual]\fP"

.PP
A tag name when represented by XML\&. 
.PP
\fBReturns:\fP
.RS 4
A tag name 
.RE
.PP

.PP
Implements \fBEntity\fP\&.
.SS "auto CHILD_TAG () const \->  std::string\fC [virtual]\fP"

.PP
A tag name of children\&. < TAG>
.br
      <CHILD_TAG />
.br
      <CHILD_TAG />
.br
 </TAG> 
.PP
Implements \fBIEntityGroup\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Samchon Framework for CPP from the source code\&.
