.TH "IOperator< _Ty >" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IOperator< _Ty > \- Interface for comparision operator\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IOperator\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIOperator\fP ()"
.br
.RI "\fIDefault Constructor\&. \fP"
.ti -1c
.RI "virtual auto \fBoperator<\fP (const \fBIOperator\fP &) const  \-> bool=0"
.br
.RI "\fILess\&. \fP"
.ti -1c
.RI "virtual auto \fBoperator==\fP (const \fBIOperator\fP &) const  \-> bool=0"
.br
.RI "\fIEqual\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Ty>class samchon::library::IOperator< _Ty >"
Interface for comparision operator\&. 

\fBIOperator\fP is a template class makes enalbe to realizing all compare operators by only overriding operator< and operator== methods\&. 
.PP
.PD 0
.IP "\(bu" 2
[!=] -> [NOT ==] 
.IP "\(bu" 2
[<=] -> [< OR ==] 
.IP "\(bu" 2
[>] -> [NOT < AND NOT ==] 
.IP "\(bu" 2
[>=] -> [NOT <]
.PP
.PP
Methods operator< and operator== are abstract\&. Overrides them\&. 
.PP
\fBNote:\fP
.RS 4
If you want to realize all comparison operators without inheritance and specifying clear type of parameter, you can use following macros instead\&.
.RE
.PP
.PD 0
.IP "\(bu" 2
OPERATOR_METHODS_INLINE(_Ty) 
.IP "\(bu" 2
OPERATOR_METHODS_HEADER(_Ty) 
.IP "\(bu" 2
OPERATOR_METHODS_BODY(_Class, _Ty)
.PP
\fBSee also:\fP
.RS 4
\fBsamchon::library\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Jeongho Nam 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "virtual auto operator< (const \fBIOperator\fP< _Ty > &) const \->  bool\fC [pure virtual]\fP"

.PP
Less\&. Overrides method less\&.
.PP
\fBParameters:\fP
.RS 4
\fIobj\fP The object to compare\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The object is less than this\&. 
.RE
.PP

.SS "virtual auto operator== (const \fBIOperator\fP< _Ty > &) const \->  bool\fC [pure virtual]\fP"

.PP
Equal\&. Overrides methods equal\&.
.PP
\fBParameters:\fP
.RS 4
\fIobj\fP The object to compare\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The object is equal with this\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Samchon Framework for CPP from the source code\&.
