.TH "HTTPLoader" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HTTPLoader \- A http, web-page loader\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <HTTPLoader\&.hpp>\fP
.SH "Detailed Description"
.PP 
A http, web-page loader\&. 

 
.PP
\fBNote:\fP
.RS 4
Depreciated
.RE
.PP
\fBSee also:\fP
.RS 4
\fBsamchon::library\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Jeongho Nam 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Samchon Framework for CPP from the source code\&.
