.TH "Packer" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Packer \- A packer planning the best packaging\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Packer\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPacker\fP (std::vector< \fBProduct\fP > *, std::vector< \fBWrapper\fP > *)"
.br
.RI "\fIConstruct from products and wrapper\&. \fP"
.ti -1c
.RI "\fBPacker\fP (const \fBPacker\fP &)"
.br
.RI "\fICopy Constructor\&. \fP"
.ti -1c
.RI "void \fBoptimize\fP ()"
.br
.RI "\fIFind the best packaging method\&. \fP"
.ti -1c
.RI "auto \fBcalcPrice\fP () const  \-> int"
.br
.RI "\fICalculate price of the wrappers\&. \fP"
.ti -1c
.RI "auto \fBtoString\fP () const  \-> std::string"
.br
.RI "\fIReturn a string represents an packaging method\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBProduct\fP > * \fBproductArray\fP"
.br
.RI "\fIProdcut(s) to package in some Wrapper(s) \fP"
.ti -1c
.RI "std::vector< \fBWrapper\fP > * \fBwrapperArray\fP"
.br
.RI "\fIType of Wrapper(s) to be used for packaging\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A packer planning the best packaging\&. 

Retrieves the solution of packaging by combination permuation and factorial case\&. 
.PP
 
.PP
\fBWarning:\fP
.RS 4
.RE
.PP
Be careful about number of products and wrappers\&. 
.PP
The time complexity of \fBPacker\fP overs O(m^n)\&. Elapsed time of calculation increases enourmously\&. Do not use \fBPacker\fP if the digits of number of products or wrappers overs 2\&. 
.PP
\fBAuthor:\fP
.RS 4
Jeongho Nam 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBPacker\fP (std::vector< \fBProduct\fP > * productArray, std::vector< \fBWrapper\fP > * wrapperArray)"

.PP
Construct from products and wrapper\&. 
.PP
\fBParameters:\fP
.RS 4
\fIproductArray\fP Product(s) to input some \fBWrapper\fP 
.br
\fIwrapperArray\fP Type of Wrapper(s) to be used 
.RE
.PP

.SS "\fBPacker\fP (const \fBPacker\fP & packer)"

.PP
Copy Constructor\&. Copy constructor of \fBPacker\fP does not copy children items\&. 
.PP
Only copies member variables(productArray, wrapperArray) of \fBPacker\fP's\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Samchon Framework for CPP from the source code\&.
