.TH "Instance" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Instance \- A physical instance\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Instance\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInstance\fP (const std::string &\fBname\fP, int \fBprice\fP, int \fBvolume\fP, int \fBweight\fP)"
.br
.RI "\fIConstruct from instance\&. \fP"
.ti -1c
.RI "auto \fBgetName\fP () const  \-> std::string"
.br
.RI "\fIGet name\&. \fP"
.ti -1c
.RI "auto \fBgetPrice\fP () const  \-> int"
.br
.RI "\fIGet price\&. \fP"
.ti -1c
.RI "auto \fBgetVolume\fP () const  \-> int"
.br
.RI "\fIGet volume\&. \fP"
.ti -1c
.RI "auto \fBgetWeight\fP () const  \-> int"
.br
.RI "\fIGet weight\&. \fP"
.ti -1c
.RI "virtual auto \fBtoString\fP () const  \-> std::string"
.br
.RI "\fIReturn a string represents the \fBInstance\fP\&. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fBname\fP"
.br
.RI "\fIName represent the \fBInstance\fP\&. \fP"
.ti -1c
.RI "int \fBprice\fP"
.br
.RI "\fIPrice of an instance -> 1,000 won\&. \fP"
.ti -1c
.RI "int \fBvolume\fP"
.br
.RI "\fIVolume of an instance -> 130 cm^3\&. \fP"
.ti -1c
.RI "int \fBweight\fP"
.br
.RI "\fIWeight of an instance -> 1,200 g\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A physical instance\&. 

A physical instance having its own name, price, volume and weight\&. 
.PP
 
.PP
\fBAuthor:\fP
.RS 4
Jeongho Nam 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBInstance\fP (const std::string & name, int price, int volume, int weight)"

.PP
Construct from instance\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP Name of the instance 
.br
\fIprice\fP Price of the instance 
.br
\fIvolume\fP Volume of the instance 
.br
\fIweight\fP Weight of the instance 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Samchon Framework for CPP from the source code\&.
