.TH "samchon::example::tsp" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
samchon::example::tsp \- A packer with number of wrapper type and products\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBGAParameters\fP"
.br
.RI "\fIParameters for Genetic-Algorithm\&. \fP"
.ti -1c
.RI "class \fBGeometryPoint\fP"
.br
.RI "\fIA geometry coordinates (point) \fP"
.ti -1c
.RI "class \fBScheduler\fP"
.br
.RI "\fIA scheduler\&. \fP"
.ti -1c
.RI "class \fBTravel\fP"
.br
.RI "\fIRepresent a travel containning Point(s) \fP"
.in -1c
.SH "Detailed Description"
.PP 
A packer with number of wrapper type and products\&. 

Traveling Salesman Problem Solver\&.
.PP
Retrieves the solution of packaging by combination permuation and factorial case\&.
.PP
 
.PP
 
.PP
\fBSee also:\fP
.RS 4
\fBlibrary::CaseGenerator\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Jeongho Nam
.RE
.PP
Deducts an optimal traveling scheduel by genetic algorithm\&.
.PP
 
.PP
 
.PP
\fBAuthor:\fP
.RS 4
Jeongho Nam 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Samchon Framework for CPP from the source code\&.
