.TH "IEntityChain" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IEntityChain \- A chain of entity\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IEntityChain\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIEntityChain\fP (\fBEntity\fP *)"
.br
.RI "\fIDefault Constructor\&. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBEntity\fP * \fBentity\fP"
.br
.RI "\fIAn entity related with the chain\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A chain of entity\&. 

\fBIEntityChain\fP is an interface takes role of control about an entity by chain of responsibliy pattern\&. It's suitable for a supplementary processes are required on an entity like calculation or historical regression about an entity\&. 
.PP
 
.PP
\fBSee also:\fP
.RS 4
\fBsamchon::protocol\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Jeongho Nam 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBIEntityChain\fP (\fBEntity\fP * entity)"

.PP
Default Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIentity\fP A related entity\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Samchon Framework for CPP from the source code\&.
