.TH "PRInvokeHistory" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PRInvokeHistory \- A reported history of an \fBInvoke\fP message\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PRInvokeHistory\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPRInvokeHistory\fP ()"
.br
.RI "\fIDefault Constructor\&. \fP"
.ti -1c
.RI "\fBPRInvokeHistory\fP (std::shared_ptr< \fBInvoke\fP >)"
.br
.RI "\fIConstruct from an \fBInvoke\fP message\&. \fP"
.ti -1c
.RI "virtual void \fBconstruct\fP (std::shared_ptr< \fBlibrary::XML\fP >) override"
.br
.RI "\fIConstruct data of the \fBEntity\fP from an XML object\&. \fP"
.ti -1c
.RI "auto \fBgetIndex\fP () const  \-> size_t"
.br
.RI "\fIGet index\&. \fP"
.ti -1c
.RI "auto \fBgetSize\fP () const  \-> size_t"
.br
.RI "\fIGet size\&. \fP"
.ti -1c
.RI "virtual auto \fBtoXML\fP () const  \-> std::shared_ptr< \fBlibrary::XML\fP > override"
.br
.RI "\fIGet an XML object represents the \fBEntity\fP\&. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "size_t \fBindex\fP"
.br
.RI "\fIStart index\&. \fP"
.ti -1c
.RI "size_t \fBsize\fP"
.br
.RI "\fIThe Size\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A reported history of an \fBInvoke\fP message\&. 


.PP
\fB[Inherited]\fP
.RS 4

.RE
.PP
\fBInvokeHistory\fP is a class for reporting history log of an \fBInvoke\fP message with elapsed time from a slave to its master\&.
.PP
With the elapsed time, consumed time for a process of handling the \fBInvoke\fP message, \fBInvokeHistory\fP is reported to the master\&. The master utilizies the elapsed time to estimating performances of each slave system\&. With the estimated performan index, master retrives the optimal solution of distributing processes\&. 
.PP
 
.PP
\fBSee also:\fP
.RS 4
\fBsamchon::protocol\fP 
.PP
\fBsamchon::protocol::master\fP 
.PP
\fBsamchon::protocol::slave\fP
.RE
.PP
\fBAuthor:\fP
.RS 4
Jeongho Nam 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBPRInvokeHistory\fP (std::shared_ptr< \fBInvoke\fP >)"

.PP
Construct from an \fBInvoke\fP message\&. \fBInvokeHistory\fP does not archive entire \fBInvoke\fP message, only archives its listener\&. 
.PP
\fBParameters:\fP
.RS 4
\fIinvoke\fP A message to archive its history log 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void construct (std::shared_ptr< \fBlibrary::XML\fP >)\fC [override]\fP, \fC [virtual]\fP"

.PP
Construct data of the \fBEntity\fP from an XML object\&. Overrides the \fBconstruct()\fP method and fetch data of member variables from the XML\&. 
.PP
By recommended guidance, data representing member variables are contained in properties of the put XML object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIxml\fP An xml used to construct data of entity 
.RE
.PP

.PP
Reimplemented from \fBInvokeHistory\fP\&.
.SS "auto toXML () const \-> std::shared_ptr<\fBlibrary::XML\fP>\fC [override]\fP, \fC [virtual]\fP"

.PP
Get an XML object represents the \fBEntity\fP\&. Returns an XML object that can represents the \fBEntity\fP containing member variables into properties\&. 
.PP
A member variable (not object, but atomic value like number, string or date) is categorized as a property within the framework of entity side\&. Thus, when overriding a \fBtoXML()\fP method and archiving member variables to an XML object to return, puts each variable to be a property belongs to only an XML object\&. 
.PP
Don't archive the member variable of atomic value to XML::value causing enormouse creation of XML objects to number of member variables\&. An \fBEntity\fP must be represented by only an XML instance (tag)\&. 
.PP
Standard Usage  Non-standard usage abusing value   <memberList>
.br
      <member id='jhnam88' name='Jeongho+Nam' birthdate='1988-03-11' />
.br
      <member id='master' name='Administartor' birthdate='2011-07-28' />
.br
 </memberList>  <member>
.br
      <id>jhnam88</id>
.br
      <name>Jeongho+Nam</name>
.br
      <birthdate>1988-03-11</birthdate>
.br
 </member>   
.PP
\fBReturns:\fP
.RS 4
An XML object representing the \fBEntity\fP\&. 
.RE
.PP

.PP
Reimplemented from \fBInvokeHistory\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Samchon Framework for CPP from the source code\&.
