.TH "IEntityGroup" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IEntityGroup \- An iternface for entity group\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IEntityGroup\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIEntityGroup\fP ()"
.br
.RI "\fIDefault Constructor\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual auto \fBCHILD_TAG\fP () const  \-> std::string=0"
.br
.RI "\fIA tag name of children\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
An iternface for entity group\&. 

\fBIEntityGroup\fP is an interface for a container of entity\&. It does not have any special role or function\&. The IEntityGorup is only for discriminate an entity is single instance or gorup of entity\&. 
.PP
.PD 0
.IP "\(bu" 2
Group of entity is divided into \fBEntityArray\fP and \fBEntityGroup\fP\&.  
.PD 0

.IP "  \(bu" 4
Even they are template classes so that cannot be discriminated globally\&.  
.PP

.IP "\(bu" 2
dynamic_cast<IEntityGroup>(\fIsome entity instance\fP)  
.PD 0

.IP "  \(bu" 4
If true then, it's not single entity instance, but group of entity\&.  
.IP "  \(bu" 4
False then, it's a single instance\&.  
.PP

.PP
.PP
\fBAuthor:\fP
.RS 4
Jeongho Nam 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "virtual auto CHILD_TAG () const \->  std::string\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
A tag name of children\&. < TAG>
.br
      <CHILD_TAG />
.br
      <CHILD_TAG />
.br
 </TAG> 
.PP
Implemented in \fBInvoke\fP, \fBNTCriteria\fP, \fBExternalSystemArray\fP, \fBExternalSystem\fP, \fBNTParameter\fP, \fBChatRoomArray\fP, \fBInvokeHistoryArray\fP, \fBNTParameterArray\fP, and \fBFTFolder\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Samchon Framework for CPP from the source code\&.
