.TH "INTExplore" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
INTExplore \- An interface for exploration\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <INTExplore\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBINTExplore\fP ()"
.br
.RI "\fIDefault Constructor\&. \fP"
.ti -1c
.RI "virtual void \fBconstruct\fP (std::shared_ptr< \fBlibrary::XML\fP >)"
.br
.RI "\fIConstruct data of the Entity from an XML object\&. \fP"
.ti -1c
.RI "auto \fBgetMinimum\fP () const  \-> double"
.br
.RI "\fIGet minimum\&. \fP"
.ti -1c
.RI "auto \fBgetMaximum\fP () const  \-> double"
.br
.RI "\fIGet maximum\&. \fP"
.ti -1c
.RI "auto \fBgetSection\fP () const  \-> unsigned int"
.br
.RI "\fIGet section\&. \fP"
.ti -1c
.RI "auto \fBgetPrecision\fP () const  \-> int"
.br
.RI "\fIGet precision\&. \fP"
.ti -1c
.RI "virtual auto \fBtoXML\fP () const  \-> std::shared_ptr< \fBlibrary::XML\fP >"
.br
.RI "\fIGet an XML object represents the Entity\&. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "double \fBminimum\fP"
.br
.RI "\fIMinimum value\&. \fP"
.ti -1c
.RI "double \fBmaximum\fP"
.br
.RI "\fIMaximum value\&. \fP"
.ti -1c
.RI "unsigned int \fBsection\fP"
.br
.RI "\fISection number of exploration\&. \fP"
.ti -1c
.RI "int \fBprecision\fP"
.br
.RI "\fITarget precision: 10\*{precision\*}  \fP"
.in -1c
.SH "Detailed Description"
.PP 
An interface for exploration\&. 

 
.PP
\fBINTExplore\fP is an interface containing some parameters for grid optimization method\&. 
.PP
 
.PP
\fBSee also:\fP
.RS 4
\fBsamchon::namtree\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Jeongho Nam 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void construct (std::shared_ptr< \fBlibrary::XML\fP >)\fC [virtual]\fP"

.PP
Construct data of the Entity from an XML object\&. Overrides the \fBconstruct()\fP method and fetch data of member variables from the XML\&. 
.PP
By recommended guidance, data representing member variables are contained in properties of the put XML object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIxml\fP An xml used to construct data of entity 
.RE
.PP

.PP
Implements \fBEntity\fP\&.
.PP
Reimplemented in \fBNTFile\fP, and \fBNTParameter\fP\&.
.SS "auto toXML () const \-> std::shared_ptr<\fBlibrary::XML\fP>\fC [virtual]\fP"

.PP
Get an XML object represents the Entity\&. Returns an XML object that can represents the Entity containing member variables into properties\&. 
.PP
A member variable (not object, but atomic value like number, string or date) is categorized as a property within the framework of entity side\&. Thus, when overriding a \fBtoXML()\fP method and archiving member variables to an XML object to return, puts each variable to be a property belongs to only an XML object\&. 
.PP
Don't archive the member variable of atomic value to XML::value causing enormouse creation of XML objects to number of member variables\&. An Entity must be represented by only an XML instance (tag)\&. 
.PP
Standard Usage  Non-standard usage abusing value   <memberList>
.br
      <member id='jhnam88' name='Jeongho+Nam' birthdate='1988-03-11' />
.br
      <member id='master' name='Administartor' birthdate='2011-07-28' />
.br
 </memberList>  <member>
.br
      <id>jhnam88</id>
.br
      <name>Jeongho+Nam</name>
.br
      <birthdate>1988-03-11</birthdate>
.br
 </member>   
.PP
\fBReturns:\fP
.RS 4
An XML object representing the Entity\&. 
.RE
.PP

.PP
Reimplemented from \fBEntity\fP\&.
.PP
Reimplemented in \fBNTFile\fP, and \fBNTParameter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Samchon Framework for CPP from the source code\&.
