.TH "ChatServer" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChatServer \- A chat server\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ChatServer\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChatServer\fP ()"
.br
.RI "\fIDefault Constructor\&. \fP"
.ti -1c
.RI "auto \fBgetChatRoomArray\fP () const  \-> \fBChatRoomArray\fP *"
.br
.RI "\fIGet chat room list\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual auto \fBPORT\fP () const  \-> int override"
.br
.RI "\fIPort number of the server\&. \fP"
.ti -1c
.RI "virtual auto \fBcreateUser\fP () \-> \fBprotocol::service::User\fP *override"
.br
.RI "\fIFactory method of User\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBChatRoomArray\fP * \fBroomArray\fP"
.br
.RI "\fIA manager of chat rooms\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A chat server\&. 

 
.PP
\fBAuthor:\fP
.RS 4
Jeongho Nam 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Samchon Framework for CPP from the source code\&.
