.TH "NTParameter" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NTParameter \- A metadata of a parameter in a function\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NTParameter\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNTParameter\fP ()"
.br
.RI "\fIDefault Constructor\&. \fP"
.ti -1c
.RI "virtual void \fBconstruct\fP (std::shared_ptr< \fBlibrary::XML\fP >) override"
.br
.RI "\fIConstruct data of the Entity from an XML object\&. \fP"
.ti -1c
.RI "virtual auto \fBkey\fP () const  \-> std::string override"
.br
.RI "\fIGet a key that can identify the Entity uniquely\&. \fP"
.ti -1c
.RI "auto \fBgetName\fP () const  \-> std::string"
.br
.RI "\fIGet name\&. \fP"
.ti -1c
.RI "auto \fBgetInitialValue\fP () const  \-> double"
.br
.RI "\fIGet initial, default vlaue\&. \fP"
.ti -1c
.RI "virtual auto \fBTAG\fP () const  \-> std::string override"
.br
.RI "\fIA tag name when represented by XML\&. \fP"
.ti -1c
.RI "virtual auto \fBCHILD_TAG\fP () const  \-> std::string override"
.br
.RI "\fIA tag name of children\&. \fP"
.ti -1c
.RI "virtual auto \fBtoXML\fP () const  \-> std::shared_ptr< \fBlibrary::XML\fP > override"
.br
.RI "\fIGet an XML object represents the Entity\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual auto \fBcreateChild\fP (std::shared_ptr< \fBlibrary::XML\fP >) \-> \fBNTParameterDetermined\fP *override"
.br
.RI "\fIFactory method of a child Entity\&. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fBname\fP"
.br
.RI "\fIName of a paremeter\&. \fP"
.ti -1c
.RI "double \fBinitialValue\fP"
.br
.RI "\fIAn initial, default value\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A metadata of a parameter in a function\&. 

\fBNTParameter\fP is a class containing metadata of a parameter which is belonged to a class, metadata of a function, \fBNTFile\fP\&. Between the \fBNTFile\fP and NTParameter(s), there's a associate relationship\&. 
.PP
 
.PP
\fBSee also:\fP
.RS 4
\fBsamchon::namtree\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Jeongho Nam 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void construct (std::shared_ptr< \fBlibrary::XML\fP >)\fC [override]\fP, \fC [virtual]\fP"

.PP
Construct data of the Entity from an XML object\&. Overrides the \fBconstruct()\fP method and fetch data of member variables from the XML\&. 
.PP
By recommended guidance, data representing member variables are contained in properties of the put XML object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIxml\fP An xml used to construct data of entity 
.RE
.PP

.PP
Reimplemented from \fBINTExplore\fP\&.
.SS "auto createChild (std::shared_ptr< \fBlibrary::XML\fP >) \->  \fBNTParameterDetermined\fP *override\fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Factory method of a child Entity\&. EntityGroup::createChild() is a factory method creating a new child Entity which is belonged to the EntityGroup\&. This method is called by EntityGroup::construct()\&. The children construction methods Entity::construct() will be called by abstract method of the EntityGroup::construct()\&. 
.PP
\fBReturns:\fP
.RS 4
A new child Entity belongs to EntityGroup\&. 
.RE
.PP

.PP
Implements \fBEntityGroup< _Container, _ETy, _Ty >\fP\&.
.SS "auto key () const \-> std::string\fC [override]\fP, \fC [virtual]\fP"

.PP
Get a key that can identify the Entity uniquely\&. If identifier of the Entity is not atomic value, returns a string represents the composite identifier\&. If identifier of the Entity is not string, converts the identifier to string and returns the string\&. 
.PP
\fBReturns:\fP
.RS 4
An identifier 
.RE
.PP

.PP
Reimplemented from \fBEntity\fP\&.
.SS "auto TAG () const \->  std::string\fC [override]\fP, \fC [virtual]\fP"

.PP
A tag name when represented by XML\&. 
.PP
\fBReturns:\fP
.RS 4
A tag name 
.RE
.PP

.PP
Implements \fBEntity\fP\&.
.SS "auto CHILD_TAG () const \->  std::string\fC [override]\fP, \fC [virtual]\fP"

.PP
A tag name of children\&. < TAG>
.br
      <CHILD_TAG />
.br
      <CHILD_TAG />
.br
 </TAG> 
.PP
Implements \fBIEntityGroup\fP\&.
.SS "auto toXML () const \-> std::shared_ptr<\fBlibrary::XML\fP>\fC [override]\fP, \fC [virtual]\fP"

.PP
Get an XML object represents the Entity\&. Returns an XML object that can represents the Entity containing member variables into properties\&. 
.PP
A member variable (not object, but atomic value like number, string or date) is categorized as a property within the framework of entity side\&. Thus, when overriding a \fBtoXML()\fP method and archiving member variables to an XML object to return, puts each variable to be a property belongs to only an XML object\&. 
.PP
Don't archive the member variable of atomic value to XML::value causing enormouse creation of XML objects to number of member variables\&. An Entity must be represented by only an XML instance (tag)\&. 
.PP
Standard Usage  Non-standard usage abusing value   <memberList>
.br
      <member id='jhnam88' name='Jeongho+Nam' birthdate='1988-03-11' />
.br
      <member id='master' name='Administartor' birthdate='2011-07-28' />
.br
 </memberList>  <member>
.br
      <id>jhnam88</id>
.br
      <name>Jeongho+Nam</name>
.br
      <birthdate>1988-03-11</birthdate>
.br
 </member>   
.PP
\fBReturns:\fP
.RS 4
An XML object representing the Entity\&. 
.RE
.PP

.PP
Reimplemented from \fBINTExplore\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string name\fC [protected]\fP"

.PP
Name of a paremeter\&. The string label is identifier of a \fBNTParameter\fP\&. It must be unique\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Samchon Framework for CPP from the source code\&.
