.TH "samchon::example::chat_service" 3 "Mon Oct 26 2015" "Version 1.0.0" "Samchon Framework for CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
samchon::example::chat_service \- A chat service inherited from cloud service\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBChatClient\fP"
.br
.RI "\fIA client\&. \fP"
.ti -1c
.RI "class \fBChatMessage\fP"
.br
.RI "\fIA chat message\&. \fP"
.ti -1c
.RI "class \fBChatRoom\fP"
.br
.RI "\fIA chat room\&. \fP"
.ti -1c
.RI "class \fBChatRoomArray\fP"
.br
.RI "\fIA manager of chat rooms\&. \fP"
.ti -1c
.RI "class \fBChatServer\fP"
.br
.RI "\fIA chat server\&. \fP"
.ti -1c
.RI "class \fBChatService\fP"
.br
.RI "\fIA chat service\&. \fP"
.ti -1c
.RI "class \fBChatUser\fP"
.br
.RI "\fIAn user in chat server\&. \fP"
.ti -1c
.RI "class \fBListService\fP"
.br
.RI "\fIA list service of chat rooms\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A chat service inherited from cloud service\&. 

An example for realizing cloud service and using critical allocators\&. 
.PP
 
.PP
\fBAuthor:\fP
.RS 4
Jeongho Nam 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Samchon Framework for CPP from the source code\&.
