Samchon Framework for CPP: samchon::templates::service::Server Class Reference
samchon::templates::service::Server Class Reference abstract
#include <Server.hpp>
Public Member Functions
Server ()
virtual ~Server ()
auto has (const std::string &accountID) const -> bool
auto get (const std::string &accountID) const -> std::shared_ptr< User >
virtual void sendData (std::shared_ptr< protocol::Invoke >) override
virtual void replyData (std::shared_ptr< protocol::Invoke >)=0
Public Member Functions inherited from samchon::protocol::WebServer
WebServer ()
Public Member Functions inherited from samchon::protocol::Server
Server ()
virtual void open (int port)
virtual void close ()
Public Member Functions inherited from samchon::protocol::IProtocol
virtual void replyData (std::shared_ptr< Invoke >)=0
virtual void sendData (std::shared_ptr< Invoke >)=0
Protected Member Functions
virtual auto createUser () -> User *=0
Protected Member Functions inherited from samchon::protocol::Server
virtual void addClient (std::shared_ptr< ClientDriver >)=0
Private Member Functions
virtual void addClient (std::shared_ptr< protocol::ClientDriver >) final
Detailed Description
A cloud server.
The Server is an abstract server class, who can build a real-time cloud server, that is following the web-socket protocol. Extends this Server and related classes and overrides abstract methods under below. After the overridings, open this cloud server using the open() method.
Objects in composite relationship and their factory methods
User: Server.createUser()
Client: User.createClient()
Service: { Client.createService Client.createService()}
Invoke message chains; replyData
Server.replyData
User.replyData
Client.replyData
Service.replyData
Templates - Cloud Service
Author
Jeongho Nam http://samchon.org
Definition at line 48 of file Server.hpp.
Constructor & Destructor Documentation
Server::Server ()
Default Constructor.
Definition at line 17 of file Server_service.cpp.
Server::~Server () virtual
Default Destructor.
Reimplemented from samchon::protocol::Server.
Definition at line 22 of file Server_service.cpp.
References addClient(), createUser(), samchon::protocol::WebClientDriver::getSessionID(), samchon::library::RWMutex::readLock(), samchon::library::RWMutex::readUnlock(), sendData(), and samchon::library::UniqueReadLock::unlock().
Member Function Documentation
virtual auto samchon::templates::service::Server::createUser () -> User * protected pure virtual
Factory method creating User object.
Returns
A newly created User object.
Referenced by ~Server().
auto samchon::templates::service::Server::has (const std::string & accountID) const -> bool inline
Test wheter an User exists with the accountID.
Parameters
accountID Account id of User to find.
Returns
Exists or not.
Definition at line 95 of file Server.hpp.
References samchon::HashMap< Key, T, Hash, Pred, Alloc >::has().
auto samchon::templates::service::Server::get (const std::string & accountID) const -> std::shared_ptr<User> inline
Get an User object by its accountID.
Parameters
accountID Account id of User to get.
Returns
An User object.
Definition at line 106 of file Server.hpp.
References samchon::HashMap< Key, T, Hash, Pred, Alloc >::get().
virtual void samchon::templates::service::Server::sendData (std::shared_ptr< protocol::Invoke >) override virtual
Send an Invoke message.
Sends an Invoke message to all remote clients through the belonged User and Client objects. Sending the Invoke message to all remote clients, it's came true by passing through User.sendData(). And the User.sendData also pass through the Client.sendData().
 class protocol.service.Server
 {
     public sendData(invoke: Invoke): void
     {
         for (user: User in this)
             for (client: Client in user)
                 client.sendData(invoke);
     }
 }
Parameters
invoke Invoke message to send to all remote clients.
Referenced by ~Server().
virtual void samchon::templates::service::Server::replyData (std::shared_ptr< protocol::Invoke >) pure virtual
Handle a replied Invoke message.
The Server.replyData() is an abstract method that handling Invoke message that should be handled in the Server level. Overrides this replyData() method and defines what to do with the Invoke message in this Server level.
Parameters
invoke An invoke message to be handled in Server level.
virtual void samchon::templates::service::Server::addClient (std::shared_ptr< protocol::ClientDriver >) final private virtual
Add a newly connected remote client.
When a remote client connects to this cloud server, then Server queries the {WebClientDriver.getSessionID session id} of the remote client. If the {WebClientDriver.getSessionID session id} is new one, then creates a new User object.
At next, creates a Client object who represents the newly connected remote client and insert the Client object to the matched User object which is new or ordinary one following the {WebClientDriver.getSessionID session id}. At last, a Service object can be created with referencing the path.
List of objects can be created by this method.
User by createUser().
Client by User.createClient().
Service by Client.createService().
Parameters
driver A web communicator for remote client.
Referenced by ~Server().
The documentation for this class was generated from the following files:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/templates/service/Server.hpp
D:/OneDrive/Project/Samchon/framework/cpp/samchon/templates/service/Server_service.cpp