Samchon Framework for CPP: samchon::library::StringUtil Class Reference
samchon::library::StringUtil Class Reference
Utility class for string.
#include <StringUtil.hpp>
Static Public Member Functions
template<typename T , typename... _Args>
static auto substitute (const std::string &format, const T &val, const _Args &...args) -> std::string
Substitutes "{n}" tokens within the specified string with the respective arguments passed in.
template<typename T , typename... _Args>
static auto substituteSQL (const std::string &format, const T &value, const _Args &...args) -> std::string
Substitutes "{n}" tokens within the specified sql-string with the respective arguments passed in.
.
static auto isNumeric (const std::string &str) -> bool
Returns wheter the std::string represents Number or not
.
static auto toNumber (const std::string &str) -> double
Number std::string to Number having ',' symbols.
static auto numberFormat (double val, int precision=2) -> std::string
static auto percentFormat (double val, int precision=2) -> std::string
Returns a percentage string converted from the number rounded off from specified precision with "," symbols
ex) percentFormat(11.3391, 1) => 1,133.9%.
static auto colorNumberFormat (double value, int precision=2, double delimiter=0.0) -> std::string
Returns a string converted from the number rounded off from specified precision with "," symbols and color tag
ex) numberFormat(17151.339, 2) => <font color="red">17,151.34</font>
static auto colorPercentFormat (double value, int precision=2, double delimiter=0.0) -> std::string
Returns a percentage string converted from the number rounded off from specified precision with "," symbols
ex) percentFormat(11.3391, 1) => 1,133.9%.
static auto trim (const std::string &val, const std::vector< std::string > &delims) -> std::string
Removes all designated characters from the beginning and end of the specified string.
static auto ltrim (const std::string &val, const std::vector< std::string > &delims) -> std::string
Removes all designated characters from the beginning of the specified string.
static auto rtrim (const std::string &val, const std::vector< std::string > &delims) -> std::string
Removes all designated characters from the end of the specified string.
static auto finds (const std::string &str, const std::vector< std::string > &delims, size_t startIndex=0) -> IndexPair< std::string >
Finds first occurence in string.
static auto rfinds (const std::string &str, const std::vector< std::string > &delims, size_t endIndex=SIZE_MAX) -> IndexPair< std::string >
Finds last occurence in string.
static auto substring (const std::string &str, size_t startIndex, size_t endIndex=SIZE_MAX) -> std::string
Generates a substring.
static auto between (const std::string &str, const std::string &start="", const std::string &end="") -> std::string
Generate a substring.
static auto addTab (const std::string &str, size_t n=1) -> std::string
Adds tab() character to first position of each line.
static auto split (const std::string &str, const std::string &delim) -> std::vector< std::string >
Generates substrings.
static auto betweens (const std::string &str, const std::string &start="", const std::string &end="") -> std::vector< std::string >
Generates substrings.
static auto toLowerCase (const std::string &str) -> std::string
Returns a string that all uppercase characters are converted to lowercase.
static auto yoUpperCase (const std::string &str) -> std::string
static auto replaceAll (const std::string &str, const std::string &before, const std::string &after) -> std::string
Returns a string specified word is replaced.
static auto replaceAll (const std::string &str, const std::vector< std::pair< std::string, std::string >> &pairs) -> std::string
Returns a string specified words are replaced.
static auto removeHTMLSpaces (const std::string &str) -> std::string
Replace all HTML spaces to a literal space.
Detailed Description
Utility class for string.
StringUtil is an utility class providing lots of static methods for std::string.
There are two methods to strength std::string to have addictional uility methods like trim and split. The way of first is to make std::string class inheriting from std::string. The second is to make StringUtil class having static methods.
But those methods have problems. std::string class violates standard and StringUtil class violates principle of Object-Oriented Design. For the present, I've made the StringUtil class, but if you have a good opinion about the issue, please write your opinion on my github.
See also
library::WeakString
samchon::library
Author
Jeongho Nam http://samchon.org
Definition at line 36 of file StringUtil.hpp.
Member Function Documentation
template<typename T , typename... _Args> static auto samchon::library::StringUtil::substitute (const std::string & format, const T & val, const _Args &... args) -> std::string inline static
Substitutes "{n}" tokens within the specified string with the respective arguments passed in.
Parameters
format The string to make substitutions in.
This string can contain special tokens of the form {n}, where n is a zero based index, that will be replaced with the additional parameters found at that index if specified
val Target value to substitute the minimum {n} tokens
args Additional parameters that can be substituted in the str parameter at each {n} location, where n is an integer (zero based) index value into the varadics of values specified.
Returns
New string with all of the {n} tokens replaced with the respective arguments specified.
Definition at line 54 of file StringUtil.hpp.
Referenced by colorNumberFormat(), colorPercentFormat(), samchon::example::packer::Instance::toString(), samchon::example::tsp::GeometryPoint::toString(), and samchon::library::Date::toString().
template<typename T , typename... _Args> static auto samchon::library::StringUtil::substituteSQL (const std::string & format, const T & value, const _Args &... args) -> std::string inline static
Substitutes "{n}" tokens within the specified sql-string with the respective arguments passed in.
.
Warning
substituteSQL creates the dynamic sql-statement.
Not recommended when the dynamic sql-statement is not only for procedure.
Parameters
format The string to make substitutions in.
This string can contain special tokens of the form {n}, where n is a zero based index, that will be replaced with the additional parameters found at that index if specified
val Target value to substitute the minimum {n} tokens
args Additional parameters that can be substituted in the str parameter at each {n} location, where n is an integer (zero based) index value into the varadics of values specified.
Returns
New sql-string with all of the {n} tokens replaced with the respective arguments specified.
Definition at line 80 of file StringUtil.hpp.
References betweens(), samchon::WeakString::empty(), samchon::WeakString::find(), isNumeric(), samchon::library::Math::minimum(), replaceAll(), samchon::WeakString::replaceAll(), and samchon::WeakString::str().
static auto samchon::library::StringUtil::isNumeric (const std::string & str) -> bool inline static
Returns wheter the std::string represents Number or not
.
Parameters
str Target std::string to check
Returns
Whether the std::string can be converted to Number or not
Definition at line 198 of file StringUtil.hpp.
Referenced by substituteSQL().
static auto samchon::library::StringUtil::toNumber (const std::string & str) -> double inline static
Number std::string to Number having ',' symbols.
Parameters
str Target std::string you want to convert to Number
Returns
Number from std::string
Definition at line 223 of file StringUtil.hpp.
References replaceAll().
static auto samchon::library::StringUtil::numberFormat (double val, int precision = 2) -> std::string inline static
Returns a string converted from the number rounded off from specified precision with "," symbols ex) numberFormat(17151.339, 2) => 17,151.34
Parameters
val A number wants to convert to string
precision Target precision of roundoff
Returns
A string representing the number with roundoff and "," symbols
Definition at line 241 of file StringUtil.hpp.
Referenced by colorNumberFormat(), percentFormat(), and samchon::example::tsp::Travel::toString().
static auto samchon::library::StringUtil::percentFormat (double val, int precision = 2) -> std::string inline static
Returns a percentage string converted from the number rounded off from specified precision with "," symbols
ex) percentFormat(11.3391, 1) => 1,133.9%.
Warning
Do not multiply by 100 to the value representing percent
Parameters
val A number wants to convert to percentage string
precision Target precision of roundoff
Definition at line 291 of file StringUtil.hpp.
References numberFormat().
Referenced by colorPercentFormat().
static auto samchon::library::StringUtil::colorNumberFormat (double value, int precision = 2, double delimiter = 0.0) -> std::string inline static
Returns a string converted from the number rounded off from specified precision with "," symbols and color tag
ex) numberFormat(17151.339, 2) => <font color="red">17,151.34</font>
Which color would be chosen
Number is positive, color is RED
Number is zero (0), color is BLACK
Number is negative, color is BLUE
Parameters
val A number wants to convert to colored string
precision Target precision of roundoff
Returns
A colored string representing the number with roundoff and "," symbols
Definition at line 313 of file StringUtil.hpp.
References numberFormat(), and substitute().
static auto samchon::library::StringUtil::colorPercentFormat (double value, int precision = 2, double delimiter = 0.0) -> std::string inline static
Returns a percentage string converted from the number rounded off from specified precision with "," symbols
ex) percentFormat(11.3391, 1) => 1,133.9%.
Warning
Do not multiply by 100 to the value representing percent
Parameters
val A number wants to convert to percentage string
precision Target precision of roundoff
Definition at line 337 of file StringUtil.hpp.
References percentFormat(), and substitute().
static auto samchon::library::StringUtil::trim (const std::string & val, const std::vector< std::string > & delims) -> std::string inline static
Removes all designated characters from the beginning and end of the specified string.
Parameters
str The string should be trimmed
delims Designated character(s)
Returns
Updated string where designated characters was removed from the beginning and end
Definition at line 364 of file StringUtil.hpp.
Referenced by rtrim().
static auto samchon::library::StringUtil::ltrim (const std::string & val, const std::vector< std::string > & delims) -> std::string inline static
Removes all designated characters from the beginning of the specified string.
Parameters
str The string should be trimmed
delims Designated character(s)
Returns
Updated string where designated characters was removed from the beginning
Definition at line 376 of file StringUtil.hpp.
Referenced by rtrim().
static auto samchon::library::StringUtil::rtrim (const std::string & val, const std::vector< std::string > & delims) -> std::string inline static
Removes all designated characters from the end of the specified string.
Parameters
str The string should be trimmed
delims Designated character(s)
Returns
Updated string where designated characters was removed from the end
Definition at line 388 of file StringUtil.hpp.
References ltrim(), and trim().
static auto samchon::library::StringUtil::finds (const std::string & str, const std::vector< std::string > & delims, size_t startIndex = 0) -> IndexPair<std::string> inline static
Finds first occurence in string.
Finds first occurence position of each delim in the string after startIndex and returns the minimum position of them
If startIndex is not specified, then starts from 0.
If failed to find any substring, returns -1 (std::string::npos)
Parameters
str Target string to find
delims The substrings of target(str) which to find
startIndex Specified starting index of find. Default is 0
Returns
pair<size_t := position, string := matched substring>
Definition at line 437 of file StringUtil.hpp.
References samchon::WeakString::finds(), samchon::IndexPair< T >::get_index(), and samchon::IndexPair< T >::getValue().
static auto samchon::library::StringUtil::rfinds (const std::string & str, const std::vector< std::string > & delims, size_t endIndex = SIZE_MAX) -> IndexPair<std::string> inline static
Finds last occurence in string.
Finds last occurence position of each delim in the string before endIndex and returns the maximum position of them
If index is not specified, then starts str.size() - 1
If failed to find any substring, returns -1 (std::string::npos)
Parameters
str Target string to find
delims The substrings of target(str) which to find
endIndex Specified starting index of find. Default is str.size() - 1
Returns
pair<size_t := position, string := matched substring>
Definition at line 460 of file StringUtil.hpp.
References samchon::IndexPair< T >::get_index(), samchon::IndexPair< T >::getValue(), and samchon::WeakString::rfinds().
static auto samchon::library::StringUtil::substring (const std::string & str, size_t startIndex, size_t endIndex = SIZE_MAX) -> std::string inline static
Generates a substring.
Extracts a string consisting of the character specified by startIndex and all characters up to endIndex - 1 If endIndex is not specified, string::size() will be used instead.
If endIndex is greater than startIndex, then those will be swapped
Parameters
str Target string to be applied substring
startIndex Index of the first character.
If startIndex is greater than endIndex, those will be swapped
endIndex Index of the last character - 1.
If not specified, then string::size() will be used instead
Returns
Extracted string by specified index(es)
Definition at line 483 of file StringUtil.hpp.
References samchon::WeakString::substring().
static auto samchon::library::StringUtil::between (const std::string & str, const std::string & start = "", const std::string & end = "") -> std::string inline static
Generate a substring.
Extracts a substring consisting of the characters from specified start to end It's same with str.substring(? = (str.find(start) + start.size()), str.find(end, ?))
ex) between("ABCD[EFGH]IJK", "[", "]") => "EFGH"
If start is not specified, extracts from begin of the string to end.
If end is not specified, extracts from start to end of the string.
If start and end are all omitted, returns str, itself.
Parameters
str Target string to be applied between
start A string for separating substring at the front
end A string for separating substring at the end
Returns
substring by specified terms
Definition at line 508 of file StringUtil.hpp.
References samchon::WeakString::between().
static auto samchon::library::StringUtil::addTab (const std::string & str, size_t n = 1) -> std::string inline static
Adds tab() character to first position of each line.
Parameters
str Target str to add tabs
n The size of tab to be added for each line
Returns
A string added multiple tabs
Definition at line 522 of file StringUtil.hpp.
References split().
static auto samchon::library::StringUtil::split (const std::string & str, const std::string & delim) -> std::vector<std::string> inline static
Generates substrings.
Splits a string into an array of substrings by dividing the specified delimiter
Parameters
str Target string to split
delim The pattern that specifies where to split this string
Returns
An array of substrings
Definition at line 551 of file StringUtil.hpp.
References betweens(), and samchon::WeakString::split().
Referenced by addTab().
static auto samchon::library::StringUtil::betweens (const std::string & str, const std::string & start = "", const std::string & end = "") -> std::vector<std::string> inline static
Generates substrings.
Splits a string into an array of substrings dividing by specified delimeters of start and end. It's the array of substrings adjusted the between.
If startStr is omitted, it's same with the split by endStr not having last item
If endStr is omitted, it's same with the split by startStr not having first item
If startStr and endStar are all omitted, returns {str}
Parameters
str Target string to split by between
start A string for separating substring at the front. If omitted, it's same with split(end) not having last item
end A string for separating substring at the end. If omitted, it's same with split(start) not having first item
Returns
An array of substrings
Definition at line 581 of file StringUtil.hpp.
References samchon::WeakString::betweens().
Referenced by split(), and substituteSQL().
static auto samchon::library::StringUtil::toLowerCase (const std::string & str) -> std::string inline static
Returns a string that all uppercase characters are converted to lowercase.
Parameters
str Target string to convert uppercase to lowercase
Returns
A string converted to lowercase
Definition at line 605 of file StringUtil.hpp.
References samchon::WeakString::toLowerCase().
static auto samchon::library::StringUtil::yoUpperCase (const std::string & str) -> std::string inline static
Returns a string all lowercase characters are converted to uppercase
Parameters
str Target string to convert lowercase to uppercase
Returns
A string converted to uppercase
Definition at line 616 of file StringUtil.hpp.
References replaceAll(), and samchon::WeakString::yoUpperCase().
static auto samchon::library::StringUtil::replaceAll (const std::string & str, const std::string & before, const std::string & after) -> std::string inline static
Returns a string specified word is replaced.
Parameters
str Target string to replace
before Specific word you want to be replaced
after Specific word you want to replace
Returns
A string specified word is replaced
Definition at line 630 of file StringUtil.hpp.
References samchon::WeakString::replaceAll().
Referenced by removeHTMLSpaces(), substituteSQL(), toNumber(), and yoUpperCase().
static auto samchon::library::StringUtil::replaceAll (const std::string & str, const std::vector< std::pair< std::string, std::string >> & pairs) -> std::string inline static
Returns a string specified words are replaced.
Parameters
str Target string to replace
pairs A specific word's pairs you want to replace and to be replaced
Returns
A string specified words are replaced
Definition at line 645 of file StringUtil.hpp.
References samchon::WeakString::replaceAll().
static auto samchon::library::StringUtil::removeHTMLSpaces (const std::string & str) -> std::string inline static
Replace all HTML spaces to a literal space.
Parameters
str Target string to replace.
Definition at line 656 of file StringUtil.hpp.
References replaceAll().
The documentation for this class was generated from the following file:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/library/StringUtil.hpp