Samchon Framework for CPP: samchon::library::Date Class Reference
samchon::library::Date Class Reference
Date (year, month, day in month)
#include <Date.hpp>
Public Member Functions
Date ()
Default Constructor.
Date (const super &date)
Copy Constructor.
Date (super &&date)
Date (int year, int month, int date, int hour=0, int min=0, int sec=0)
Construct from date elements.
Date (const std::string &str)
Construct from string.
Date (long long linuxTime)
Construct from linux_time.
void set (const WeakString &wstr)
Setter by string.
void set (int year, int month, int date, int hour=0, int min=0, int sec=0)
Setter by elements of date.
void set (long long linuxTime)
Setter by linux_time.
auto getYear () const -> int
Get year of the Date.
auto getMonth () const -> int
Get month of the Date.
auto getDate () const -> int
Get the day in month of the Date.
auto getDay () const -> int
Get the day in week of the Date.
auto getHour () const -> int
Get hour.
auto getMinute () const -> int
Get minute.
auto getSecond () const -> int
Get second.
void setYear (int year)
Set year of the Date.
void setMonth (int month)
Set month of the Date.
void setDate (int val)
void setHour (int val)
Set hour.
void setMinute (int val)
Set minute.
void setSecond (int val)
Set hour.
void addYear (int val)
Add years to the Date.
void addMonth (int val)
Add months to the Date.
void addWeek (int val)
Add weeks to the Date.
void addDate (int val)
Add days to the Date.
void addHour (int val)
Add hours.
void addMinute (int val)
Add minutes.
void addSecond (int val)
Add seconds.
auto toTM () const -> struct::tm
Converts the Date to struct tm.
auto toLinuxTime () const -> long long
Converts the Date to linux_time.
auto toString () const -> std::string
Converts the Date to std::string.
Static Private Member Functions
static auto calc_seconds (int year, int month, int date) -> long long
Calculates how many seconds have flowen since 0000-01-01 00:00:00.
static auto calc_last_dates (int year) -> std::array< int, 12 >
Calculates and gets an array of final date of each month for that year.
Detailed Description
Date (year, month, day in month)
Date class is a chrono::time_point<std::chrono::system_clock>.
Date represents the date with year, month and day in month. The basic date (local time) is from your operating system.
[Inherited]
A time_point object expresses a point in time relative to a clock's epoch.
Internally, the object stores an object of a duration type, and uses the Clock type as a reference for its epoch.
Referenced comments of std::chrono::time_point
http://www.cplusplus.com/reference/chrono/time_point/
See also
samchon::library
Author
Jeongho Nam http://samchon.org
Definition at line 38 of file Date.hpp.
Constructor & Destructor Documentation
samchon::library::Date::Date () inline
Default Constructor.
The date will be now (Now's date from operating system)
Definition at line 96 of file Date.hpp.
Referenced by Date().
samchon::library::Date::Date (const super & date) inline
Copy Constructor.
Copy the date from another Date
Parameters
date Target to be copied
Definition at line 106 of file Date.hpp.
samchon::library::Date::Date (super && date) inline
Move Constructor
Gets the date from other and truncate the other
Parameters
date Target to be moved
Definition at line 116 of file Date.hpp.
samchon::library::Date::Date (int year, int month, int date, int hour = 0, int min = 0, int sec = 0) inline
Construct from date elements.
Parameters
year ex) 2015
month January to December. 1 ~ 12
date day in month. 1 ~ 31
Exceptions
invalid_argument month or date is invalid.
Definition at line 128 of file Date.hpp.
samchon::library::Date::Date (const std::string & str) inline
Construct from string.
Parameters
str A string represents the date. (1991-01-01)
Exceptions
invalid_argument month or date is invalid.
Definition at line 139 of file Date.hpp.
References Date().
samchon::library::Date::Date (long long linuxTime) inline
Construct from linux_time.
Parameters
linuxTime linux_time to be converted
Definition at line 154 of file Date.hpp.
Member Function Documentation
static auto samchon::library::Date::calc_seconds (int year, int month, int date) -> long long inline static private
Calculates how many seconds have flowen since 0000-01-01 00:00:00.
This static method is used for calculate the linux_time (since 1970-01-01 09:00:00)
Returns
linux_time of the Date
Definition at line 50 of file Date.hpp.
References calc_last_dates().
Referenced by set().
static auto samchon::library::Date::calc_last_dates (int year) -> std::array<int, 12> inline static private
Calculates and gets an array of final date of each month for that year.
Parameters
year The target year
Returns
Array of fianl date of each month for that year
Definition at line 74 of file Date.hpp.
Referenced by addMonth(), calc_seconds(), set(), and setMonth().
void samchon::library::Date::set (const WeakString & wstr) inline
Setter by string.
Parameters
str Y-m-d
Exceptions
invalid_argument month or date is invalid.
Definition at line 165 of file Date.hpp.
References samchon::WeakString::between(), samchon::WeakString::empty(), samchon::WeakString::find(), samchon::WeakString::split(), and samchon::WeakString::substr().
void samchon::library::Date::set (int year, int month, int date, int hour = 0, int min = 0, int sec = 0) inline
Setter by elements of date.
Parameters
year ex) 2015
month January to December. 1 ~ 12
date day in month. 1 ~ 31
Exceptions
invalid_argument month or date is invalid.
Definition at line 212 of file Date.hpp.
References calc_last_dates(), and calc_seconds().
void samchon::library::Date::set (long long linuxTime) inline
Setter by linux_time.
Parameters
linuxTime linux_time to be converted
Definition at line 233 of file Date.hpp.
auto samchon::library::Date::getYear () const -> int inline
Get year of the Date.
Returns
Year
Definition at line 252 of file Date.hpp.
References toTM().
Referenced by addMonth(), addYear(), setDate(), and setMonth().
auto samchon::library::Date::getMonth () const -> int inline
Get month of the Date.
Returns
Month as integer (1: January, 12: December)
Definition at line 263 of file Date.hpp.
References toTM().
Referenced by addMonth(), setDate(), and setYear().
auto samchon::library::Date::getDate () const -> int inline
Get the day in month of the Date.
Returns
Day in month (1 to 31)
Definition at line 274 of file Date.hpp.
References toTM().
Referenced by addMonth(), setMonth(), and setYear().
auto samchon::library::Date::getDay () const -> int inline
Get the day in week of the Date.
Returns
Day in week to integer (0: Sunday, 1: Monday, ..., 6: Saturday)
Definition at line 285 of file Date.hpp.
References toTM().
auto samchon::library::Date::getHour () const -> int inline
Get hour.
Returns
hour of the Date to integer
Definition at line 296 of file Date.hpp.
References toTM().
Referenced by setHour().
auto samchon::library::Date::getMinute () const -> int inline
Get minute.
Returns
minute of the Date to integer
Definition at line 307 of file Date.hpp.
References toTM().
Referenced by setMinute().
auto samchon::library::Date::getSecond () const -> int inline
Get second.
Returns
second of the Date to integer
Definition at line 318 of file Date.hpp.
References toTM().
Referenced by setSecond().
void samchon::library::Date::setYear (int year) inline
Set year of the Date.
If previous date is leaf month's expiration date and target year what you want is not leaf, the date will be 28
2000-02-29 -> setYear(2001) -> 2001-02-28
2001-02-28 -> setYear(2000) -> 2000-02-08
Parameters
val Target year
Definition at line 339 of file Date.hpp.
References getDate(), and getMonth().
Referenced by addYear().
void samchon::library::Date::setMonth (int month) inline
Set month of the Date.
If the expiration date of the month will be shrinked, the date will be changed to the expiration date
2000-03-31 -> setMonth(4) -> 2000-04-30
2007-08-31 -> setMonth(9) -> 2007-09-30
Parameters
val Target month (1 - 12)
Exceptions
invalid_argument month is out of range
Definition at line 371 of file Date.hpp.
References calc_last_dates(), getDate(), and getYear().
void samchon::library::Date::setDate (int val) inline
Set date of the Date
Parameters
val Target day in month
Exceptions
invalid_argument When date is over expiration date in month
Definition at line 396 of file Date.hpp.
References getMonth(), and getYear().
void samchon::library::Date::setHour (int val) inline
Set hour.
Parameters
val Target hour (0 - 23)
Exceptions
invalid_argument When hour is out of range
Definition at line 407 of file Date.hpp.
References addHour(), and getHour().
void samchon::library::Date::setMinute (int val) inline
Set minute.
Parameters
val Target minute (0 - 59)
Exceptions
invalid_argument When minute is out of range
Definition at line 418 of file Date.hpp.
References addMinute(), and getMinute().
void samchon::library::Date::setSecond (int val) inline
Set hour.
Parameters
val Target second (0 - 59)
Exceptions
invalid_argument When second is out of range
Definition at line 429 of file Date.hpp.
References addSecond(), and getSecond().
void samchon::library::Date::addYear (int val) inline
Add years to the Date.
Parameters
val Years to add
Definition at line 443 of file Date.hpp.
References getYear(), and setYear().
void samchon::library::Date::addMonth (int val) inline
Add months to the Date.
Not a matter to val is over 12. If the month is over 12, then years will be added.
Parameters
val Months to add
Definition at line 458 of file Date.hpp.
References calc_last_dates(), getDate(), getMonth(), and getYear().
void samchon::library::Date::addWeek (int val) inline
Add weeks to the Date.
Not a matter that val is too huge. If the adding weeks derives modification in month or year, then it will be.
Parameters
val Weeks to add
Definition at line 491 of file Date.hpp.
References addDate().
void samchon::library::Date::addDate (int val) inline
Add days to the Date.
Not a matter that val is too huge. If the adding dates derives modification in month or year, then it will be.
Parameters
val Days to add
Definition at line 505 of file Date.hpp.
References addHour().
Referenced by addWeek().
void samchon::library::Date::addHour (int val) inline
Add hours.
It's same with operator+=(chrono::hours(val))
Do not worry about the out of range of the hour(val) Parent items like date, month and years will be adjusted automatically.
Parameters
val hours to add
Definition at line 521 of file Date.hpp.
Referenced by addDate(), and setHour().
void samchon::library::Date::addMinute (int val) inline
Add minutes.
It's same with operator+=(chrono::minutes(val))
Do not worry about the out of range of the minutes(val) Parent items like date, month and years will be adjusted automatically.
Parameters
val minutes to add
Definition at line 537 of file Date.hpp.
Referenced by setMinute().
void samchon::library::Date::addSecond (int val) inline
Add seconds.
It's same with operator+=(chrono::seconds(val))
Do not worry about the out of range of the seconds(val) Parent items like date, month and years will be adjusted automatically.
Parameters
val seconds to add
Definition at line 554 of file Date.hpp.
Referenced by setSecond().
auto samchon::library::Date::toTM () const -> struct ::tm inline
Converts the Date to struct tm.
Returns
struct tm representing the Date
Definition at line 567 of file Date.hpp.
Referenced by getDate(), getDay(), getHour(), getMinute(), getMonth(), getSecond(), getYear(), and toString().
auto samchon::library::Date::toLinuxTime () const -> long long inline
Converts the Date to linux_time.
Returns
linux_time of the Date
Definition at line 581 of file Date.hpp.
auto samchon::library::Date::toString () const -> std::string inline
Converts the Date to std::string.
Returns
std::string expressing the Date
Definition at line 594 of file Date.hpp.
References samchon::library::StringUtil::substitute(), and toTM().
The documentation for this class was generated from the following file:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/library/Date.hpp