Samchon Framework for CPP: samchon::protocol::Entity Class Reference
samchon::protocol::Entity Class Reference abstract
An entity, a standard data class.
#include <Entity.hpp>
Public Member Functions
virtual auto TAG () const -> std::string=0
A tag name when represented by XML.
Entity ()
Default Constructor.
virtual void construct (std::shared_ptr< library::XML >)=0
Construct data of the Entity from an XML object.
virtual auto key () const -> std::string
Get a key that can identify the Entity uniquely.
virtual auto toXML () const -> std::shared_ptr< library::XML >
Get an XML object represents the Entity.
Detailed Description
An entity, a standard data class.
Entity is a class for standardization of expression method using on network I/O by XML. If Invoke is a standard message protocol of Samchon Framework which must be kept, Entity is a recommended semi-protocol of message for expressing a data class. Following the semi-protocol Entity is not imposed but encouraged.
As we could get advantages from standardization of message for network I/O with Invoke, we can get additional advantage from standardizing expression method of data class with Entity. We do not need to know a part of network communication. Thus, with the Entity, we can only concentrate on entity's own logics and relationships between another entities. Entity does not need to how network communications are being done.
Example source
 #include <iostream>
 #include <samchon/protocol/Entity.hpp>
 #include <samchon/protocol/IHTMLEntity.hpp>
 #include <samchon/protocol/SharedEntityArray.hpp>
 #include <samchon/library/XML.hpp>
 #ifdef _WIN64
 #   ifdef _DEBUG
 #       pragma comment(lib, "x64/Debug/SamchonFramework.lib")
 #   else
 #       pragma comment(lib, "x64/Release/SamchonFramework.lib")
 #   endif
 #else
 #   ifdef _DEBUG
 #       pragma comment(lib, "Debug/SamchonFramework.lib")
 #   else
 #       pragma comment(lib, "Release/SamchonFramework.lib")
 #   endif
 #endif
 using namespace std;
 using namespace samchon::library;
 using namespace samchon::protocol;
 class Member
     : public Entity, public virtual IHTMLEntity
 {
 protected:
     typedef Entity super;
     string id;
     string name;
     int age;
     int grade;
 public:
     /* ---------------------------------------------------------------------
         CONSTRUCTORS
     --------------------------------------------------------------------- */
     Member()
         : super(), IHTMLEntity()
     {
     };
     Member(const string &id, const string &name, int age, int grade)
         : super(), IHTMLEntity()
     {
         this->id = id;
         this->name = name;
         this->age = age;
         this->grade = grade;
     };
     virtual ~Member() = default;
     virtual void construct(shared_ptr<XML> xml) override
     {
         this->id = xml->getProperty("id");
         this->name = xml->getProperty("name");
         this->age = xml->getProperty<int>("age");
         this->grade = xml->getProperty<int>("grade");
     };
     /* ---------------------------------------------------------------------
         GETTERSs
     --------------------------------------------------------------------- */
     virtual auto key() const -> std::string override
     {
         return this->id;
     };
     /* ---------------------------------------------------------------------
         XML EXPORTERS
     --------------------------------------------------------------------- */
     virtual auto TAG() const -> string override
     {
         return "member";
     };
     virtual auto toXML() const -> shared_ptr<XML>
     {
         shared_ptr<XML> &xml = super::toXML();
         xml->setProperty("id", id);
         xml->setProperty("name", name);
         xml->setProperty("age", age);
         xml->setProperty("grade", grade);
         return move(xml);
     };
     virtual auto toHTML() const -> string
     {
         return toTR(id, name, age, grade);
     };
 };
 class MemberArray
     : public SharedEntityArray<Member>,
     public virtual IHTMLEntity
 {
 protected:
     typedef SharedEntityArray<Member> super;
     string application;
     int department;
     Member *chief;
 public:
     /* ---------------------------------------------------------------------
         CONSTRUCTORS
     --------------------------------------------------------------------- */
     MemberArray()
         : super(), IHTMLEntity()
     {
         this->chief = nullptr;
     };
     virtual ~MemberArray() = default;
     // You don't need to consider children(Member) objects
     // Just concentrate on constructing MemberArray's own member variables
     virtual void construct(shared_ptr<XML> xml) override
     {
         super::construct(xml);
         this->application = xml->getProperty("application");
         this->department = xml->getProperty<int>("department");
         if(xml->hasProperty("chief") == true && this->has( xml->getProperty("chief") ) == true)
             this->chief = this->get( xml->getProperty("cheif") ).get();
     };
 protected:
     //FACTORY METHOD FOR MEMBER
     virtual auto createChild(shared_ptr<XML> = nullptr) -> Member* override
     {
         return new Member();
     };
     /* ---------------------------------------------------------------------
         XML EXPORTERS
     --------------------------------------------------------------------- */
 public:
     virtual auto TAG() const -> string override
     {
         return "memberArray";
     };
     virtual auto CHILD_TAG() const -> string override
     {
         return "member";
     };
     // You don't need to consider children(Member) objects
     // Just concentrate on expressing MemberArray's own member variables
     virtual auto toXML() const -> shared_ptr<XML>
     {
         shared_ptr<XML> &xml = super::toXML();
         xml->setProperty("application", application);
         xml->setProperty("department", department);
         if(chief != nullptr)
             xml->setProperty("cheif", chief->key());
         return move(xml);
     };
     virtual auto toHTML() const -> string
     {
         string html = "<table>\n";
         html += toTH("ID", "Name", "Age", "Grade") + "\n";
         for (size_t i = 0; i < 2; i++)
             html += at(i)->toHTML() + "\n";
         html += "</table>";
         return move(html);
     };
 };
 void main()
 {
     string str = string("") +
         "<memberArray application='framework' department='7' cheif='samchon'>\n" +
         "   <member id='samchon' name='Jeongho Nam' age='27' grade='5' />" +
         "   <member id='submaster' name='No Name' age='100' grade='4' />" +
         "   <member id='john' name='John Doe' age='33' grade='2' />" +
         "   <member id='bad_man' name='Bad Man' age='44' grade='-1' />" +
         "   <member id='guest' name='Guest' age='0' grade='0' />" +
         "</memberArray>";
     shared_ptr<XML> xml(new XML(str));
     MemberArray memberArray;
     memberArray.construct(xml);
     memberArray.emplace_back(new Member("freshman", "A fresh man", 20, 2));
     memberArray.emplace_back(new Member("senior", "A senior", 70, 2));
     cout << memberArray.toXML()->toString() << endl << endl;
     cout << memberArray.toHTML() << endl;
     system("pause");
 }
Result of the example
Note
I say repeatedly. Expression method of Entity is recommended, but not imposed. It's a semi protocol for network I/O but not a essential protocol must be kept. The expression method of Entity, using on network I/O, is expressed by XML string.
If your own network system has a critical performance issue on communication data class, it would be better to using binary communication (with ByteArray or boost::serialization). Don't worry about the problem! Invoke also provides methods for binary data (ByteArray).
See also
protocol
Author
Jeongho Nam
Definition at line 52 of file Entity.hpp.
Constructor & Destructor Documentation
Entity::Entity ()
Default Constructor.
Definition at line 20 of file Entity.cpp.
Member Function Documentation
virtual auto samchon::protocol::Entity::TAG () const -> std::string pure virtual
A tag name when represented by XML.
Returns
A tag name
Implemented in samchon::protocol::InvokeParameter, samchon::protocol::InvokeHistory, samchon::protocol::Invoke, samchon::namtree::NTCriteria, samchon::protocol::ExternalSystemArray, samchon::protocol::ExternalSystem, samchon::protocol::ExternalSystemRole, samchon::namtree::NTParameter, samchon::namtree::NTParameterDetermined, samchon::protocol::SystemRole, samchon::protocol::master::ParallelSlaveSystemMediator, samchon::protocol::master::DistributedSlaveSystemMediator, samchon::example::chat_service::ChatRoom, samchon::namtree::NTSide, samchon::protocol::InvokeHistoryArray, samchon::namtree::NTParameterArray, samchon::example::chat_service::ChatMessage, and samchon::library::FTInstance.
void Entity::construct (std::shared_ptr< library::XML >) pure virtual
Construct data of the Entity from an XML object.
Overrides the construct() method and fetch data of member variables from the XML.
By recommended guidance, data representing member variables are contained in properties of the put XML object.
Parameters
xml An xml used to construct data of entity
Implemented in samchon::protocol::InvokeParameter, samchon::protocol::master::DistributedSystem, samchon::namtree::NTCriteria, samchon::namtree::NTFile, samchon::protocol::InvokeHistory, samchon::protocol::EntityGroup< _Container, _ETy, _Ty >, samchon::protocol::EntityGroup< _Container, std::unique_ptr< Entity > >, samchon::protocol::EntityGroup< _Container, std::shared_ptr< Entity > >, samchon::protocol::EntityGroup< _Container, Entity * >, samchon::protocol::master::ParallelSystem, samchon::protocol::EntityList< _Ty >, samchon::protocol::ExternalSystem, samchon::protocol::ExternalSystemRole, samchon::protocol::EntityArray< _Ty >, samchon::protocol::Invoke, samchon::protocol::master::PRInvokeHistory, samchon::protocol::master::DistributedSystemArray, samchon::example::chat_service::ChatMessage, samchon::namtree::INTExplore, samchon::namtree::NTParameterDetermined, samchon::protocol::master::ParallelSystemArrayMediator, samchon::protocol::master::DistributedSystemArrayMediator, samchon::namtree::NTParameter, samchon::protocol::SystemRole, samchon::namtree::NTSide, samchon::protocol::ExternalClientArray, samchon::protocol::ExternalServer, samchon::protocol::master::DistributedClientArrayMediator, samchon::protocol::master::ParallelClientArrayMediator, samchon::protocol::master::DistributedClientArray, samchon::protocol::master::DistributedServer, and samchon::protocol::master::ParallelServer.
Definition at line 23 of file Entity.cpp.
Referenced by samchon::protocol::EntityGroup< _Container, Entity * >::construct().
auto Entity::key () const -> std::string virtual
Get a key that can identify the Entity uniquely.
If identifier of the Entity is not atomic value, returns a string represents the composite identifier. If identifier of the Entity is not string, converts the identifier to string and returns the string.
Returns
An identifier
Reimplemented in samchon::protocol::InvokeParameter, samchon::protocol::InvokeHistory, samchon::protocol::ExternalSystem, samchon::protocol::ExternalSystemRole, samchon::library::FTInstance, samchon::namtree::NTParameter, samchon::namtree::NTParameterDetermined, and samchon::protocol::SystemRole.
Definition at line 15 of file Entity.cpp.
Referenced by samchon::protocol::EntityGroup< _Container, Entity * >::get(), and samchon::protocol::EntityGroup< _Container, Entity * >::has().
auto Entity::toXML () const -> std::shared_ptr<library::XML> virtual
Get an XML object represents the Entity.
Returns an XML object that can represents the Entity containing member variables into properties.
A member variable (not object, but atomic value like number, string or date) is categorized as a property within the framework of entity side. Thus, when overriding a toXML() method and archiving member variables to an XML object to return, puts each variable to be a property belongs to only an XML object.
Don't archive the member variable of atomic value to XML::value causing enormouse creation of XML objects to number of member variables. An Entity must be represented by only an XML instance (tag).
Standard Usage Non-standard usage abusing value
<memberList>
<member id='jhnam88' name='Jeongho+Nam' birthdate='1988-03-11' />
<member id='master' name='Administartor' birthdate='2011-07-28' />
</memberList> <member>
<id>jhnam88</id>
<name>Jeongho+Nam</name>
<birthdate>1988-03-11</birthdate>
</member>
Returns
An XML object representing the Entity.
Reimplemented in samchon::protocol::InvokeParameter, samchon::protocol::EntityGroup< _Container, _ETy, _Ty >, samchon::protocol::EntityGroup< _Container, std::unique_ptr< Entity > >, samchon::protocol::EntityGroup< _Container, std::shared_ptr< Entity > >, samchon::protocol::EntityGroup< _Container, Entity * >, samchon::protocol::InvokeHistory, samchon::protocol::Invoke, samchon::protocol::master::DistributedSystem, samchon::namtree::NTCriteria, samchon::namtree::NTFile, samchon::protocol::ExternalSystem, samchon::protocol::ExternalSystemRole, samchon::protocol::master::ParallelSystem, samchon::protocol::master::DistributedSystemArray, samchon::protocol::EntityList< _Ty >, samchon::protocol::master::DistributedSystemRole, samchon::protocol::EntityArray< _Ty >, samchon::example::chat_service::ChatRoom, samchon::protocol::master::PRInvokeHistory, samchon::library::FTInstance, samchon::namtree::INTExplore, samchon::namtree::NTParameter, samchon::namtree::NTParameterDetermined, samchon::example::chat_service::ChatMessage, samchon::protocol::master::DistributedSystemArrayMediator, samchon::protocol::master::ParallelSystemArrayMediator, samchon::protocol::SystemRole, samchon::protocol::ExternalClientArray, samchon::protocol::ExternalServer, samchon::library::FTFolder, samchon::namtree::NTSide, samchon::library::FTFile, samchon::protocol::master::DSInvokeHistory, samchon::protocol::master::DistributedClientArrayMediator, samchon::protocol::master::ParallelClientArrayMediator, samchon::protocol::master::DistributedClientArray, samchon::protocol::master::DistributedServer, and samchon::protocol::master::ParallelServer.
Definition at line 30 of file Entity.cpp.
Referenced by samchon::namtree::NTSide::toXML(), samchon::protocol::SystemRole::toXML(), samchon::example::chat_service::ChatMessage::toXML(), samchon::namtree::NTParameterDetermined::toXML(), samchon::namtree::INTExplore::toXML(), samchon::library::FTInstance::toXML(), samchon::example::chat_service::ChatRoom::toXML(), samchon::protocol::EntityArray< _Ty >::toXML(), samchon::protocol::EntityList< _Ty >::toXML(), samchon::protocol::ExternalSystemRole::toXML(), samchon::protocol::InvokeHistory::toXML(), samchon::protocol::EntityGroup< _Container, Entity * >::toXML(), and samchon::protocol::InvokeParameter::toXML().
The documentation for this class was generated from the following files:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/protocol/Entity.hpp
D:/OneDrive/Project/Samchon/framework/cpp/samchon/protocol/Entity.cpp