Samchon Framework for CPP: samchon::library::IOperator< T > Class Template Reference
samchon::library::IOperator< T > Class Template Reference abstract
Interface for comparision operator.
#include <IOperator.hpp>
Public Member Functions
IOperator ()
Default Constructor.
virtual auto operator< (const IOperator &) const -> bool=0
Less.
virtual auto operator== (const IOperator &) const -> bool=0
Equal.
Detailed Description
template<typename T>
class samchon::library::IOperator< T >
Interface for comparision operator.
IOperator is a template class makes enalbe to realizing all compare operators by only overriding operator< and operator== methods.
[!=] -> [NOT ==]
[<=] -> [< OR ==]
[>] -> [NOT < AND NOT ==]
[>=] -> [NOT <]
Methods operator< and operator== are abstract. Overrides them.
Note
If you want to realize all comparison operators without inheritance and specifying clear type of parameter, you can use following macros instead.
OPERATOR_METHODS_INLINE(_Ty)
OPERATOR_METHODS_HEADER(_Ty)
OPERATOR_METHODS_BODY(_Class, _Ty)
See also
samchon::library
Author
Jeongho Nam http://samchon.org
Definition at line 122 of file IOperator.hpp.
Constructor & Destructor Documentation
template<typename T> samchon::library::IOperator< T >::IOperator () inline
Default Constructor.
Definition at line 128 of file IOperator.hpp.
References samchon::library::IOperator< T >::operator<(), and samchon::library::IOperator< T >::operator==().
Member Function Documentation
template<typename T> virtual auto samchon::library::IOperator< T >::operator< (const IOperator< T > &) const -> bool pure virtual
Less.
Overrides method less.
Parameters
obj The object to compare.
Returns
The object is less than this.
Referenced by samchon::library::IOperator< T >::IOperator().
template<typename T> virtual auto samchon::library::IOperator< T >::operator== (const IOperator< T > &) const -> bool pure virtual
Equal.
Overrides methods equal.
Parameters
obj The object to compare.
Returns
The object is equal with this.
Referenced by samchon::library::IOperator< T >::IOperator().
The documentation for this class was generated from the following file:
D:/OneDrive/Project/Samchon/framework/cpp/samchon/library/IOperator.hpp